### PR TITLE
fix(logger): correct log level verbosity in rule evaluation

### LINKED ISSUE #19320: Info logs even when log level set to 'error'
**Describe the bug**
Seeing these 4 log lines with 'level=info' even though my config has the log level set to 'error':

`Sep 25 17:51:42 loki-linux-amd64[54032]: level=info msg="request timings" insight=true source=loki_ruler rule_name=MethodAborted rule_type=alerting total=0.005327964 total_bytes=164428 query_hash=940180731
Sep 25 17:51:42 loki-linux-amd64[54032]: level=info msg="request timings" insight=true source=loki_ruler rule_name=BadResearchRelease rule_type=alerting total=0.005206615 total_bytes=164428 query_hash=796802455
Sep 25 17:51:42 loki-linux-amd64[54032]: level=info msg="request timings" insight=true source=loki_ruler rule_name=NotifyUser rule_type=alerting total=0.005696506 total_bytes=164428 query_hash=1646277714
Sep 25 17:51:42 loki-linux-amd64[54032]: level=info msg="request timings" insight=true source=loki_ruler rule_name=MethodPaused rule_type=alerting total=0.005959446 total_bytes=164428 query_hash=3140296105
`
**To Reproduce**
Launch Loki. Get these 4 logs every minute

**Expected behavior**
Not getting info logs when log level is error

**Environment:**
 - Infrastructure: bare metal
 - Deployment tool: systemd

### PR DESCRIPTION
**Pull request by steffsas**
**What this PR does / why we need it**:
This PR fixes incorrect log level verbosity in rule evaluation, as described in #19320.

**Which issue(s) this PR fixes**:
Fixes #19320

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

File: pkg/ruler/evaluator_local.go [hunk 1]
```diff
@@ -32,7 +32,11 @@ func NewLocalEvaluator(engine *logql.QueryEngine, logger log.Logger) (*LocalEval
 		return nil, fmt.Errorf("given engine is nil")
 	}
 
-	return &LocalEvaluator{engine: engine, logger: logger, insightsLogger: log.NewLogfmtLogger(os.Stderr)}, nil
+	return &LocalEvaluator{
+		engine:         engine,
+		logger:         logger,
+		insightsLogger: log.With(util_log.Logger, "msg", "request timings", "insight", "true", "source", "loki_ruler"),
```
Comment (chaudum) [inline pkg/ruler/evaluator_local.go:38]: Is the `logger` that is passed to the constructor configured differently than `util_log.Logger`? I would expect them to be the same

```suggestion
		logger:         logger,
		insightsLogger: log.With(logger, "msg", "request timings", "insight", "true", "source", "loki_ruler"),
```

File: pkg/ruler/evaluator_remote.go [hunk 2]
```diff
@@ -85,7 +85,7 @@ func NewRemoteEvaluator(client httpgrpc.HTTPClient, overrides RulesLimits, logge
 		client:         client,
 		overrides:      overrides,
 		logger:         logger,
-		insightsLogger: log.NewLogfmtLogger(os.Stderr),
+		insightsLogger: log.With(util_log.Logger, "msg", "request timings", "insight", "true", "source", "loki_ruler", "rule_name"),
```
Comment (chaudum) [inline pkg/ruler/evaluator_remote.go:88]: Same here


```suggestion
		insightsLogger: log.With(logger, "msg", "request timings", "insight", "true", "source", "loki_ruler", "rule_name"),
```

File: pkg/ruler/evaluator_local.go (hunk 1 above)
Comment (steffsas) [reply pkg/ruler/evaluator_local.go:38]: `util_log.Logger` respects log level set in Loki's configuration file via `server.log_level: warn`, for example. In contrast, `github.com/go-kit/log` does not read the configuration file. Instead, it solely uses environment variables to determine its log level.

See for example https://github.com/grafana/loki/blob/cfd07c36833160e292369d807bc943614478cf44/pkg/util/log/log.go#L40-L47

File: pkg/ruler/evaluator_remote.go (hunk 2 above)
Comment (steffsas) [reply pkg/ruler/evaluator_remote.go:88]: see https://github.com/grafana/loki/pull/19519#discussion_r2435757433

File: pkg/ruler/evaluator_local.go (hunk 1 above)
Comment (chaudum) [reply pkg/ruler/evaluator_local.go:38]: Exactly, the problem is the "insights logger" (`insightsLogger: log.NewLogfmtLogger(os.Stderr)`), not the regular `logger`.

The regular logger is a `util_log.Logger` instance.

So, why not use `logger` that is passed to `NewLocalEvaluator` for both regular and insight logging?

Comment (chaudum) [reply pkg/ruler/evaluator_local.go:38]: Ah, now I see.

```
	// we don't want/need to log all the additional context, such as
	// caller=spanlogger.go:116 component=ruler evaluation_mode=remote method=ruler.remoteEvaluation.Query
	// in insights logs, so create a new logger
	insightsLogger log.Logger
```

Ok, then it makes sense to initialize a new logger.
