### PR TITLE
Fluent-bit: Fix panic error when AutoKubernetesLabels is true

### LINKED ISSUE #1524: encounter panic when turning on AutoKubernetesLabels
**Describe the bug**
When turning on AutoKubernetesLabels, fluent-bit log returns panic as follow

**Expected behavior**
Successfully see all logs in Loki

**Environment:**
 - Infrastructure: minikube v1.6.2
 - Deployment tool: kustomize

**Screenshots, Promtail config, or terminal output**

kubectl logs output
```
[2020/01/15 08:28:55] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443
[2020/01/15 08:28:55] [ info] [filter_kube] local POD info OK
[2020/01/15 08:28:55] [ info] [filter_kube] testing connectivity with API server...
[2020/01/15 08:28:55] [ info] [filter_kube] API server connectivity OK
[2020/01/15 08:28:55] [ info] [sp] stream processor started
panic: interface conversion: interface {} is map[string]interface {}, not map[interface {}]interface {}
```

fluent-bit.conf:

```
[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
  Name tail
  Path /var/log/containers/*.log
  Parser docker
  Tag kube.*
  Refresh_Interval 5
  Mem_Buf_Limit 5MB
  Skip_Long_Lines On
  DB /run/fluent-bit/flb_kube.db

[INPUT]
  Name systemd
  Tag host.*
  Systemd_Filter _SYSTEMD_UNIT=docker.service
  Systemd_Filter _SYSTEMD_UNIT=kubelet.service
  Systemd_Filter _SYSTEMD_UNIT=node-problem-detector.service
  Max_Entries 1000
  Read_From_Tail true
  Strip_Underscores false

[FILTER]
  Name kubernetes
  Match kube.*
  Kube_Tag_Prefix kube.var.log.containers.
  Kube_URL https://kubernetes.default.svc:443
  Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
  Merge_Log On
  K8S-Logging.Parser Off

[OUTPUT]
  Name loki
  Match kube.*
  Url http://loki.gohub-gohub.svc:3100/api/prom/push
  # Labels {job="fluent-bit"}
  # RemoveKeys kubernetes,stream
  AutoKubernetesLabels true
  # LabelMapPath /fluent-bit/etc/labelmap.json
  # LineFormat json
  # LogLevel warn
```

parsers.conf:

```
[PARSER]
  Name         docker
  Format       json
  Time_Key     time
  Time_Format  %Y-%m-%dT%H:%M:%S.%L
```

### PR DESCRIPTION
**Pull request by adityacs**
**What this PR does / why we need it**:
Fluent-bit: Fix panic error when AutoKubernetesLabels is true

**Which issue(s) this PR fixes**:
Fixes #1524 

**Checklist**
- [x] Tests updated

### CODE REVIEW

File: cmd/fluent-bit/loki.go [hunk 1]
```diff
@@ -81,35 +80,28 @@ func toStringMap(record map[interface{}]interface{}) map[string]interface{} {
...
 	return m
 }
 
 func autoLabels(records map[string]interface{}) model.LabelSet {
 	kuberneteslbs := model.LabelSet{}
 	replacer := strings.NewReplacer("/", "_", ".", "_", "-", "_")
-	for k, v := range records["kubernetes"].(map[interface{}]interface{}) {
-		switch key := k.(string); key {
+	for k, v := range records["kubernetes"].(map[string]interface{}) {
+		switch key := k; key {
```
Comment (cyriltovena) [inline cmd/fluent-bit/loki.go]: You don't need to create a new `key` variable here ?

File: cmd/fluent-bit/loki.go [hunk 2]
```diff
@@ -81,35 +80,28 @@ func toStringMap(record map[interface{}]interface{}) map[string]interface{} {
...
 		case "labels":
-			for m, n := range v.(map[interface{}]interface{}) {
-				switch t := n.(type) {
-				case []byte:
-					kuberneteslbs[model.LabelName(replacer.Replace(m.(string)))] = model.LabelValue(string(t))
-				default:
-					kuberneteslbs[model.LabelName(replacer.Replace(m.(string)))] = model.LabelValue(fmt.Sprintf("%v", n))
-				}
+			fmt.Println("inside for loop labels")
```
Comment (cyriltovena) [inline cmd/fluent-bit/loki.go]: Can you remove the print.

File: cmd/fluent-bit/loki_test.go [hunk 3]
```diff
@@ -299,3 +299,47 @@ func Test_labelMapping(t *testing.T) {
...
+				},
+			},
+			model.LabelSet{
+				"foo": "buzz",
+			},
+		},
+		{
+			"records with labels",
+			map[interface{}]interface{}{
+				"kubernetes": map[string]interface{}{
```
Comment (cyriltovena) [inline cmd/fluent-bit/loki_test.go]: Can you add a test without kubernetes key basically an empty map. I have a feeling it will fail.

Comment (adityacs) [reply cmd/fluent-bit/loki_test.go]: Yes definitely it will fail. We should check if `kubernetes` key is present when `AutoKubernetesLabels` is turned on. Will add that logic

Comment (cyriltovena) [reply cmd/fluent-bit/loki_test.go]: you can just `kube,ok := records["kubernetes"]` and skip if the key is missing.

Comment (adityacs) [reply cmd/fluent-bit/loki_test.go]: With current logic, if autokuberneteslabels is on, then no other labels will be extracted. So, we will have entries with empty labels. This would not be desired behaviour. 
May be we should check `kube,ok := records["kubernetes"]` here https://github.com/grafana/loki/blob/master/cmd/fluent-bit/loki.go#L44 before we call `autokuberneteslabels` . If `!ok` do `lbs = extractLabels(records, l.cfg.labelKeys)` https://github.com/grafana/loki/blob/master/cmd/fluent-bit/loki.go#L48

Comment (cyriltovena) [reply cmd/fluent-bit/loki_test.go]: I think the current implementation is fine, but add a test for error case.

Comment (adityacs) [reply cmd/fluent-bit/loki_test.go]: updated my code. Also, added test case for missing k8s key

File: cmd/fluent-bit/loki.go [hunk 4]
```diff
@@ -81,36 +84,32 @@ func toStringMap(record map[interface{}]interface{}) map[string]interface{} {
...
+
 	return m
 }
 
-func autoLabels(records map[string]interface{}) model.LabelSet {
-	kuberneteslbs := model.LabelSet{}
+func autoLabels(records map[string]interface{}, kuberneteslbs model.LabelSet) error {
+	kube, ok := records["kubernetes"]
+	if !ok {
+		return errors.New("Kubernetes labels not found, no labels will be added")
```
Comment (cyriltovena) [inline cmd/fluent-bit/loki.go]: We should capitalized error message.

Comment (adityacs) [reply cmd/fluent-bit/loki.go]: Done. Removed capitalization

**Comment by adityacs** [comment]
@cyriltovena done
