### PR TITLE
Fix panic in labels debug message

### LINKED ISSUE #1680: Promtail: Nil pointer reference, when parsing JSON logs
**Describe the bug**
I am trying to parse JSON logs with a pipeline in JSON. The JSON maps do not all have the same set of keys, e.g. the 'exception'-key is only present in a few logs. When I know want to extract the 'exception'- key-value pair and use it later on in the pipeline, e.g. to set it as a label, Promtail panics when trying to set the label, when the key did not exist in the JSON. Promatil gives me the following exception:

```
level=debug ts=2020-02-12T14:44:36.069455Z caller=pipeline.go:91 component=file_pipeline component=pipeline msg="processing pipeline" stage=0 name=json labels="{filename=\"/tmp/logs/log.json\", job=\"gerrit_error\"}" time=2020-02-12T15:44:36.06937+01:00 entry="{\"name\":\"test1\"}"
level=debug ts=2020-02-12T14:44:36.069974Z caller=pipeline.go:91 component=file_pipeline component=pipeline msg="processing pipeline" stage=1 name=labels labels="{filename=\"/tmp/logs/log.json\", job=\"gerrit_error\"}" time=2020-02-12T15:44:36.06937+01:00 entry="{\"name\":\"test1\"}"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x1a4beb0]

goroutine 259 [running]:
github.com/grafana/loki/pkg/logentry/stages.(*labelStage).Process(0xc00042fda0, 0xc0004eb710, 0xc0004eb740, 0xc0000ce6a0, 0xc000596370)
	/src/loki/pkg/logentry/stages/labels.go:71 +0x230
github.com/grafana/loki/pkg/logentry/stages.(*Pipeline).Process(0xc00009de80, 0xc0004eb710, 0xc0004eb740, 0xc0000ce6a0, 0xc000596370)
	/src/loki/pkg/logentry/stages/pipeline.go:93 +0x213
github.com/grafana/loki/pkg/logentry/stages.(*Pipeline).Wrap.func1(0xc0004eb710, 0xbf8921b504228090, 0x12c5bb147, 0x48be9e0, 0xc000584020, 0x10, 0x0, 0xffffffffffffffff)
	/src/loki/pkg/logentry/stages/pipeline.go:113 +0x101
github.com/grafana/loki/pkg/promtail/api.EntryHandlerFunc.Handle(0xc00042fde0, 0xc0004eb710, 0xbf8921b504228090, 0x12c5bb147, 0x48be9e0, 0xc000584020, 0x10, 0x203000, 0xc0004eb6e0)
	/src/loki/pkg/promtail/api/types.go:19 +0x65
github.com/grafana/loki/pkg/promtail/api.AddLabelsMiddleware.func1.1(0xc0004eb6e0, 0xbf8921b504228090, 0x12c5bb147, 0x48be9e0, 0xc000584020, 0x10, 0x0, 0x0)
	/src/loki/pkg/promtail/api/types.go:40 +0xa3
github.com/grafana/loki/pkg/promtail/api.EntryHandlerFunc.Handle(0xc0002460a0, 0xc0004eb6e0, 0xbf8921b504228090, 0x12c5bb147, 0x48be9e0, 0xc000584020, 0x10, 0xc0006e3d98, 0x0)
	/src/loki/pkg/promtail/api/types.go:19 +0x65
github.com/grafana/loki/pkg/promtail/api.AddLabelsMiddleware.func1.1(0xc0004eb6b0, 0xbf8921b504228090, 0x12c5bb147, 0x48be9e0, 0xc000584020, 0x10, 0x2fd8700, 0xc0004eb6b0)
	/src/loki/pkg/promtail/api/types.go:40 +0xa3
github.com/grafana/loki/pkg/promtail/api.EntryHandlerFunc.Handle(0xc000246300, 0xc0004eb6b0, 0xbf8921b504228090, 0x12c5bb147, 0x48be9e0, 0xc000584020, 0x10, 0x0, 0x0)
	/src/loki/pkg/promtail/api/types.go:19 +0x65
github.com/grafana/loki/pkg/promtail/targets.(*tailer).run(0xc0000c2720)
	/src/loki/pkg/promtail/targets/tailer.go:109 +0x47d
created by github.com/grafana/loki/pkg/promtail/targets.newTailer
	/src/loki/pkg/promtail/targets/tailer.go:74 +0x493
```

**To Reproduce**
1. Have a json log file:

```
{"name":"test1"}
{"name":"test2", "exception":"foo"}
```

2. Have a Promtail pipeline like:

```
  - json:
      expressions:
        name:
        exception:
  - labels:
      exception:
```

3. Start Promtail (1.3.0) to tail 'log.json'

**Expected behavior**
I would expect Promtail to skip non-existing key-value pairs in logs (maybe printing a warning). Thus, in the example above, I would get the label `exception` for the second, but not the first log entry, or at least have the label for the first entry set to `"nil"` or something similar.

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: binary

**Screenshots, Promtail config, or terminal output**
see description above.

### PR DESCRIPTION
**Pull request by adityacs**
Just a placeholder for now. Need to test more

**What this PR does / why we need it**:
Fix panic in labels debug message

**Which issue(s) this PR fixes**:
Fixes #1680

### CODE REVIEW

**Comment by adityacs** [comment]
Just a placeholder for now. Need to test more

File: pkg/logentry/stages/labels.go [hunk 1]
```diff
@@ -68,7 +68,7 @@ func (l *labelStage) Process(labels model.LabelSet, extracted map[string]interfa
 			s, err := getString(lValue)
 			if err != nil {
 				if Debug {
-					level.Debug(l.logger).Log("msg", "failed to convert extracted label value to string", "err", err, "type", reflect.TypeOf(lValue).String())
+					level.Debug(l.logger).Log("msg", "failed to convert extracted label value to string", "err", err, "type", reflect.TypeOf(lValue))
```
Comment (adityacs) [inline pkg/logentry/stages/labels.go]: Not sure if we require `.String()` here. If required, we will have to handle `nil` case.

Comment (adityacs) [reply pkg/logentry/stages/labels.go]: This also happens in `template` and `tenant` stage. 
May be we should just set `extracted[n] = ""` here https://github.com/grafana/loki/blob/master/pkg/logentry/stages/json.go#L153

Comment (cyriltovena) [reply pkg/logentry/stages/labels.go]: Can you paste the stacktrace here to verify this was the problem ?

Comment (adityacs) [reply pkg/logentry/stages/labels.go]:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x1978f03]

goroutine 165 [running]:
testing.tRunner.func1(0xc0001b8700)
	/usr/local/Cellar/go/1.13.3/libexec/src/testing/testing.go:874 +0x3a3
panic(0x1aa2160, 0x248be70)
	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/panic.go:679 +0x1b2
github.com/grafana/loki/pkg/logentry/stages.(*labelStage).Process(0xc00028ffe0, 0xc0002bd5f0, 0xc0002bd650, 0xc000302040, 0xc0002e0940)
	/Users/adityacs/adityacs/loki/src/github.com/grafana/loki/pkg/logentry/stages/labels.go:71 +0x223
github.com/grafana/loki/pkg/logentry/stages.(*Pipeline).Process(0xc0002b7cc0, 0xc0002bd5f0, 0xc0002bd650, 0xc000302040, 0xc0002e0940)
	/Users/adityacs/adityacs/loki/src/github.com/grafana/loki/pkg/logentry/stages/pipeline.go:93 +0x213
github.com/grafana/loki/pkg/logentry/stages.TestLabelsPipeline_Labels(0xc0001b8700)
	/Users/adityacs/adityacs/loki/src/github.com/grafana/loki/pkg/logentry/stages/labels_test.go:47 +0x271
testing.tRunner(0xc0001b8700, 0x1c3a568)
	/usr/local/Cellar/go/1.13.3/libexec/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/Cellar/go/1.13.3/libexec/src/testing/testing.go:960 +0x350

```

Comment (adityacs) [reply pkg/logentry/stages/labels.go]: This line points out the error `github.com/grafana/loki/pkg/logentry/stages.(*labelStage).Process(0xc00028ffe0, 0xc0002bd5f0, 0xc0002bd650, 0xc000302040, 0xc0002e0940)
/Users/adityacs/adityacs/loki/src/github.com/grafana/loki/pkg/logentry/stages/labels.go:71 +0x223`

Comment (cyriltovena) [reply pkg/logentry/stages/labels.go]: I see you should add a regression test then.

**Comment by adityacs** [comment]
@owen-d @cyriltovena need a small clarity. Just wanted to know what's the take here. Should we just remove `.String()` here `reflect.TypeOf(lValue).String()` from all `Debug` lines ? 
OR 
should we set `extracted[n] = ""` here https://github.com/grafana/loki/blob/master/pkg/logentry/stages/json.go#L153 ?

**Comment by cyriltovena** [comment]
I think removing the `.String()` is a good idea. Pretty sure the logger will be fine, but the best option is to have a test covering this line/case.

File: pkg/logentry/stages/labels_test.go [hunk 2]
```diff
@@ -49,6 +59,26 @@ func TestLabelsPipeline_Labels(t *testing.T) {
...
+	ts := time.Now()
+	entry := testLabelsLogLineWithMissingKey
+	extracted := map[string]interface{}{}
+	pl.Process(lbls, extracted, &ts, &entry)
+	expectedLog := "level=debug msg=\"failed to convert extracted label value to strin\" err=\"Can't convert <nil> to string\" type=null"
+	if !(strings.Contains(buf.String(), expectedLog)) {
+		t.Errorf("\nexpected: %s\n+actual: %s", expectedLog, buf.String())
+	}
+}
+
```
Comment (adityacs) [inline pkg/logentry/stages/labels_test.go]: @cyriltovena @owen-d I have added the test case to validate the log lines. May be not good way to test/assert log lines. Kindly guide me for any other better ways.
If this is OK. I will add similar tests to template, regex, output and tenant

Comment (cyriltovena) [reply pkg/logentry/stages/labels_test.go]: Looks good, however tests are failing.

Comment (adityacs) [reply pkg/logentry/stages/labels_test.go]: Will fix.
