### PR TITLE
fix: Return error 422 (Unprocessable Content) when push request does not contain any streams

### LINKED ISSUE #13399: Some invalid push payloads are accepted and return 204 but store no data
**Describe the bug**

When crafting a payload to test Loki it was discovered that a json push request could be structured such that Loki can correctly parse the json but extracts no labels nor logs from it.

There exist validations to make sure a push request has valid labels (a push request cannot have zero labels), however, prior to reaching that code there are several places we exit early if there are no streams or entries found, and we exit with the 204 status code which indicates a successful push.

https://github.com/grafana/loki/blob/9f31b25253502f035cfb6a831bcea7f778f427dd/pkg/distributor/distributor.go#L343-L345

https://github.com/grafana/loki/blob/9f31b25253502f035cfb6a831bcea7f778f427dd/pkg/distributor/distributor.go#L460-L462

to exit early at the first point the json just needs to be valid and NOT contain a `streams` key
```
{"strooms": [{"ignoredkey1": "ignoredval1", "ignoredkey2": "ignoredval2"}]}
```

to exit at the second point, the json needs to be valid and contains a `streams` key:

```
{"streams": [{"ignoredkey1": "ignoredval1", "ignoredkey2": "ignoredval2"}]}
```

**Expected behavior**

I don't think a 204 "no content" response which is also used to indicate success should be returned here, rather a 400 Bad Request feels like the least surprising thing to consumers of the API who could then get a message indicating why their logs are not being displayed when they query.

### PR DESCRIPTION
**Pull request by ravishankar15**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #13399 

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [x] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Comment by ravishankar15** [comment]
Can someone take a look at this PR its a small fix

File: pkg/validation/validate.go [hunk 1]
```diff
@@ -11,7 +11,9 @@ import (
 )
 
 const (
-	ReasonLabel = "reason"
+	ReasonLabel    = "reason"
+	MissingStreams = "error at least one valid stream is required for ingestion"
```
Comment (chaudum) [inline pkg/validation/validate.go:15]: nit: I would use the same naming convention as for other error messages

```suggestion
	MissingStreamsErrorMsg = "error at least one valid stream is required for ingestion"
```

**Review by chaudum — COMMENTED** [review]
@ravishankar15 One suggestion, otherwise LGTM

**Review by chaudum — APPROVED** [review]
