### PR TITLE
Fix v1 label API to be Prometheus-compatible

### LINKED ISSUE #1293: Grafana cannot read label values from Loki response
**Describe the bug**
I'm using Loki in grafana as Prometheus datasource (using `/loki` path). When I try to create a new variable on a dasboard using `label_name(<label>)` query, grafana cannot get the values because `/loki/label/<label>/values` does not response with the expected json structure

Expected:
```json
{
 "data": ["<list_of_values>"],
  "status": "success"
}
```

Returned:
```json
{
  "values": ["<list_of_Values>"]
}
```
**To Reproduce**
1. Deploy loki and grafana
2. Feed loki with some logs
3. Try to create a new variable in a dasboard using `label_values(<label>)` query
4.  Check `Preview of values` is empty but http response contains values

**Expected behavior**
`/loki/label/<label>/values` endpoint responses with the appropiete format

**Environment:**
 - Infrastructure: kubernetes v1.15.5
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**

Variable config:
image

Loki response:
image

Prometheus expected response:
image

### PR DESCRIPTION
**Pull request by rfratto**
The label and label values API will now return the expected form of:

```json
{
  "status": "success",
  "data": [
    "label1",
    "label2",
    "labeln"
  ]
}
```

Fixes #1293.

### CODE REVIEW

File: pkg/logql/marshal/marshal.go [hunk 1]
```diff
@@ -38,7 +38,12 @@ func WriteQueryResponseJSON(v promql.Value, w io.Writer) error {
 //  Note that it simply directly marshals the value passed in.  This is because the label currently marshals
```
Comment (joe-elliott) [inline pkg/logql/marshal/marshal.go]: This comment is no longer relevant?

Comment (rfratto) [reply pkg/logql/marshal/marshal.go]: whoops :) fixed
