### PR TITLE
Include the stream's labels in OOO error responses.

### LINKED ISSUE #250: Promtail: retry 500s (and other errors), and not 400s
We should retry logs push on non-400 errors.

### LINKED ISSUE #298: Promtail should log the first couple of hundred chars of the http body on failed pushes
So users can see what the error message was.

See this code for the equivalent prometheus: https://github.com/prometheus/prometheus/blob/master/storage/remote/client.go#L104

### PR DESCRIPTION
**Pull request by tomwilkie**
Also, read the body of error responses and log them.  And retries 500s and connection errors.

Fixes #298, fixes #250

Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

### CODE REVIEW

File: pkg/promtail/client/client.go [hunk 1]
```diff
@@ -123,49 +131,84 @@ func (c *Client) run() {
...
+			return
+		}
+
+		level.Error(c.logger).Log("msg", "error sending batch", "status", status, "error", err)
+
+		// Only retry 500s and connection-level errors.
+		if status > 0 && status/100 != 5 {
+			return
+		}
+
```
Comment (slim-bean) [inline pkg/promtail/client/client.go]: What about logging a Warn if the status is 5xx and we are still retrying, then log an error when we run out of retries, and log any non-retryable error immediately as Error?

This way we when we see Error in the logs we know we are dropping messages, however, Warns would give us some indicator of transient issues.

File: pkg/promtail/client/client.go [hunk 2]
```diff
@@ -123,49 +131,84 @@ func (c *Client) run() {
...
+	defer helpers.LogError("closing watcher", resp.Body.Close)
 
 	if resp.StatusCode/100 != 2 {
-		return fmt.Errorf("Error doing write: %d - %s", resp.StatusCode, resp.Status)
+		scanner := bufio.NewScanner(io.LimitReader(resp.Body, maxErrMsgLen))
+		line := ""
+		if scanner.Scan() {
+			line = scanner.Text()
+		}
+		err = fmt.Errorf("server returned HTTP status %s (%d): %s", resp.Status, resp.StatusCode, line)
```
Comment (slim-bean) [inline pkg/promtail/client/client.go]: I guess if we go the route above with only logging at Warn for 5xx errors we would want to do that here too, and log everything else as Error

File: pkg/promtail/client/client.go [hunk 3]
```diff
@@ -123,49 +131,84 @@ func (c *Client) run() {
...
-func (c *Client) send(batch map[model.Fingerprint]*logproto.Stream) error {
+func (c *Client) sendBatch(batch map[model.Fingerprint]*logproto.Stream) {
+	buf, err := encodeBatch(batch)
+	if err != nil {
+		level.Error(c.logger).Log("msg", "error encoding batch", "error", err)
+		return
+	}
+	sentBytes.Add(float64(len(buf)))
+
+	ctx := context.Background()
```
Comment (woodsaj) [inline pkg/promtail/client/client.go]: can we add a context.WithTimeout() here with the `timeout` configurable via the Confg.

Comment (woodsaj) [reply pkg/promtail/client/client.go]: actually, we will need to create the context.WithTimeout() within the `for backoff.Ongoing()` loop so that the timeout is reset for each attempt to send.

File: pkg/promtail/client/client.go [hunk 4]
```diff
@@ -123,49 +131,84 @@ func (c *Client) run() {
...
+	backoff := util.NewBackoff(ctx, c.cfg.BackoffConfig)
+	for backoff.Ongoing() {
+		start := time.Now()
```
Comment (woodsaj) [inline pkg/promtail/client/client.go]: can we add a context.WithTimeout() here with the `timeout` configurable via the Confg.  This will ensure we dont block indefinitely if the server doesn't respond.

File: pkg/promtail/client/client.go [hunk 5]
```diff
@@ -123,49 +131,84 @@ func (c *Client) run() {
...
-		return err
+	req = req.WithContext(ctx)
+	req.Header.Set("Content-Type", contentType)
+
+	resp, err := http.DefaultClient.Do(req)
+	if err != nil {
+		return -1, err
 	}
-	requestDuration.WithLabelValues(strconv.Itoa(resp.StatusCode)).Observe(time.Since(start).Seconds())
+	defer helpers.LogError("closing watcher", resp.Body.Close)
```
Comment (woodsaj) [inline pkg/promtail/client/client.go]:
```suggestion
	defer helpers.LogError("closing response body", resp.Body.Close)
```

File: pkg/promtail/client/client.go (hunk 3 above)
Comment (tomwilkie) [reply pkg/promtail/client/client.go]: will keep that separate, there is a issue for that.

File: pkg/promtail/client/client.go (hunk 4 above)
Comment (tomwilkie) [reply pkg/promtail/client/client.go]: Will do separate PR for that, there is an issue.
