### PR TITLE
logcli: Add retries to unsuccessful log queries

### LINKED ISSUE #3855: Logcli doesn't do retries on timeout failures
**Describe the bug**
I'm using logcli to download a large volume of logs from loki in batches.
This might take a long time to complete. Unfortunately, logcli stops on the first error it encounters, rather then doing retries.

**To Reproduce**
1. Started Loki on a limited resources cluster.
2. Query using logcli.

**Expected behavior**
I was expecting logcli to do a retry on a timeout error and proceed with the query.

**Proposed Simple Solution**
A very simple solution would be to replace the following `log.Fatalf()` with `log.Println()` followed by a `continue` statement.
https://github.com/grafana/loki/blob/bdee4a37417f6c3f5e1087c6353866c046b5a42c/pkg/logcli/query/query.go#L104

**Environment:**
 - Infrastructure: OpenShift cluster
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**

```
$ logcli query '{filename="XXX.json"}' --batch=50000 --limit=5000000          
Query failed: Error response from server: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>                                                                                                                                                                                                     (<nil>)     
```

### PR DESCRIPTION
**Pull request by vyzigold**
**What this PR does / why we need it**:
This adds a possibility to retry unsuccessful queries when using logcli
Example output of a failed query (there is no server running on that port):
```
./logcli query "{type=\"logtest\"}" --addr="http://127.0.0.1" --retries 3
2021/06/22 15:28:02 http://127.0.0.1/loki/api/v1/query_range?direction=BACKWARD&end=1624368482937234835&limit=30&query=%7Btype%3D%22logtest%22%7D&start=1624364882937234835
2021/06/22 15:28:02 error sending request Get "http://127.0.0.1/loki/api/v1/query_range?direction=BACKWARD&end=1624368482937234835&limit=30&query=%7Btype%3D%22logtest%22%7D&start=1624364882937234835": dial tcp 127.0.0.1:80: connect: connection refused
2021/06/22 15:28:02 error sending request Get "http://127.0.0.1/loki/api/v1/query_range?direction=BACKWARD&end=1624368482937234835&limit=30&query=%7Btype%3D%22logtest%22%7D&start=1624364882937234835": dial tcp 127.0.0.1:80: connect: connection refused
2021/06/22 15:28:02 error sending request Get "http://127.0.0.1/loki/api/v1/query_range?direction=BACKWARD&end=1624368482937234835&limit=30&query=%7Btype%3D%22logtest%22%7D&start=1624364882937234835": dial tcp 127.0.0.1:80: connect: connection refused
2021/06/22 15:28:02 Query failed: Run out of retries while querying the server
```

**Which issue(s) this PR fixes**:
Fixes #3855

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Review by ronensc — APPROVED** [review]
Thanks for adding this feature

File: pkg/logcli/client/client.go [hunk 1]
```diff
@@ -216,21 +217,39 @@ func (c *DefaultClient) doRequest(path, query string, quiet bool, out interface{
...
 	}
-	resp, err := client.Do(req)
-	if err != nil {
-		return err
+
+	var resp *http.Response
+	retries := c.Retries
+	success := false
+
+	for retries > 0 {
```
Comment (sandeepsukhani) [inline pkg/logcli/client/client.go:225]: If a user sets the retries flag value to 0 by mistake then they would unexpectedly skip making any calls. Also, retried calls should be the ones done after seeing a failure in the initial call, so let us initialise the `retries` above to `c.Retries + 1`.
What do you think?

**Review by sandeepsukhani — COMMENTED** [review]
Just added a minor suggestion but otherwise the code LGTM!
Thanks for the PR!

File: pkg/logcli/client/client.go (hunk 1 above)
Comment (vyzigold) [reply pkg/logcli/client/client.go]: You are right, but I enhanced your idea a little bit. I renamed the variable to "attempts", which seemed like a better name to me now. I implemented your suggestion, so `attempts = c.Retries + 1` and I made the default value for c.Retries = 0. So there still is 1 attempt unless the user sets the retries flag to something other than 0.

**Review by sandeepsukhani — APPROVED** [review]
LGTM!
