### PR TITLE
Fixes races in multiline stage and promtail.

### LINKED ISSUE #3120: Promtail crashing
**Describe the bug**
Using primtail to ingest a bunch of nginx log files into loki, and sometimes when starting promtail it crashes.

promtail, version 2.1.0 (branch: HEAD, revision: 1b79df37)
  build user:       root@b8941a81fe55
  build date:       2020-12-24T14:08:17Z
  go version:       go1.15.3
  platform:         linux/amd64

**Expected behavior**
promtail should not crash on startup.

**Environment:**
 - Linux hostname 5.4.0-1035-azure #36~18.04.1-Ubuntu SMP Wed Dec 16 23:49:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Screenshots, Promtail config, or terminal output**
goroutine 344 [running]:
runtime.throw(0x2a9fcb2, 0x21)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc000ddd8b0 sp=0xc000ddd880 pc=0x43adf2
runtime.mapaccess2_fast64(0x25e6b20, 0xc000a17620, 0xdcc6c0329c259a87, 0xdcc6c0329c259a87, 0x0)
        /usr/local/go/src/runtime/map_fast64.go:61 +0x1ac fp=0xc000ddd8d8 sp=0xc000ddd8b0 pc=0x4160cc
github.com/grafana/loki/pkg/logql/log.(*noopPipeline).ForStream(0xc0001187b8, 0xc000dee300, 0x3, 0x3, 0xc000deb718, 0xc00064c7e0)
        /src/loki/pkg/logql/log/pipeline.go:64 +0x71 fp=0xc000ddd938 sp=0xc000ddd8d8 pc=0xcd85b1
github.com/grafana/loki/pkg/logentry/stages.(*matcherStage).Process(0xc000a54060, 0xc000dec420, 0xc000dec450, 0xc0002fa060, 0xc000a27a30)
        /src/loki/pkg/logentry/stages/match.go:135 +0x138 fp=0xc000dddb10 sp=0xc000ddd938 pc=0xd21e38
github.com/grafana/loki/pkg/logentry/stages.(*Pipeline).Process(0xc000a18900, 0xc000dec420, 0xc000dec450, 0xc0002fa060, 0xc000a27a30)
        /src/loki/pkg/logentry/stages/pipeline.go:109 +0x213 fp=0xc000dddc78 sp=0xc000dddb10 pc=0xd26b53
github.com/grafana/loki/pkg/logentry/stages.(*Pipeline).Wrap.func1(0xc000dec420, 0xbff4f0efb5fde4d8, 0x12e631c94, 0x413f820, 0xc0005fcc60, 0x155, 0x0, 0xffffffffffffffff)
        /src/loki/pkg/logentry/stages/pipeline.go:129 +0x110 fp=0xc000dddd08 sp=0xc000dddc78 pc=0xd2ec50
github.com/grafana/loki/pkg/promtail/api.EntryHandlerFunc.Handle(0xc00027de40, 0xc000dec420, 0xbff4f0efb5fde4d8, 0x12e631c94, 0x413f820, 0xc0005fcc60, 0x155, 0x203000, 0xc000dec3f0)
        /src/loki/pkg/promtail/api/types.go:24 +0x65 fp=0xc000dddd58 sp=0xc000dddd08 pc=0xd017a5
github.com/grafana/loki/pkg/promtail/api.AddLabelsMiddleware.func1.1(0xc000dec3f0, 0xbff4f0efb5fde4d8, 0x12e631c94, 0x413f820, 0xc0005fcc60, 0x155, 0x0, 0x0)
        /src/loki/pkg/promtail/api/types.go:45 +0xa3 fp=0xc000ddddc0 sp=0xc000dddd58 pc=0xd01983
github.com/grafana/loki/pkg/promtail/api.EntryHandlerFunc.Handle(0xc000650100, 0xc000dec3f0, 0xbff4f0efb5fde4d8, 0x12e631c94, 0x413f820, 0xc0005fcc60, 0x155, 0xc000ddde58, 0x5)
        /src/loki/pkg/promtail/api/types.go:24 +0x65 fp=0xc000ddde10 sp=0xc000ddddc0 pc=0xd017a5
github.com/grafana/loki/pkg/promtail/api.AddLabelsMiddleware.func1.1(0xc000dec3c0, 0xbff4f0efb5fde4d8, 0x12e631c94, 0x413f820, 0xc0005fcc60, 0x155, 0x2941bc0, 0xc000dec3c0)
        /src/loki/pkg/promtail/api/types.go:45 +0xa3 fp=0xc000ddde78 sp=0xc000ddde10 pc=0xd01983
github.com/grafana/loki/pkg/promtail/api.EntryHandlerFunc.Handle(0xc00046e860, 0xc000dec3c0, 0xbff4f0efb5fde4d8, 0x12e631c94, 0x413f820, 0xc0005fcc60, 0x155, 0x0, 0x0)
        /src/loki/pkg/promtail/api/types.go:24 +0x65 fp=0xc000dddec8 sp=0xc000ddde78 pc=0xd017a5
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000173700)
        /src/loki/pkg/promtail/targets/file/tailer.go:150 +0x57c fp=0xc000dddfd8 sp=0xc000dddec8 pc=0x205599c
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000dddfe0 sp=0xc000dddfd8 pc=0x473a01
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 1 [chan receive]:
github.com/weaveworks/common/server.(*Server).Run(0xc000a1fb80, 0x0, 0x0)
        /src/loki/vendor/github.com/weaveworks/common/server/server.go:402 +0x15b
github.com/grafana/loki/pkg/promtail.(*Promtail).Run(0xc0005f2960, 0xc000a18c40, 0x4)
        /src/loki/pkg/promtail/promtail.go:98 +0xa5
main.main()
        /src/loki/cmd/promtail/main.go:113 +0x552

goroutine 6 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x41414a0)
        /src/loki/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
        /src/loki/vendor/k8s.io/klog/klog.go:411 +0xd8

goroutine 68 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000172280)
        /src/loki/vendor/go.opencensus.io/stats/view/worker.go:276 +0x105
created by go.opencensus.io/stats/view.init.0
        /src/loki/vendor/go.opencensus.io/stats/view/worker.go:34 +0x68

goroutine 69 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x4141580)
        /src/loki/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
        /src/loki/vendor/k8s.io/klog/v2/klog.go:416 +0xd8

goroutine 275 [select]:
github.com/prometheus/prometheus/discovery.(*Manager).sender(0xc0002d1900)
        /src/loki/vendor/github.com/prometheus/prometheus/discovery/manager.go:234 +0x125
created by github.com/prometheus/prometheus/discovery.(*Manager).Run
        /src/loki/vendor/github.com/prometheus/prometheus/discovery/manager.go:141 +0x45

goroutine 211 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc000681000)
        /src/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x3b3
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
        /src/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x85

goroutine 142 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc0002fbce0)
        /src/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x3b3
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
        /src/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x85

goroutine 189 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00000f120)
        /src/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x3b3
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
        /src/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x85

goroutine 252 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e620, 0xc0006f71a8, 0xc0004d6080, 0x2fdef00, 0xc0009640d0, 0xc0004d60a0)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 259 [runnable]:
github.com/prometheus/common/model.LabelSet.String(0xc000d59590, 0xc000330d80, 0xc000079e90)
        /src/loki/vendor/github.com/prometheus/common/model/labelset.go:139 +0x33c
github.com/grafana/loki/pkg/promtail/client.(*batch).add(0xc00064cdb0, 0x0, 0x0, 0xc000d59590, 0xbff4f0efb602e2a0, 0x12e6819f8, 0x413f820, 0xc000f36000, 0x15a)
        /src/loki/pkg/promtail/client/batch.go:42 +0x58
github.com/grafana/loki/pkg/promtail/client.(*client).run(0xc0005b7b00)
        /src/loki/pkg/promtail/client/client.go:224 +0x5b5
created by github.com/grafana/loki/pkg/promtail/client.New
        /src/loki/pkg/promtail/client/client.go:170 +0x445

goroutine 260 [select]:
github.com/grafana/loki/pkg/promtail/positions.(*positions).run(0xc0005f29b0)
        /src/loki/pkg/promtail/positions/positions.go:153 +0x115
created by github.com/grafana/loki/pkg/promtail/positions.New
        /src/loki/pkg/promtail/positions/positions.go:95 +0x195

goroutine 265 [syscall]:
syscall.Syscall6(0x101, 0xffffffffffffff9c, 0xc000d490c0, 0x80000, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0002af418)
        /usr/local/go/src/syscall/asm_linux_amd64.s:41 +0x5
syscall.openat(0xffffffffffffff9c, 0xc000d0e2d0, 0x30, 0x80000, 0xc000000000, 0x100, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:68 +0xbd
syscall.Open(...)
        /usr/local/go/src/syscall/syscall_linux.go:152
os.openFileNolog(0xc000d0e2d0, 0x30, 0x0, 0x0, 0xc000d7cc30, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:200 +0x8f
os.OpenFile(0xc000d0e2d0, 0x30, 0x0, 0xc000000000, 0x0, 0x0, 0xc00046f4e0)
        /usr/local/go/src/os/file.go:327 +0x65
os.Open(...)
        /usr/local/go/src/os/file.go:307
github.com/hpcloud/tail.OpenFile(0xc000d0e2d0, 0x30, 0xc000d55ce0, 0x0, 0xc0002af560)
        /src/loki/vendor/github.com/hpcloud/tail/tail_posix.go:22 +0x95
github.com/hpcloud/tail.TailFile(0xc000d0e2d0, 0x30, 0xc0003dd010, 0x10101, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:128 +0x191
github.com/grafana/loki/pkg/promtail/targets/file.newTailer(0x2f6a060, 0xc000a16960, 0x2f6e2c0, 0xc000650100, 0x2fe3580, 0xc0005f29b0, 0xc000d0e2d0, 0x30, 0xc0005fbe80, 0x0, ...)
        /src/loki/pkg/promtail/targets/file/tailer.go:52 +0x1bb
github.com/grafana/loki/pkg/promtail/targets/file.(*FileTarget).startTailing(0xc000172480, 0xc0005c0000, 0xb2, 0x100)
        /src/loki/pkg/promtail/targets/file/filetarget.go:303 +0x676
github.com/grafana/loki/pkg/promtail/targets/file.(*FileTarget).sync(0xc000172480, 0xc000172480, 0xc00014e300)
        /src/loki/pkg/promtail/targets/file/filetarget.go:254 +0x35b
github.com/grafana/loki/pkg/promtail/targets/file.NewFileTarget(0x2f6a060, 0xc000a16960, 0x2f6e2c0, 0xc00027de40, 0x2fe3580, 0xc0005f29b0, 0xc000135a80, 0x13, 0xc0009b82a0, 0xc0009b8240, ...)
        /src/loki/pkg/promtail/targets/file/filetarget.go:119 +0x1e5
github.com/grafana/loki/pkg/promtail/targets/file.(*targetSyncer).newTarget(...)
        /src/loki/pkg/promtail/targets/file/filetargetmanager.go:287
github.com/grafana/loki/pkg/promtail/targets/file.(*targetSyncer).sync(0xc00039a630, 0xc00064e1c8, 0x1, 0x1)
        /src/loki/pkg/promtail/targets/file/filetargetmanager.go:262 +0x12c5
github.com/grafana/loki/pkg/promtail/targets/file.(*FileTargetManager).run(0xc000a17170)
        /src/loki/pkg/promtail/targets/file/filetargetmanager.go:138 +0xd5
created by github.com/grafana/loki/pkg/promtail/targets/file.NewFileTargetManager
        /src/loki/pkg/promtail/targets/file/filetargetmanager.go:129 +0x411

goroutine 266 [chan receive]:
github.com/prometheus/prometheus/discovery.(*Manager).Run(0xc0002d1900, 0x0, 0x0)
        /src/loki/vendor/github.com/prometheus/prometheus/discovery/manager.go:142 +0x74
github.com/grafana/loki/pkg/helpers.LogError(0x2a841eb, 0x16, 0xc000a43a90)
        /src/loki/pkg/helpers/logerror.go:12 +0x3c
created by github.com/grafana/loki/pkg/promtail/targets/file.NewFileTargetManager
        /src/loki/pkg/promtail/targets/file/filetargetmanager.go:130 +0x485

goroutine 251 [syscall]:
os/signal.signal_recv(0xc00027dea0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:150 +0x45

goroutine 291 [select]:
github.com/weaveworks/common/signals.(*Handler).Loop(0xc000a6a3f0)
        /src/loki/vendor/github.com/weaveworks/common/signals/signals.go:48 +0x1d7
github.com/weaveworks/common/server.(*Server).Run.func1(0xc000a1fb80, 0xc000a54900)
        /src/loki/vendor/github.com/weaveworks/common/server/server.go:362 +0x3a
created by github.com/weaveworks/common/server.(*Server).Run
        /src/loki/vendor/github.com/weaveworks/common/server/server.go:361 +0x6b

goroutine 292 [IO wait]:
internal/poll.runtime_pollWait(0x7f75a41dce38, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc0005fab18, 0x72, 0x0, 0x0, 0x2a64741)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0005fab00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:394 +0x1fc
net.(*netFD).accept(0xc0005fab00, 0xc0009b8120, 0x4118b8, 0xc000100000)
        /usr/local/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc00027dfc0, 0xc000a75e08, 0x4118b8, 0x30)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00027dfc0, 0x28466c0, 0xc0009b8120, 0x25c4340, 0x4091dd0)
        /usr/local/go/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc000a6c000, 0x2fbb5e0, 0xc00027dfc0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2937 +0x266
github.com/weaveworks/common/server.(*Server).Run.func2(0xc000a1fb80, 0xc000a54900)
        /src/loki/vendor/github.com/weaveworks/common/server/server.go:372 +0x126
created by github.com/weaveworks/common/server.(*Server).Run
        /src/loki/vendor/github.com/weaveworks/common/server/server.go:369 +0x97

goroutine 293 [IO wait]:
internal/poll.runtime_pollWait(0x7f75a41dcd58, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc0005fab98, 0x72, 0x0, 0x0, 0x2a64741)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0005fab80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:394 +0x1fc
net.(*netFD).accept(0xc0005fab80, 0xc0001ac5a8, 0xc000a0fee0, 0xc0001ac5a0)
        /usr/local/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc00027dfe0, 0x4118b8, 0xc0001ac5a0, 0xc0001ac628)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00027dfe0, 0xc000a17d70, 0xc000a0fee0, 0xc0001ac628, 0x0)
        /usr/local/go/src/net/tcpsock.go:261 +0x65
google.golang.org/grpc.(*Server).Serve(0xc00038f380, 0x2fbb5e0, 0xc00027dfe0, 0x0, 0x0)
        /src/loki/vendor/google.golang.org/grpc/server.go:621 +0x216
github.com/weaveworks/common/server.(*Server).Run.func3(0xc000a1fb80, 0xc000a54900)
        /src/loki/vendor/github.com/weaveworks/common/server/server.go:391 +0x4e
created by github.com/weaveworks/common/server.(*Server).Run
        /src/loki/vendor/github.com/weaveworks/common/server/server.go:390 +0x13b

goroutine 294 [syscall]:
syscall.Syscall6(0xe8, 0xa, 0xc0005d1b6c, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:41 +0x5
golang.org/x/sys/unix.EpollWait(0xa, 0xc0005d1b6c, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0)
        /src/loki/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:76 +0x72
gopkg.in/fsnotify%2ev1.(*fdPoller).wait(0xc00019e220, 0x0, 0x0, 0x0)
        /src/loki/vendor/gopkg.in/fsnotify.v1/inotify_poller.go:86 +0x91
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc000146000)
        /src/loki/vendor/gopkg.in/fsnotify.v1/inotify.go:192 +0x206
created by gopkg.in/fsnotify%2ev1.NewWatcher
        /src/loki/vendor/gopkg.in/fsnotify.v1/inotify.go:59 +0x1a8

goroutine 295 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f6840, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f6840)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 296 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000172600)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 297 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000172600)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 298 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f69a0, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f69a0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 299 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000172700)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 300 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000172700)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 301 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f6a50, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f6a50)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 302 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000172900)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 303 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000172900)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 304 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f6b00, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f6b00)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 305 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000172a00)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 306 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000172a00)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 307 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f6bb0, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f6bb0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 308 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000172b00)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 309 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000172b00)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 310 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f6c60, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f6c60)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 311 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000172c00)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 312 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000172c00)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 204 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc000651fc0, 0xc0006f68b8, 0xc0006800e0, 0x2fdef00, 0xc0009c20d0, 0xc000680100)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 313 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f6d10, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f6d10)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 314 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000172d00)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 315 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000172d00)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 316 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f6dc0, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f6dc0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 317 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000172e00)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 318 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000172e00)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 205 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e280, 0xc0006f6b78, 0xc000680180, 0x2fdef00, 0xc0009c2270, 0xc0006801a0)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 319 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f6e70, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f6e70)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 320 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000172f00)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 321 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000172f00)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 322 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f6f20, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f6f20)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 323 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000173000)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 324 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000173000)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 206 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e0a0, 0xc0006f6a18, 0xc000680240, 0x2fdef00, 0xc0009c2410, 0xc000680260)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 325 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f6fd0, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f6fd0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 326 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000173100)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 327 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000173100)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 207 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e220, 0xc0006f6ac8, 0xc000680300, 0x2fdef00, 0xc0009c2680, 0xc000680320)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 328 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f7080, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7080)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 329 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000173200)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 330 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000173200)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 331 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f7130, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7130)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 332 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000173300)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 333 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000173300)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 334 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f71e0, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f71e0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 335 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000173400)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 336 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000173400)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 337 [runnable]:
github.com/hpcloud/tail.(*Tail).sendLine(0xc0006f7290, 0xc000e1c340, 0x187, 0x0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:499 +0x165
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7290)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:334 +0x15a
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 338 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000173500)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 339 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000173500)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 340 [runnable]:
github.com/hpcloud/tail.(*Tail).sendLine(0xc0006f7340, 0xc0002d4840, 0x154, 0x0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:499 +0x165
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7340)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:334 +0x15a
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 341 [chan send]:
github.com/grafana/loki/pkg/promtail/client.(*client).Handle(0xc0005b7b00, 0xc0009799b0, 0xbff4f0efb5ff9610, 0x12e64cd68, 0x413f820, 0xc0002d4840, 0x154, 0xbff4f0efb6047498, 0x30)
        /src/loki/pkg/promtail/client/client.go:371 +0x185
github.com/grafana/loki/pkg/promtail/client.MultiClient.Handle(0xc000a26600, 0x1, 0x1, 0xc0009799b0, 0xbff4f0efb5ff9610, 0x12e64cd68, 0x413f820, 0xc0002d4840, 0x154, 0xc000e50480, ...)
        /src/loki/pkg/promtail/client/multi.go:45 +0xe2
github.com/grafana/loki/pkg/logentry/stages.(*Pipeline).Wrap.func1(0xc0009799b0, 0xbff4f0efb5ff9610, 0x12e64cd68, 0x413f820, 0xc0002d4840, 0x154, 0x0, 0xffffffffffffffff)
        /src/loki/pkg/logentry/stages/pipeline.go:138 +0x262
github.com/grafana/loki/pkg/promtail/api.EntryHandlerFunc.Handle(0xc00027de40, 0xc0009799b0, 0xbff4f0efb5ff9610, 0x12e64cd68, 0x413f820, 0xc0002d4840, 0x154, 0x203000, 0xc000979980)
        /src/loki/pkg/promtail/api/types.go:24 +0x65
github.com/grafana/loki/pkg/promtail/api.AddLabelsMiddleware.func1.1(0xc000979980, 0xbff4f0efb5ff9610, 0x12e64cd68, 0x413f820, 0xc0002d4840, 0x154, 0x0, 0x0)
        /src/loki/pkg/promtail/api/types.go:45 +0xa3
github.com/grafana/loki/pkg/promtail/api.EntryHandlerFunc.Handle(0xc000650100, 0xc000979980, 0xbff4f0efb5ff9610, 0x12e64cd68, 0x413f820, 0xc0002d4840, 0x154, 0xc000dabe58, 0x5)
        /src/loki/pkg/promtail/api/types.go:24 +0x65
github.com/grafana/loki/pkg/promtail/api.AddLabelsMiddleware.func1.1(0xc000979950, 0xbff4f0efb5ff9610, 0x12e64cd68, 0x413f820, 0xc0002d4840, 0x154, 0x2941bc0, 0xc000979950)
        /src/loki/pkg/promtail/api/types.go:45 +0xa3
github.com/grafana/loki/pkg/promtail/api.EntryHandlerFunc.Handle(0xc00046e7c0, 0xc000979950, 0xbff4f0efb5ff9610, 0x12e64cd68, 0x413f820, 0xc0002d4840, 0x154, 0x0, 0x0)
        /src/loki/pkg/promtail/api/types.go:24 +0x65
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000173600)
        /src/loki/pkg/promtail/targets/file/tailer.go:150 +0x57c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 342 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000173600)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 343 [runnable]:
github.com/hpcloud/tail.(*Tail).sendLine(0xc0006f73f0, 0xc0005fcc60, 0x155, 0x0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:499 +0x165
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f73f0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:334 +0x15a
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 345 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000173700)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 346 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f74a0, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f74a0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 347 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000173800)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 348 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000173800)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 349 [runnable]:
github.com/hpcloud/tail.(*Tail).sendLine(0xc0006f7550, 0xc0009fe000, 0xb7, 0x0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:499 +0x165
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7550)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:334 +0x15a
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 350 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000173900)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 351 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000173900)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 352 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f7600, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7600)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 353 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000173a00)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 354 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000173a00)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 355 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f76b0, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f76b0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 356 [runnable]:
sync.runtime_SemacquireMutex(0xc00027d064, 0x1, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00027d060)
        /usr/local/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
github.com/go-kit/kit/log.(*fdSyncWriter).Write(0xc00027d060, 0xc0005bc1a0, 0xa6, 0x185, 0x1, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/sync.go:89 +0xe8
github.com/go-kit/kit/log.logfmtLogger.Log(0x2f6a080, 0xc00027d060, 0xc000e80100, 0xc, 0x10, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/logfmt_logger.go:58 +0x1b0
github.com/go-kit/kit/log/level.(*logger).Log(0xc000a18600, 0xc000e80100, 0xc, 0x10, 0x577cf9, 0x247c480)
        /src/loki/vendor/github.com/go-kit/kit/log/level/level.go:63 +0xb4
github.com/cortexproject/cortex/pkg/util.(*PrometheusLogger).Log(0xc000a265a0, 0xc000e80100, 0xc, 0x10, 0x4, 0x4)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/log.go:87 +0x55
github.com/go-kit/kit/log.(*context).Log(0xc0009fa4e0, 0xc000a18e00, 0x4, 0x4, 0x2, 0x2f6a060)
        /src/loki/vendor/github.com/go-kit/kit/log/log.go:124 +0x202
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000173b00)
        /src/loki/pkg/promtail/targets/file/tailer.go:122 +0x1a9
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 357 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000173b00)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 358 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f7760, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7760)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 359 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000173d00)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 360 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000173d00)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 208 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e380, 0xc0006f6cd8, 0xc000680560, 0x2fdef00, 0xc0009c2dd0, 0xc000680580)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 361 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f7810, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7810)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 362 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000173e00)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 363 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000173e00)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 364 [runnable]:
github.com/hpcloud/tail.(*Tail).sendLine(0xc0006f78c0, 0xc000ea4000, 0x260, 0x0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:499 +0x165
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f78c0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:334 +0x15a
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 365 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc000173f00)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 366 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc000173f00)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 367 [runnable]:
github.com/hpcloud/tail.(*Tail).sendLine(0xc0006f7970, 0xc0009fe180, 0xbb, 0x0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:499 +0x165
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7970)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:334 +0x15a
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 209 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e420, 0xc0006f6d88, 0xc000680620, 0x2fdef00, 0xc0009c3040, 0xc000680640)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 368 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fa000)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 369 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fa000)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 370 [runnable]:
syscall.Syscall(0x8, 0x27, 0x0, 0x1, 0x0, 0x1, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Seek(0x27, 0x0, 0x1, 0x4, 0x0, 0xc000eadcc8)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1259 +0x4c
internal/poll.(*FD).Seek(0xc00064b860, 0x0, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:414 +0xc5
os.(*File).seek(0xc00064ec80, 0x0, 0x1, 0xc000eb0000, 0x1000, 0x1000)
        /usr/local/go/src/os/file_unix.go:258 +0x65
os.(*File).Seek(0xc00064ec80, 0x0, 0x1, 0x4093800, 0xc000eaddd0, 0xbba4b7)
        /usr/local/go/src/os/file.go:235 +0x59
github.com/hpcloud/tail.(*Tail).Tell(0xc0006f7a20, 0x0, 0x0, 0x0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:150 +0xac
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7a20)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:323 +0x7c5
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 371 [runnable]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fa300)
        /src/loki/pkg/promtail/targets/file/tailer.go:121
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 372 [runnable]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fa300)
        /src/loki/pkg/promtail/targets/file/tailer.go:90
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 373 [runnable]:
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7ad0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:287
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 374 [runnable]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fa500)
        /src/loki/pkg/promtail/targets/file/tailer.go:121
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 375 [runnable]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fa500)
        /src/loki/pkg/promtail/targets/file/tailer.go:90
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 376 [runnable]:
github.com/hpcloud/tail.(*Tail).sendLine(0xc0006f7b80, 0xc000e1c4e0, 0x196, 0x0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:499 +0x165
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7b80)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:334 +0x15a
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 377 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fa600)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 378 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fa600)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 379 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f7c30, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7c30)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 380 [runnable]:
sync.runtime_SemacquireMutex(0xc00027d064, 0x0, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00027d060)
        /usr/local/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
github.com/go-kit/kit/log.(*fdSyncWriter).Write(0xc00027d060, 0xc0002d4580, 0x9d, 0x158, 0x1, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/sync.go:89 +0xe8
github.com/go-kit/kit/log.logfmtLogger.Log(0x2f6a080, 0xc00027d060, 0xc0005f8900, 0xc, 0x10, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/logfmt_logger.go:58 +0x1b0
github.com/go-kit/kit/log/level.(*logger).Log(0xc000a18600, 0xc0005f8900, 0xc, 0x10, 0x577cf9, 0x247c480)
        /src/loki/vendor/github.com/go-kit/kit/log/level/level.go:63 +0xb4
github.com/cortexproject/cortex/pkg/util.(*PrometheusLogger).Log(0xc000a265a0, 0xc0005f8900, 0xc, 0x10, 0x4, 0x4)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/log.go:87 +0x55
github.com/go-kit/kit/log.(*context).Log(0xc000978750, 0xc000655880, 0x4, 0x4, 0x2, 0x2f6a060)
        /src/loki/vendor/github.com/go-kit/kit/log/log.go:124 +0x202
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fa700)
        /src/loki/pkg/promtail/targets/file/tailer.go:122 +0x1a9
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 381 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fa700)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 382 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f7ce0, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7ce0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 383 [runnable]:
sync.runtime_SemacquireMutex(0xc00027d064, 0x0, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00027d060)
        /usr/local/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
github.com/go-kit/kit/log.(*fdSyncWriter).Write(0xc00027d060, 0xc00096c480, 0xaa, 0x165, 0x1, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/sync.go:89 +0xe8
github.com/go-kit/kit/log.logfmtLogger.Log(0x2f6a080, 0xc00027d060, 0xc0005f8a00, 0xc, 0x10, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/logfmt_logger.go:58 +0x1b0
github.com/go-kit/kit/log/level.(*logger).Log(0xc000a18600, 0xc0005f8a00, 0xc, 0x10, 0x577cf9, 0x247c480)
        /src/loki/vendor/github.com/go-kit/kit/log/level/level.go:63 +0xb4
github.com/cortexproject/cortex/pkg/util.(*PrometheusLogger).Log(0xc000a265a0, 0xc0005f8a00, 0xc, 0x10, 0x4, 0x4)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/log.go:87 +0x55
github.com/go-kit/kit/log.(*context).Log(0xc000978870, 0xc000655980, 0x4, 0x4, 0x2, 0x2f6a060)
        /src/loki/vendor/github.com/go-kit/kit/log/log.go:124 +0x202
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fa880)
        /src/loki/pkg/promtail/targets/file/tailer.go:122 +0x1a9
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 276 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e4e0, 0xc0006f6ee8, 0xc000182100, 0x2fdef00, 0xc000644270, 0xc000182160)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 384 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fa880)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 385 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f7d90, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7d90)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 386 [runnable]:
sync.runtime_SemacquireMutex(0xc00027d064, 0x0, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00027d060)
        /usr/local/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
github.com/go-kit/kit/log.(*fdSyncWriter).Write(0xc00027d060, 0xc00096c600, 0xb0, 0x16b, 0x1, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/sync.go:89 +0xe8
github.com/go-kit/kit/log.logfmtLogger.Log(0x2f6a080, 0xc00027d060, 0xc0005f8b00, 0xc, 0x10, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/logfmt_logger.go:58 +0x1b0
github.com/go-kit/kit/log/level.(*logger).Log(0xc000a18600, 0xc0005f8b00, 0xc, 0x10, 0x577cf9, 0x247c480)
        /src/loki/vendor/github.com/go-kit/kit/log/level/level.go:63 +0xb4
github.com/cortexproject/cortex/pkg/util.(*PrometheusLogger).Log(0xc000a265a0, 0xc0005f8b00, 0xc, 0x10, 0x4, 0x4)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/log.go:87 +0x55
github.com/go-kit/kit/log.(*context).Log(0xc000978990, 0xc000655a80, 0x4, 0x4, 0x2, 0x2f6a060)
        /src/loki/vendor/github.com/go-kit/kit/log/log.go:124 +0x202
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fa980)
        /src/loki/pkg/promtail/targets/file/tailer.go:122 +0x1a9
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 387 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fa980)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 388 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f7e40, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7e40)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 389 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005faa80)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 390 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005faa80)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 277 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e660, 0xc0006f7258, 0xc000182220, 0x2fdef00, 0xc0006444e0, 0xc000182260)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 391 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0006f7ef0, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0006f7ef0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 392 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fac80)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 393 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fac80)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 394 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc00094c210, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094c210)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 395 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fad80)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 396 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fad80)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 253 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e540, 0xc0006f6f98, 0xc0004d6560, 0x2fdef00, 0xc000964340, 0xc0004d6580)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 397 [runnable]:
sync.runtime_SemacquireMutex(0xc00027d064, 0x1, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00027d060)
        /usr/local/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
github.com/go-kit/kit/log.(*fdSyncWriter).Write(0xc00027d060, 0xc00096c000, 0xa5, 0x17a, 0x1, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/sync.go:89 +0xe8
github.com/go-kit/kit/log.logfmtLogger.Log(0x2f6a080, 0xc00027d060, 0xc000962780, 0xa, 0xc, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/logfmt_logger.go:58 +0x1b0
github.com/go-kit/kit/log/level.(*logger).Log(0xc000a18600, 0xc000962780, 0xa, 0xc, 0x577cf9, 0x247c480)
        /src/loki/vendor/github.com/go-kit/kit/log/level/level.go:63 +0xb4
github.com/cortexproject/cortex/pkg/util.(*PrometheusLogger).Log(0xc000a265a0, 0xc000962780, 0xa, 0xc, 0x4, 0x4)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/log.go:87 +0x55
github.com/go-kit/kit/log.(*context).Log(0xc000a6bf50, 0xc000655c80, 0x4, 0x4, 0xc000655c80, 0x2)
        /src/loki/vendor/github.com/go-kit/kit/log/log.go:124 +0x202
github.com/go-kit/kit/log.(*context).Log(0xc000978c60, 0xc0004d74a0, 0x2, 0x2, 0x2, 0xc000974190)
        /src/loki/vendor/github.com/go-kit/kit/log/log.go:124 +0x202
github.com/grafana/loki/pkg/util.LogAdapter.Printf(0x2f6a060, 0xc000a6bf50, 0x2a7516b, 0x10, 0xc0004d7460, 0x2, 0x2)
        /src/loki/pkg/util/log.go:68 +0x232
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094c2c0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:305 +0x91d
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 398 [semacquire]:
sync.runtime_SemacquireMutex(0xc00027d064, 0x0, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00027d060)
        /usr/local/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
github.com/go-kit/kit/log.(*fdSyncWriter).Write(0xc00027d060, 0xc0002d46e0, 0xa5, 0x160, 0x1, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/sync.go:89 +0xe8
github.com/go-kit/kit/log.logfmtLogger.Log(0x2f6a080, 0xc00027d060, 0xc0005f9000, 0xc, 0x10, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/logfmt_logger.go:58 +0x1b0
github.com/go-kit/kit/log/level.(*logger).Log(0xc000a18600, 0xc0005f9000, 0xc, 0x10, 0x577cf9, 0x247c480)
        /src/loki/vendor/github.com/go-kit/kit/log/level/level.go:63 +0xb4
github.com/cortexproject/cortex/pkg/util.(*PrometheusLogger).Log(0xc000a265a0, 0xc0005f9000, 0xc, 0x10, 0x4, 0x4)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/log.go:87 +0x55
github.com/go-kit/kit/log.(*context).Log(0xc000978cc0, 0xc000655cc0, 0x4, 0x4, 0x2, 0x2f6a060)
        /src/loki/vendor/github.com/go-kit/kit/log/log.go:124 +0x202
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fae80)
        /src/loki/pkg/promtail/targets/file/tailer.go:122 +0x1a9
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 399 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fae80)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 402 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e300, 0xc0006f6c28, 0xc000680ac0, 0x2fdef00, 0xc0009c32b0, 0xc000680ae0)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 400 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc00094c370, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094c370)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 401 [runnable]:
sync.runtime_SemacquireMutex(0xc00027d064, 0x1, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00027d060)
        /usr/local/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
github.com/go-kit/kit/log.(*fdSyncWriter).Write(0xc00027d060, 0xc00096c780, 0x9f, 0x171, 0x1, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/sync.go:89 +0xe8
github.com/go-kit/kit/log.logfmtLogger.Log(0x2f6a080, 0xc00027d060, 0xc0005f9100, 0xc, 0x10, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/logfmt_logger.go:58 +0x1b0
github.com/go-kit/kit/log/level.(*logger).Log(0xc000a18600, 0xc0005f9100, 0xc, 0x10, 0x577cf9, 0x247c480)
        /src/loki/vendor/github.com/go-kit/kit/log/level/level.go:63 +0xb4
github.com/cortexproject/cortex/pkg/util.(*PrometheusLogger).Log(0xc000a265a0, 0xc0005f9100, 0xc, 0x10, 0x4, 0x4)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/log.go:87 +0x55
github.com/go-kit/kit/log.(*context).Log(0xc000978de0, 0xc000655dc0, 0x4, 0x4, 0x2, 0x2f6a060)
        /src/loki/vendor/github.com/go-kit/kit/log/log.go:124 +0x202
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005faf80)
        /src/loki/pkg/promtail/targets/file/tailer.go:122 +0x1a9
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 418 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005faf80)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 419 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc00094c420, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094c420)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 420 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fb080)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 421 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fb080)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 254 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e5a0, 0xc0006f7048, 0xc0004d6b80, 0x2fdef00, 0xc0009645b0, 0xc0004d6ba0)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 403 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e4a0, 0xc0006f6e38, 0xc000680cc0, 0x2fdef00, 0xc0009c3380, 0xc000680ce0)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 422 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc00094c4d0, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094c4d0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 423 [runnable]:
sync.runtime_SemacquireMutex(0xc00027d064, 0x1, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00027d060)
        /usr/local/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
github.com/go-kit/kit/log.(*fdSyncWriter).Write(0xc00027d060, 0xc00096c900, 0x9f, 0x174, 0x1, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/sync.go:89 +0xe8
github.com/go-kit/kit/log.logfmtLogger.Log(0x2f6a080, 0xc00027d060, 0xc0005f9300, 0xc, 0x10, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/logfmt_logger.go:58 +0x1b0
github.com/go-kit/kit/log/level.(*logger).Log(0xc000a18600, 0xc0005f9300, 0xc, 0x10, 0x577cf9, 0x247c480)
        /src/loki/vendor/github.com/go-kit/kit/log/level/level.go:63 +0xb4
github.com/cortexproject/cortex/pkg/util.(*PrometheusLogger).Log(0xc000a265a0, 0xc0005f9300, 0xc, 0x10, 0x4, 0x4)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/log.go:87 +0x55
github.com/go-kit/kit/log.(*context).Log(0xc000978f90, 0xc000655f00, 0x4, 0x4, 0x2, 0x2f6a060)
        /src/loki/vendor/github.com/go-kit/kit/log/log.go:124 +0x202
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fb180)
        /src/loki/pkg/promtail/targets/file/tailer.go:122 +0x1a9
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 424 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fb180)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 425 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc00094c580, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094c580)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 426 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fb280)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 427 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fb280)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 255 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e5e0, 0xc0006f70f8, 0xc0004d6e40, 0x2fdef00, 0xc000964820, 0xc0004d6e60)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 428 [semacquire]:
sync.runtime_SemacquireMutex(0xc00027d064, 0x0, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00027d060)
        /usr/local/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
github.com/go-kit/kit/log.(*fdSyncWriter).Write(0xc00027d060, 0xc000f08000, 0xa9, 0x183, 0x1, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/sync.go:89 +0xe8
github.com/go-kit/kit/log.logfmtLogger.Log(0x2f6a080, 0xc00027d060, 0xc000d62a80, 0xa, 0xc, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/logfmt_logger.go:58 +0x1b0
github.com/go-kit/kit/log/level.(*logger).Log(0xc000a18600, 0xc000d62a80, 0xa, 0xc, 0x577cf9, 0x247c480)
        /src/loki/vendor/github.com/go-kit/kit/log/level/level.go:63 +0xb4
github.com/cortexproject/cortex/pkg/util.(*PrometheusLogger).Log(0xc000a265a0, 0xc000d62a80, 0xa, 0xc, 0x4, 0x4)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/log.go:87 +0x55
github.com/go-kit/kit/log.(*context).Log(0xc000d58330, 0xc0003079c0, 0x4, 0x4, 0xc0003079c0, 0x2)
        /src/loki/vendor/github.com/go-kit/kit/log/log.go:124 +0x202
github.com/go-kit/kit/log.(*context).Log(0xc000d58c30, 0xc00046f5c0, 0x2, 0x2, 0x2, 0xc000d55d40)
        /src/loki/vendor/github.com/go-kit/kit/log/log.go:124 +0x202
github.com/grafana/loki/pkg/util.LogAdapter.Printf(0x2f6a060, 0xc000d58330, 0x2a7516b, 0x10, 0xc00046f540, 0x2, 0x2)
        /src/loki/pkg/util/log.go:68 +0x232
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094c630)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:305 +0x91d
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 429 [semacquire]:
sync.runtime_SemacquireMutex(0xc00027d064, 0x0, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00027d060)
        /usr/local/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
github.com/go-kit/kit/log.(*fdSyncWriter).Write(0xc00027d060, 0xc000f0c000, 0xa9, 0x164, 0x1, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/sync.go:89 +0xe8
github.com/go-kit/kit/log.logfmtLogger.Log(0x2f6a080, 0xc00027d060, 0xc0004e0400, 0xc, 0x10, 0x0, 0x0)
        /src/loki/vendor/github.com/go-kit/kit/log/logfmt_logger.go:58 +0x1b0
github.com/go-kit/kit/log/level.(*logger).Log(0xc000a18600, 0xc0004e0400, 0xc, 0x10, 0x577cf9, 0x247c480)
        /src/loki/vendor/github.com/go-kit/kit/log/level/level.go:63 +0xb4
github.com/cortexproject/cortex/pkg/util.(*PrometheusLogger).Log(0xc000a265a0, 0xc0004e0400, 0xc, 0x10, 0x4, 0x4)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/log.go:87 +0x55
github.com/go-kit/kit/log.(*context).Log(0xc000d58c90, 0xc000307a00, 0x4, 0x4, 0x2, 0x2f6a060)
        /src/loki/vendor/github.com/go-kit/kit/log/log.go:124 +0x202
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fb380)
        /src/loki/pkg/promtail/targets/file/tailer.go:122 +0x1a9
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 430 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fb380)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 431 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc00094c6e0, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094c6e0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 432 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fb480)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 433 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fb480)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 434 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc00094c790, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094c790)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 435 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fb580)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 404 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e880, 0xc0006f7518, 0xc000680e60, 0x2fdef00, 0xc0009c35f0, 0xc000680e80)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 436 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fb580)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 437 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc00094c840, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094c840)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 438 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fb680)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 439 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fb680)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 440 [runnable]:
github.com/hpcloud/tail.(*Tail).sendLine(0xc00094c8f0, 0xc000f0c480, 0x162, 0x0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:499 +0x165
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094c8f0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:334 +0x15a
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 441 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fb780)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 442 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fb780)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 443 [select]:
github.com/hpcloud/tail.(*Tail).waitForChanges(0xc00094c9a0, 0xc00007e060, 0xc00007e060, 0x2f69b01)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:425 +0x116
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094c9a0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:386 +0x515
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 444 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fb880)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 445 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fb880)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 446 [runnable]:
github.com/hpcloud/tail.(*Tail).sendLine(0xc00094ca50, 0xc000f36000, 0x15a, 0x0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:499 +0x165
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094ca50)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:334 +0x15a
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 447 [chan receive]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fb980)
        /src/loki/pkg/promtail/targets/file/tailer.go:136 +0x20c
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 448 [runnable]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fb980)
        /src/loki/pkg/promtail/targets/file/tailer.go:90
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 449 [runnable]:
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094cb00)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:287
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 450 [runnable]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fba80)
        /src/loki/pkg/promtail/targets/file/tailer.go:121
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 451 [runnable]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fba80)
        /src/loki/pkg/promtail/targets/file/tailer.go:90
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 452 [runnable]:
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094cbb0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:287
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 453 [runnable]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fbb80)
        /src/loki/pkg/promtail/targets/file/tailer.go:121
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 454 [runnable]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fbb80)
        /src/loki/pkg/promtail/targets/file/tailer.go:90
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 405 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e920, 0xc0006f7678, 0xc0006810c0, 0x2fdef00, 0xc0009c3a00, 0xc0006810e0)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 455 [runnable]:
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094cc60)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:287
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 456 [runnable]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fbc80)
        /src/loki/pkg/promtail/targets/file/tailer.go:121
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 457 [runnable]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fbc80)
        /src/loki/pkg/promtail/targets/file/tailer.go:90
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 458 [runnable]:
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094cd10)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:287
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 459 [runnable]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fbd80)
        /src/loki/pkg/promtail/targets/file/tailer.go:121
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 460 [runnable]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fbd80)
        /src/loki/pkg/promtail/targets/file/tailer.go:90
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 461 [runnable]:
github.com/hpcloud/tail.(*Tail).tailFileSync(0xc00094cdc0)
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:287
created by github.com/hpcloud/tail.TailFile
        /src/loki/vendor/github.com/hpcloud/tail/tail.go:134 +0x15a

goroutine 462 [runnable]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).readLines(0xc0005fbe80)
        /src/loki/pkg/promtail/targets/file/tailer.go:121
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:80 +0x53d

goroutine 463 [select]:
github.com/grafana/loki/pkg/promtail/targets/file.(*tailer).updatePosition(0xc0005fbe80)
        /src/loki/pkg/promtail/targets/file/tailer.go:100 +0x145
created by github.com/grafana/loki/pkg/promtail/targets/file.newTailer
        /src/loki/pkg/promtail/targets/file/tailer.go:81 +0x565

goroutine 256 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046ed60, 0xc0006f7eb8, 0xc0004d7280, 0x2fdef00, 0xc000965040, 0xc0004d72a0)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 406 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046ec20, 0xc0006f7ca8, 0xc000681100, 0x2fdef00, 0xc0009c3ba0, 0xc000681120)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 257 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046eda0, 0xc0006f7f68, 0xc0004d7340, 0x2fdef00, 0xc0009652b0, 0xc0004d7360)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 466 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046ee00, 0xc00094c288, 0xc0004d7400, 0x2fdef00, 0xc000965520, 0xc0004d7420)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 467 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046eec0, 0xc00094c3e8, 0xc0004d7540, 0x2fdef00, 0xc000965930, 0xc0004d7560)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 407 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e960, 0xc0006f7728, 0xc0006811c0, 0x2fdef00, 0xc0009c3d40, 0xc0006811e0)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 464 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046f0a0, 0xc00094c758, 0xc00046f6a0, 0x2fdef00, 0xc000d7cf70, 0xc00046f6c0)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 468 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046ef20, 0xc00094c498, 0xc0004d7600, 0x2fdef00, 0xc000965ba0, 0xc0004d7620)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 465 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046ec60, 0xc0006f7d58, 0xc00046f700, 0x2fdef00, 0xc000d7d110, 0xc00046f720)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 469 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046ef80, 0xc00094c548, 0xc0004d76c0, 0x2fdef00, 0xc000965e10, 0xc0004d76e0)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 482 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046f100, 0xc00094c808, 0xc00046f7e0, 0x2fdef00, 0xc000d7d2b0, 0xc00046f800)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 470 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046efe0, 0xc00094c5f8, 0xc0004d7780, 0x2fdef00, 0xc000e460d0, 0xc0004d77a0)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 483 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046f160, 0xc00094c8b8, 0xc00046f900, 0x2fdef00, 0xc000d7d520, 0xc00046f920)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 408 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e9a0, 0xc0006f77d8, 0xc000681280, 0x2fdef00, 0xc000e8e000, 0xc0006812c0)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 484 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046f2c0, 0xc00094ca18, 0xc00046fc60, 0x2fdef00, 0xc000d7d930, 0xc00046fc80)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 409 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046e9e0, 0xc0006f7888, 0xc000681360, 0x2fdef00, 0xc000e8e270, 0xc0006813a0)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

goroutine 485 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents.func1(0xc00046ed20, 0xc0006f7e08, 0xc00046fca0, 0x2fdef00, 0xc000d7dad0, 0xc00046fcc0)
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:68 +0x8f
created by github.com/hpcloud/tail/watch.(*PollingFileWatcher).ChangeEvents
        /src/loki/vendor/github.com/hpcloud/tail/watch/polling.go:59 +0x18c

### PR DESCRIPTION
**Pull request by cyriltovena**
Not fully sure how this was happening, but I have a test showing it's possible and a fix for it.

I think it should fix #3120.

I also remove race within some tests of promtail.

/cc @jeschkies WDYT ?

Signed-off-by: Cyril Tovena <cyril.tovena@gmail.com>

### CODE REVIEW

File: pkg/logentry/stages/multiline.go [hunk 1]
```diff
@@ -203,11 +203,15 @@ func (m *multilineStage) flush(out chan Entry, s *multilineState) {
...
 	}
-
+	// copy extracted data.
+	extracted := make(map[string]interface{}, len(s.startLineEntry.Extracted))
+	for k, v := range s.startLineEntry.Extracted {
+		extracted[k] = v
+	}
 	collapsed := Entry{
-		Extracted: s.startLineEntry.Extracted,
+		Extracted: extracted,
```
Comment (jeschkies) [inline pkg/logentry/stages/multiline.go:212]: That's interesting. I thought `Extracted` would be a value not a reference. *few minutes googling later*

Ok, maps are references, see https://blog.golang.org/maps:

> Map types are reference types, like pointers or slices, and so the value of m above is nil; it doesn't point to an initialized map.

:facepalm: 

So either we send a copy across the channel. Or we reset the entry but that would be a little bit more complicated.

**Comment by chancez** [comment]
This looks like it worked! I ran the original test-case I was using before on master, it panics literally immediately, and after switching to a build of promtail from this branch, it's running through the logs, updating my cursor, etc, no panic.

**Review by jeschkies — APPROVED** [review]
Nice. Should enable `go build -race`? I wonder if it would have caught this one.

**Review by sandeepsukhani — APPROVED** [review]
