### PR TITLE
fix(distributor): parseError BadRequest

### LINKED ISSUE #929: loki returns 500 code for parse error in labels
**Describe the bug**
If you provide a POST to `/api/prom/push` where the "labels" member is unparseable, loki rejects it with a 500 error.  IMO it should be 400.

500 implies that (a) the fault is at the server side, not with the client-provided data; and (b) that it may work if the client resends the same request later, which clearly it won't in this case.

(Extracted from #927)

**To Reproduce**
1. Started loki (v0.3.0)
2. Submit with curl where "labels" contains an unterminated string - see end

**Expected behavior**
A 400 "Bad Request" error code (which is the behaviour if the request is invalid for other reasons, e.g. you submit a log timestamp that is too far in the past)

**Environment:**
 - Ubuntu 18.04
 - Manual build

**Screenshots, promtail config, or terminal output**

Trimmed request:

```
# curl -v -H Content-Type:application/json -d '{"streams":[{"labels":"{foo=\"bar}"}]}' http://127.0.0.1:3100/api/prom/push
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3100 (#0)
> POST /api/prom/push HTTP/1.1
> Host: 127.0.0.1:3100
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type:application/json
> Content-Length: 38
>
* upload completely sent off: 38 out of 38 bytes
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Wed, 21 Aug 2019 10:29:58 GMT
< Content-Length: 53
<
parse error at line 1, col 6: literal not terminated
* Connection #0 to host 127.0.0.1 left intact
```

A more complete request which showed this:

```
# curl -v -H Content-Type:application/json -d '{"streams":[{"labels":"{job=\"fluent.info\",source=\"\",facility=\"\",severity=\"\",program=\"\",foo=\"\"\"}","entries":[{"ts":"2019-08-21T09:34:34.733352Z","line":"worker=\"0\" message=\"fluentd worker is now stopping worker=0\""}]}]}' http://127.0.0.1:3100/api/prom/push
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3100 (#0)
> POST /api/prom/push HTTP/1.1
> Host: 127.0.0.1:3100
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type:application/json
> Content-Length: 235
>
* upload completely sent off: 235 out of 235 bytes
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Wed, 21 Aug 2019 10:24:12 GMT
< Content-Length: 54
<
parse error at line 1, col 71: literal not terminated
* Connection #0 to host 127.0.0.1 left intact
```

### PR DESCRIPTION
**Pull request by sh0rez**
When the label validation in the distributor failed, it was reported as `500 Internal Server Error` instead of `400 BadRequest`. 

Fixes #929

### CODE REVIEW

File: pkg/distributor/http.go [hunk 1]
```diff
@@ -39,10 +40,15 @@ func (d *Distributor) PushHandler(w http.ResponseWriter, r *http.Request) {
 		return
 	}
 
-	resp, ok := httpgrpc.HTTPResponseFromError(err)
-	if ok {
+	if parseErr, ok := err.(logql.ParseError); ok {
```
Comment (slim-bean) [inline pkg/distributor/http.go]: I'm not sure if i'm just missing this, but I don't see where the distributor code ever throws a `logql.ParseError`? this sounds more like something we would see on the query path, not the write path.

Comment (sh0rez) [reply pkg/distributor/http.go]: I can't tell where the error comes from, but it ends up here. And this works...

Comment (candlerb) [reply pkg/distributor/http.go]: Presumably, on the write path the "labels" value must be parsed somewhere

Comment (sh0rez) [reply pkg/distributor/http.go]: @slim-bean the `logql.ParseError` comes from here:
https://github.com/grafana/loki/blob/29f08ccb1cde0e26d57d2c95e293eceb4df17976/pkg/distributor/distributor.go#L148

This is actual ingester logic, so it seems good to me?
