### PR TITLE
Fix: Ensure query limits tripperware wraps frontend.

### LINKED ISSUE #8790: Ensure `LimitsMiddleware` is injected after per-request limits middleware.
The query frontend should reject queries that violate per-request limits. They were introduced with https://github.com/grafana/loki/pull/8727. However, do not seem to be enforce in the frontend but only the querier.

### PR DESCRIPTION
**Pull request by jeschkies**
**What this PR does / why we need it**:
The query frontend would not enforce the per-request query limits because the injected tripperware was wrapped *after* the frontend has been created. That is a bug. The order must be changed so that the `queryrange.LimitsMiddleware` runs *after* the `querylimits.limitsMiddleware`.

**Which issue(s) this PR fixes**:
Fixes #8790

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [x] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

File: integration/loki_micro_services_test.go [hunk 1]
```diff
@@ -126,4 +129,13 @@ func TestMicroServicesIngestQuery(t *testing.T) {
 		require.NoError(t, err)
 		assert.ElementsMatch(t, []string{"fake"}, resp)
 	})
+
+	t.Run("per-request-limits", func(t *testing.T) {
+		queryLimitsPolicy := client.InjectHeadersOption(map[string][]string{querylimits.HTTPHeaderQueryLimitsKey: {`{"maxQueryLength": "1m"}`}})
```
Comment (cstyan) [inline integration/loki_micro_services_test.go:134]: am I missing some config that we have for this test client, I thought 1m was the default timeout, so this test should pass?

File: pkg/loki/loki.go [hunk 2]
```diff
@@ -674,13 +674,25 @@ func (t *Loki) setupModuleManager() error {
...
-		deps[Querier] = append(deps[Querier], QueryLimiter)
-		deps[QueryFrontend] = append(deps[QueryFrontend], QueryLimitsTripperware)
-
+		// Ensure query limiter embeds overrides after they've been
+		// created.
 		deps[QueryLimiter] = []string{Overrides}
 		deps[QueryLimitsInterceptors] = []string{}
+
+		// Ensure query limits tripperware embeds the query frontend
+		// tripperware after it's been created.
```
Comment (cstyan) [inline pkg/loki/loki.go:683]: can we include in this comment `any additional milleware/tripperware you want to add to the querier or frontend must happen after this line`? I think this is the right spot for that addition

File: integration/loki_micro_services_test.go [hunk 3]
```diff
@@ -10,6 +10,8 @@ import (
 
 	"github.com/grafana/loki/integration/client"
 	"github.com/grafana/loki/integration/cluster"
+
```
Comment (cstyan) [inline integration/loki_micro_services_test.go:13]: nit, this extra newline can be removed

**Review by cstyan — COMMENTED** [review]
minor comments

File: integration/loki_micro_services_test.go (hunk 1 above)
Comment (jeschkies) [reply integration/loki_micro_services_test.go:134]: It's the query length limit that defaults to sixty or thirty minutes. You see the change to the frontend config in line 69 above.

Comment (cstyan) [reply integration/loki_micro_services_test.go:133]: I was missing that the setup of the `cliQueryFrontendLimited` and calling `cliQueryFrontendLimited.LabelNames` uses a time of `30 * time.Minute` defined in `integration/client.go` :+1:

**Review by cstyan — APPROVED** [review]
