### PR TITLE
fix: allow boolean numeric values in detected labels

### LINKED ISSUE #16859: /detected_labels endpoint incorrectly filters out fields with numeric values
**Describe the bug**
User reported a `probe_success` label with values `0` and `1` was being omitted from the label breakdown panel in Logs Drilldown (see screenshot below). This seems to be because of the behavior in the [`containsAllIDTypes`](https://github.com/grafana/loki/blob/d359e0d709e3b8e4afce53f703eeb70d4e869031/pkg/querier/querier.go#L881-L893) filter, which removes numeric values in an effort to remove uids, which are by their nature high cardinality, but should not remove low cardinality numeric values like the his exmaple.

**To Reproduce**
1. Send logs with a low cardinality numeric label, such as a binary `0` or `1`
2. Hit the `/detected_labels` endpoint with a selector that will match that stream
3. See that your low cardinality numeric field is missing.

**Expected behavior**
Low cardinality numeric field is present in response

**Environment:**
 - Cloud Logs

**Screenshots, Promtail config, or terminal output**
Image

### PR DESCRIPTION
**Pull request by trevorwhitney**
**What this PR does / why we need it**:

In general, we want to filter out numeric or uuid values in the detected labels endpoint as these are too high in cardinality. However, a 0/1 value representing a boolean is a common use case and should be allowed as it will not result in high cardinality.

**Which issue(s) this PR fixes**:
Fixes #16859 

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

File: pkg/querier/querier.go [hunk 1]
```diff
@@ -877,7 +877,43 @@ func (q *SingleTenantQuerier) Patterns(ctx context.Context, req *logproto.QueryP
...
+			"true":  true,
+			"false": true,
+			"0":     true,
+			"1":     true,
+		}
+
+		allBooleans := true
+		for _, v := range values {
+			if !boolValues[v] {
+				allBooleans = false
```
Comment (shantanualsi) [inline pkg/querier/querier.go:902]: may be just return false here? :D

**Review by shantanualsi — APPROVED** [review]
LGTM!
