### PR TITLE
[bugfix] scheduler: Gracefully shutdown querier when using query-scheduler

### LINKED ISSUE #7722: [deadlock] scheduler: if querier OOM restart .
**Describe the bug**
I deploy frontend+scheduler+querier 3 components in k8s to complete logql API query. 

According to my observation, when the queryer is killed by k8s due to OOM, the logql query will be unavailable. And the log keeps reporting errors. 

frontend log
```log
level=error ts=2022-11-18T10:52:00.862957605Z caller=retry.go:77 org_id=123_qaawmopdln 
msg=\"error processing request\" try=0 err=\"context canceled\"
```

The phenomenon is somewhat similar to deadlock. But I'm still investigating the rootcause.

**To Reproduce**
I deploy loki without helm, it's diffcult to reproduce .

**Expected behavior**
if querier was killed, logql should be available.

**Environment:**
 - Infrastructure: [Kubernetes]
 - Deployment tool: [deploy yaml one by one]
 - loki code branch : github master

**Screenshots, Promtail config, or terminal output**
scheduler log
image

image

prometheus metrics
image

querier cpu and memory
image

frontend querylog
image

### PR DESCRIPTION
**Pull request by liguozhong**
**What this PR does / why we need it**:
Gracefully shutdown querier when using query-scheduler
This PR is an attempt to fix a bug that my loki cluster is unavailable for logql. The source code and ideas are from mimir of LGTM. Thanks mimir and pr author @pracucci 

**Which issue(s) this PR fixes**:
Fixes #7722

**Special notes for your reviewer**:
mimir PR
https://github.com/grafana/mimir/pull/1756
https://github.com/grafana/mimir/pull/1767

**Checklist**
- [x] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [x] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

File: pkg/querier/worker/scheduler_processor.go [hunk 1]
```diff
@@ -71,29 +78,33 @@ func (sp *schedulerProcessor) notifyShutdown(ctx context.Context, conn *grpc.Cli
...
 			continue
 		}
 
-		if err := sp.querierLoop(c, address); err != nil {
-			// E.Welch I don't know how to do this any better but context cancelations seem common,
-			// likely because of an underlying connection being close,
-			// they are noisy and I don't think they communicate anything useful.
-			if !strings.Contains(err.Error(), "context canceled") {
+		if err := sp.querierLoop(c, address, inflightQuery); err != nil {
+			// Do not log an error is the query-scheduler is shutting down.
```
Comment (jeschkies) [inline pkg/querier/worker/scheduler_processor.go:103]:
```suggestion
			// Do not log an error if the query-scheduler is shutting down.
```

File: pkg/querier/worker/scheduler_processor.go [hunk 2]
```diff
@@ -114,23 +125,31 @@ func (sp *schedulerProcessor) querierLoop(c schedulerpb.SchedulerForQuerier_Quer
...
+			if parentSpanContext != nil {
+				queueSpan, spanCtx := opentracing.StartSpanFromContextWithTracer(ctx, tracer, "querier_processor_runRequest", opentracing.ChildOf(parentSpanContext))
+				defer queueSpan.Finish()
 
-			sp.runRequest(ctx, logger, request.QueryID, request.FrontendAddress, request.StatsEnabled, request.HttpRequest)
+				ctx = spanCtx
+			}
+			logger := util_log.WithContext(ctx, sp.log)
 
-			sp.metrics.inflightRequests.Dec()
```
Comment (jeschkies) [inline pkg/querier/worker/scheduler_processor.go:133]: Where did this go?

File: pkg/querier/worker/util.go [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+
+	go func() {
+		// Wait until it's safe to cancel the execution context, which is when one of the following conditions happen:
+		// - The worker context has been canceled and there's no inflight query
+		// - The execution context itself has been explicitly canceled
+		select {
+		case <-workerCtx.Done():
+			level.Debug(logger).Log("msg", "querier worker context has been canceled, waiting until there's no inflight query")
+
+			for inflightQuery.Load() {
```
Comment (jeschkies) [inline pkg/querier/worker/util.go:40]: What happens when the query is never processed? Also, isn't there a potential race condition between testing the flag and setting it in the querier loop? It could be false here but then the next query is received.

**Review by jeschkies — CHANGES_REQUESTED** [review]
This is great work but I need to understand the synchronization of `inflightQuery` a little better.

How do you feel about using a `WaitGroup` instead. This would also avoid using a busy loop. A mutex would be easier to reason about as well.

File: pkg/querier/worker/scheduler_processor.go (hunk 2 above)
Comment (liguozhong) [reply pkg/querier/worker/scheduler_processor.go:133]: Hi, this was my mistake, I simply ‘copied’ scheduler mimir's code to loki, ignoring the inflightRequests metrics. 
I have submitted a commit which fixes this issue.

File: pkg/querier/worker/util.go (hunk 3 above)
Comment (liguozhong) [reply pkg/querier/worker/util.go:40]: https://github.com/grafana/mimir/blob/main/pkg/querier/worker/util.go

This util.go is completely copied from mimir. I will deploy this PR to my loki cluster and run it for a while to verify whether this PR will cause unexpected race risks.

**Comment by liguozhong** [comment]
> How do you feel about using a `WaitGroup` instead. This would also avoid using a busy loop. A mutex would be easier to reason about as well.

Thanks you for your timely review. this pr is really important to me .I've been trying to fix #7722 for 18 days.

I prefer to keep the current code, which will make loki and mimir use the same scheduler code, even if there is a problem with this code, it can be fixed together with the mimir community.

**Comment by dannykopping** [comment]
@jeschkies can you take another pass at this pls?

**Comment by liguozhong** [comment]
Good news, I deployed this PR to my loki cluster and Fixes https://github.com/grafana/loki/issues/7722. 

At present, the recording rule has been running stably for 1 day. This PR seems to be useful.

image

File: pkg/querier/worker/util.go (hunk 3 above)
Comment (jeschkies) [reply pkg/querier/worker/util.go:40]: Hm. We somehow need to document this. I'll try to find the original author.

Comment (pracucci) [reply pkg/querier/worker/util.go:40]: > Also, isn't there a potential race condition between testing the flag and setting it in the querier loop? It could be false here but then the next query is received.

When the querier shutdowns it's expected to cancel the context and so the call to `request, err := c.Recv()` (done in `schedulerProcessor.querierLoop()`) to return error because of the canceled context (I mean the querier context, not the query execution context).

Is there a race? Yes, there's a race between the call to `c.Recv()` and the sequent call to `inflightQuery.Store(true)`, but the time window is very short and we ignored it in Mimir (all in all we want to gracefully handle the 99.9% of cases).

Comment (pracucci) [reply pkg/querier/worker/util.go:40]: > What happens when the query is never processed?

Can you elaborate this?

Comment (jeschkies) [reply pkg/querier/worker/util.go:40]: I was wondering if we can end up in a state were the query is inflight but we shut down. I guess it times out.

Comment (pracucci) [reply pkg/querier/worker/util.go:40]: I think that race condition still exists (I found it very hard to guarantee to never happen) but in practice should be very unlikely.

Comment (jeschkies) [reply pkg/querier/worker/util.go:40]: @liguozhong would you mind add a small comment summarizing Marco's answer?

**Review by jeschkies — APPROVED** [review]
Thanks for you hard work and patience. Could you add a comment on the possible race condition.

**Comment by liguozhong** [comment]
> Thanks for you hard work and patience. Could you add a comment on the possible race condition.

done
