### PR TITLE
Log error message for invalid checksum

### LINKED ISSUE #1346: Invalid chunk cksum
Hello. We are trying to run loki in our private k8s environment. But unfortunatelly we had several occasions when it was just useless because of that problem. It usually happens on large intervals (24h for example) and with "grep" requests.
Idk if it has something to do with server stability or something else. But it would be nice to just skip broken chunk and proceed further, spitting some warning or error to loki's log. Because now I see nothing in it's logs, the request just returns "Invalid chunk cksum".

### PR DESCRIPTION
**Pull request by adityacs**
**What this PR does / why we need it**:
Skip `chunks` with `invalid checkusm` and log error message.

**Which issue(s) this PR fixes**:
Fixes #1346 

**Checklist**
- [x] Tests updated

### CODE REVIEW

**Comment by adityacs** [comment]
@cyriltovena Have few queries.
1. What should we log in the error message for invalid checksum? Available fields are `blocksize`, `bytes` etc. This won't be useful for the user. 
2. I think we should just skip and continue here while iterating blocks of chunk https://github.com/grafana/loki/blob/65013218b72cdd45237b73732aab420e67adc5a5/pkg/chunkenc/memchunk.go#L232
    Is it ok to skip here? when the checksum of chunk meta is not valid https://github.com/grafana/loki/blob/65013218b72cdd45237b73732aab420e67adc5a5/pkg/chunkenc/memchunk.go#L208

File: pkg/chunkenc/memchunk.go [hunk 1]
```diff
@@ -205,6 +208,7 @@ func NewByteChunk(b []byte) (*MemChunk, error) {
 
 	expCRC := binary.BigEndian.Uint32(b[len(b)-(8+4):])
 	if expCRC != db.crc32() {
+		level.Error(logger).Log("msg", "Checksum doesnot match for chunck meta")
```
Comment (cyriltovena) [inline pkg/chunkenc/memchunk.go]:
```suggestion
		level.Error(logger).Log("msg", "Checksum does not match for chunk meta")
```

File: pkg/chunkenc/memchunk.go [hunk 2]
```diff
@@ -35,6 +37,7 @@ var (
 // with any other use of the crc32 package anywhere. Thus we initialize it
 // before.
 var castagnoliTable *crc32.Table
+var logger log.Logger
```
Comment (cyriltovena) [inline pkg/chunkenc/memchunk.go]: you need to use util.Logger instead which is initialized. This one is not :)

File: pkg/chunkenc/memchunk.go [hunk 3]
```diff
@@ -229,7 +233,9 @@ func NewByteChunk(b []byte) (*MemChunk, error) {
 		// Verify checksums.
 		expCRC := binary.BigEndian.Uint32(b[blk.offset+l:])
 		if expCRC != crc32.Checksum(blk.b, castagnoliTable) {
-			return bc, ErrInvalidChecksum
+			level.Error(logger).Log("msg", "Checksum doesnot match for chunck block")
+			continue
+			//return bc, ErrInvalidChecksum
```
Comment (cyriltovena) [inline pkg/chunkenc/memchunk.go]: You should may be look at who is using this and keep that error returned there. The usage of this should verify if this is a checksum error we can skip.

Comment (cyriltovena) [reply pkg/chunkenc/memchunk.go]: Basically I wouldn't make the change here, but at a higher level.

Comment (adityacs) [reply pkg/chunkenc/memchunk.go]: At the block level, should we just skip the whole Chunk if one of the blocks has invalid checksum? or we should continue iterating other blocks?

Comment (cyriltovena) [reply pkg/chunkenc/memchunk.go]: we should continue iterating other blocks

File: pkg/chunkenc/memchunk.go (hunk 2 above)
Comment (adityacs) [reply pkg/chunkenc/memchunk.go]: Sure

File: pkg/chunkenc/memchunk.go [hunk 4]
```diff
@@ -229,7 +231,8 @@ func NewByteChunk(b []byte) (*MemChunk, error) {
 		// Verify checksums.
 		expCRC := binary.BigEndian.Uint32(b[blk.offset+l:])
 		if expCRC != crc32.Checksum(blk.b, castagnoliTable) {
-			return bc, ErrInvalidChecksum
+			level.Error(util.Logger).Log("msg", "Checksum does not match for a block in chunk, this block will be skipped", "err", ErrInvalidChecksum)
```
Comment (adityacs) [inline pkg/chunkenc/memchunk.go]: We don't have any indication to blocks in a chunk. We can identify the blocks only with their offsets. Can we add a field `block number` to `block` struct so that we can indicate blocks uniquely?

File: pkg/ingester/transfer.go [hunk 5]
```diff
@@ -98,8 +98,13 @@ func (i *Ingester) TransferChunks(stream logproto.Ingester_TransferChunksServer)
 
 		instance := i.getOrCreateInstance(chunkSet.UserId)
 		for _, chunk := range chunkSet.Chunks {
-			if err := instance.consumeChunk(userCtx, lbls, chunk); err != nil {
-				return err
+			err := instance.consumeChunk(userCtx, lbls, chunk) err != nil {
+				if err.Error() == "invalid checksum" {
+					level.Error(util.Logger).Log("msg", "Checksum does not match for chunk, this chunk will be skipped", "err", "invalid checksum", "chunk", chunk.String())
```
Comment (adityacs) [inline pkg/ingester/transfer.go]: Not sure if logging `chuck.String()` is a good idea

Comment (adityacs) [reply pkg/ingester/transfer.go]: I am not able reproduce this issue(#1346). Can we request the author of this issue to validate from his side using this commit and see what he sees in his logs?

Comment (cyriltovena) [reply pkg/ingester/transfer.go]: I don't think this change is necessary since now you're not sending back the invalid error.

File: pkg/chunkenc/memchunk.go (hunk 4 above)
Comment (cyriltovena) [reply pkg/chunkenc/memchunk.go]: I wouldn't change anything here. I think this looks good.

However if the full chunk is invalid it still send an error see above :
```go
if expCRC != db.crc32() {
		return nil, ErrInvalidChecksum
	}
```

which means we need to take care of this.

The error will buble up from cortex to this line https://github.com/grafana/loki/blob/master/pkg/storage/iterator.go#L404

Careful this is difficult to change :)

But you want to:

1 - Check if `err == chunkenc.ErrInvalidChecksum` if so you need to skip that chunk and log the error. (meaning send back `errChan <- nil`)
2 - However you can't leave an item in `chunks []*chunkenc.LazyChunk` with `LazyChunk.Chunk.Data` empty (otherwise you'll endup with an iterator error here https://github.com/grafana/loki/blob/master/pkg/chunkenc/lazy_chunk.go#L28), this means you need to remove the item from the list. I think you should do that after waiting for all err from the chan :
```go
	var lastErr error
	for i := 0; i < len(chksByFetcher); i++ {
		if err := <-errChan; err != nil {
			lastErr = err
		}
	}
if lastErr == nil {
// remove any lazy chunk with no data aka chunks[i].Chunk.Data == nil.
}
```

I think it's key here that you write a good test for this function to ensure it skips correctly bad chunks. You can abstract away the Fetcher interface and fake this error. `chks, err := fetcher.FetchChunks(ctx, chks, keys)` since fetcher is passed inside LazyChunk array.

Take your time to understand this function and good luck ✌️ .

File: pkg/ingester/transfer.go (hunk 5 above)
Comment (cyriltovena) [reply pkg/ingester/transfer.go]: Let's leave the transfer erroring (rollback that file), I don't think this is causing any issue for #1346.

File: pkg/chunkenc/memchunk.go (hunk 4 above)
Comment (cyriltovena) [reply pkg/chunkenc/memchunk.go]: No need for now. Let's first tackle the problem of not being able to reply if couple of chunks are bad out of the whole batch.

Comment (adityacs) [reply pkg/chunkenc/memchunk.go]: @cyriltovena should we just check for `invalid checksum`. Any error which comes here https://github.com/cortexproject/cortex/blob/f1f513ec1de84e87ede492cad87ed8e6d2af0237/pkg/chunk/local/fs_object_client.go#L77 is a potential chunk error. The `invalid checksum` error may we come here https://github.com/cortexproject/cortex/blob/f1f513ec1de84e87ede492cad87ed8e6d2af0237/pkg/chunk/local/fs_object_client.go#L92 due to `invalid checksum` of chunk meta. Later in the code `NewByteChunk` of `loki` code is called and we might get `invalid checksum` there  as well.

So, my question is, should we just check `invalid checksum` error given by `loki` code and just log it and continue iterating other chunks?
OR
Should we  just log any error related `chunk` rather than returning that error?

Comment (cyriltovena) [reply pkg/chunkenc/memchunk.go]: I would continue only in case of `invalid checksum`, this won't resolved itself. Other errors can be logged but we should stop.

Comment (adityacs) [reply pkg/chunkenc/memchunk.go]: Ok. Will update code accordingly

File: pkg/storage/iterator.go [hunk 6]
```diff
@@ -385,6 +385,7 @@ func fetchLazyChunks(ctx context.Context, chunks []*chunkenc.LazyChunk) error {
 	}
 	level.Debug(log).Log("msg", "loading lazy chunks", "chunks", totalChunks)
 
+	invalidChunks := make(chan *chunk.Fetcher)
```
Comment (adityacs) [inline pkg/storage/iterator.go]: I am creating this channel so that later when we have to remove data for chunks which are invalid, we can iterate only few chunks rather than iterating all fetchers and chunks.

File: pkg/storage/iterator.go [hunk 7]
```diff
@@ -415,6 +423,13 @@ func fetchLazyChunks(ctx context.Context, chunks []*chunkenc.LazyChunk) error {
 		}(fetcher, chunks)
 	}
 
+	// remove data of any invalid chunk
+	for fetcher := range invalidChunks {
+		for _, chk := range chksByFetcher[fetcher] {
+			chk.Chunk.Data = nil
+		}
+	}
+
```
Comment (adityacs) [inline pkg/storage/iterator.go]: @cyriltovena Kindly validate above code change before I add testcases and do cleanup.

File: pkg/storage/iterator.go [hunk 8]
```diff
@@ -415,6 +423,13 @@ func fetchLazyChunks(ctx context.Context, chunks []*chunkenc.LazyChunk) error {
 		}(fetcher, chunks)
 	}
 
+	// remove data of any invalid chunk
+	for _, fetcher := range invalidChunks {
+		for _, chk := range chksByFetcher[fetcher] {
+			chk.Chunk.Data = nil
+		}
+	}
+
```
Comment (adityacs) [inline pkg/storage/iterator.go]: @cyriltovena Kindly validate above code change before I add testcases and do cleanup.

File: pkg/storage/iterator.go [hunk 9]
```diff
@@ -385,6 +385,7 @@ func fetchLazyChunks(ctx context.Context, chunks []*chunkenc.LazyChunk) error {
 	}
 	level.Debug(log).Log("msg", "loading lazy chunks", "chunks", totalChunks)
 
+	invalidChunks := []*chunk.Fetcher{}
```
Comment (adityacs) [inline pkg/storage/iterator.go]: Reason for creating this array is later when we have to remove invalid chunks, we can iterate only invalid chunks rather than iterating all fetchers and chunks

File: pkg/storage/iterator.go [hunk 10]
```diff
@@ -403,8 +404,15 @@ func fetchLazyChunks(ctx context.Context, chunks []*chunkenc.LazyChunk) error {
 			}
 			chks, err := fetcher.FetchChunks(ctx, chks, keys)
 			if err != nil {
+				if err.Error() == chunk.ErrInvalidChecksum.Error() {
```
Comment (cyriltovena) [inline pkg/storage/iterator.go]:
```suggestion
				if err == chunk.ErrInvalidChecksum {
```

File: pkg/storage/iterator.go [hunk 11]
```diff
@@ -403,8 +404,15 @@ func fetchLazyChunks(ctx context.Context, chunks []*chunkenc.LazyChunk) error {
...
+					level.Error(util.Logger).Log("msg", "checksum of chunks does not match", "err", chunk.ErrInvalidChecksum)
+					invalidChunks = append(invalidChunks, fetcher)
```
Comment (cyriltovena) [inline pkg/storage/iterator.go]: I don't think you need this invalid chunks array.

File: pkg/storage/iterator.go [hunk 12]
```diff
@@ -415,6 +423,13 @@ func fetchLazyChunks(ctx context.Context, chunks []*chunkenc.LazyChunk) error {
 		}(fetcher, chunks)
 	}
 
+	// remove data of any invalid chunk
+	for _, fetcher := range invalidChunks {
```
Comment (cyriltovena) [inline pkg/storage/iterator.go]: You need to remove empty chunk from the `chunks` variable. And this needs to happens when we have waited for all errors.

after:

```golang
var lastErr error
	for i := 0; i < len(chksByFetcher); i++ {
		if err := <-errChan; err != nil {
			lastErr = err
		}
	}

if lastErr != nil {
 return lastErr
}
i := 0 // output index
for _, c := range chunks {
    if c.Chunk.Data != nil {
        chunks[i] = c
        i++
    }
}
chunks = chunks[:i]
return nil
```

File: pkg/storage/iterator.go (hunk 8 above)
Comment (cyriltovena) [reply pkg/storage/iterator.go]: Gave you feedback !

File: pkg/storage/iterator.go (hunk 9 above)
Comment (cyriltovena) [reply pkg/storage/iterator.go]: No need for this.

File: pkg/storage/iterator.go (hunk 12 above)
Comment (adityacs) [reply pkg/storage/iterator.go]: Got you

Comment (adityacs) [reply pkg/storage/iterator.go]: @cyriltovena I see a problem here. I may not be correct though.
From the following function https://github.com/grafana/loki/blob/master/pkg/storage/iterator.go#L280, we first partitionBySeriesChunks, which partitions chunks based on overlapping iterator. At this stage say `chunksBySeries` has chunks as below
chksBySeries after partition
```
[0xc00011c400]
[0xc00011c480]
[0xc00011c500 0xc00011c600]
[0xc00011c580]
```
Later first chunks are loaded from `loadFirstChunks` which is passed with value `chksBySeries`. After this `chksBySeries` looks as below 
```
[0xc00011c400]
[0xc00011c480]
[0xc00011c500 0xc00011c600]
[0xc00011c580]
```

and in turn `fetchLazyChunks` would have picked following chunks
`[0xc00011c400 0xc00011c480 0xc00011c500 0xc00011c580]`

Even at this point `chkBySeries` has below values
```
[0xc00011c400]
[0xc00011c480]
[0xc00011c500 0xc00011c600]
[0xc00011c580]
```
Later `filterSeriesByMatchers` is called with value `chksBySeries` and `chksBySeries` has following values
```
[[0xc00011c500 0xc00011c600][0xc00011c580]]
```
Now, say `0xc00011c600` chunk returns `invalid chunk checksum` when doing` fetchLazyChunks` and the chunks picked are `[0xc00011c500],[0xc00011c580]`, Iterator is not affected with this because `buildIterators` is passed with `chksBySeries` which iterates following chunks
`[[0xc00011c500 0xc00011c600][0xc00011c580]]`. Since, `0xc00011c600` is having no data, iterator errors saying `chunks not loaded`. 

May be we should check for `nil Data` chunk here https://github.com/grafana/loki/blob/master/pkg/storage/iterator.go#L335 and skip it 
OR
Re arrange `chkBySeries` after fetching lazy chunks before calling `buildIterators` here https://github.com/grafana/loki/blob/master/pkg/storage/iterator.go#L305

Comment (cyriltovena) [reply pkg/storage/iterator.go]: I'm off for a week. We'll get back to you then.

Comment (adityacs) [reply pkg/storage/iterator.go]: Sure. Tried to add a dummy code here https://play.golang.org/p/HFXOy5Ek2xd. This should explain what's actually happening.

Comment (cyriltovena) [reply pkg/storage/iterator.go]: The only problem I see with my suggestions is that you might actually discard a lot of chunks if the first chunk is corrupted, but that's still better than crashing so let's do that and we can review this later if someone has an issue with it.

Comment (adityacs) [reply pkg/storage/iterator.go]: `discard a lot of chunks if the first chunk is corrupted`, this is the same behaviour currently right?

Comment (cyriltovena) [reply pkg/storage/iterator.go]: yes

Comment (adityacs) [reply pkg/storage/iterator.go]: So, just leave things as is and close PR?

Comment (cyriltovena) [reply pkg/storage/iterator.go]: No currently it crashes. I want this function to be changed like we discussed.

Comment (adityacs) [reply pkg/storage/iterator.go]: Sorry I was explaining things without pushing code. The code added fails [here](https://cloud.drone.io/grafana/loki/2199/1/2). The test code is not neat. Just validating things. However, we get into below scenario.

The chunks we get here https://github.com/grafana/loki/pull/1713/files#diff-7d61465906fc121b68e860420fcd1c87R440 may be like 
`[chunk1, chunk3]`. However, `chksBySeries` here https://github.com/grafana/loki/blob/64a1c0d96bd033d67c634aff195fe1b0b96441c5/pkg/storage/iterator.go#L305 might have chunks as `[[chunk1, chunk2][chunk3]]`. So, if `chunk2` is having `nil` data due to `invalid checksum` `chksBySeries` don't drop the chunk. Which leads to `chunk is not loaded` here https://github.com/grafana/loki/blob/64a1c0d96bd033d67c634aff195fe1b0b96441c5/pkg/chunkenc/lazy_chunk.go#L29

We should re-arrange the chunks before calling `buildIterators` https://github.com/grafana/loki/blob/64a1c0d96bd033d67c634aff195fe1b0b96441c5/pkg/storage/iterator.go#L305

Comment (cyriltovena) [reply pkg/storage/iterator.go]: Yes That's what I tried to explain you should remove the lazy chunk from the array.

**Comment by cyriltovena** [comment]
I think you're still working on this right ? We can close and open a new one if you want to clear things up when you're ready.

File: pkg/storage/iterator.go (hunk 12 above)
Comment (adityacs) [reply pkg/storage/iterator.go]: I am just checking for easy ways to do this  Removing a chunk from an array is quiet a costly operation. We would have to remove an element and shift other elements. When we have large number of chunks to load, this can turn out to be time taking process. 

One easy way is to label the chunk as `invalid` or `valid` or may be a boolean. Then in the iterators we can check if the chunk is valid or not. If invalid we can skip and continue.

what's your thought on this?

**Comment by adityacs** [comment]
Yeah, I am still working on this. Anything is fine with me. However, since we have had a good discussion on this PR, I would like to get this PR merged rather opening new PR.

It's your call finally.

File: pkg/storage/iterator.go (hunk 12 above)
Comment (adityacs) [reply pkg/storage/iterator.go]: @cyriltovena Need your feedback on this

File: pkg/storage/iterator.go [hunk 13]
```diff
@@ -297,23 +297,44 @@ func newChunksIterator(ctx context.Context, chunks []*chunkenc.LazyChunk, matche
...
+		for _, chunks := range series {
+			for _, chunk := range chunks {
+				if contains(chunk, allChunks) {
+					validChunks[chunk] = true
+				}
+			}
+		}
+	}
+
+	iters, err := buildIterators(ctx, chksBySeries, validChunks, filter, direction, from, through)
```
Comment (adityacs) [inline pkg/storage/iterator.go]: @cyriltovena This is one way we can check and avoid iterating invalid chunks. However, this is going to be O(n^3) operation. 

We can add a label to `LazyChunk` like below but we will have to change many references and disturb the code a bit.

```
type LazyChunk struct {
	Chunk   chunk.Chunk
         IsValid   bool
	Fetcher *chunk.Fetcher
}
```

What do you suggest?

Comment (cyriltovena) [reply pkg/storage/iterator.go]:
```
type LazyChunk struct {
	Chunk   chunk.Chunk
        IsValid   bool
	Fetcher *chunk.Fetcher
}
```

Is less intrusive for this code base IMO I prefer this.

Comment (adityacs) [reply pkg/storage/iterator.go]: Sure. Thanks

File: pkg/storage/iterator.go [hunk 14]
```diff
@@ -323,15 +344,18 @@ func buildIterators(ctx context.Context, chks map[model.Fingerprint][][]*chunken
...
 	result := make([]iter.EntryIterator, 0, len(chks))
-
+	log, ctx := spanlogger.New(ctx, "LokiStore.fetchLazyChunks")
 	// __name__ is only used for upstream compatibility and is hardcoded within loki. Strip it from the return label set.
 	labels := dropLabels(chks[0][0].Chunk.Metric, labels.MetricName).String()
-
 	for i := range chks {
 		iterators := make([]iter.EntryIterator, 0, len(chks[i]))
 		for j := range chks[i] {
+			if _, ok := validChunks[chks[i][j]]; !ok {
```
Comment (cyriltovena) [inline pkg/storage/iterator.go]: This is exactly where you should filter invalid chunk. But I don't like a map. I prefer that you check a boolean on the chunk. I don't think you need a log also, as this will already be logged by the memchunk.go

Comment (adityacs) [reply pkg/storage/iterator.go]: 👍

File: pkg/storage/iterator.go [hunk 15]
```diff
@@ -403,8 +406,14 @@ func fetchLazyChunks(ctx context.Context, chunks []*chunkenc.LazyChunk) error {
 			}
 			chks, err := fetcher.FetchChunks(ctx, chks, keys)
 			if err != nil {
+				if err.Error() == chunkenc.ErrInvalidChecksum.Error() || strings.Contains(err.Error(), chunkenc.ErrInvalidChecksum.Error()) {
```
Comment (adityacs) [inline pkg/storage/iterator.go]: Just checking `err == chunkenc.ErrInvalidChecksum` is not working. We have to do `err.Error() == chunkenc.ErrInvalidChecksum.Error()`. 

Also, the error might come from cortex from here https://github.com/cortexproject/cortex/blob/02af2474da0cef0cb4076106e03528eed8830166/pkg/chunk/chunk.go#L263. So, we have to check if `stack` contains `invalid chunk checksum` error.

File: pkg/storage/util_test.go [hunk 16]
```diff
@@ -174,7 +228,11 @@ func (m mockChunkStoreClient) PutChunks(ctx context.Context, chunks []chunk.Chun
 func (m mockChunkStoreClient) GetChunks(ctx context.Context, chunks []chunk.Chunk) ([]chunk.Chunk, error) {
 	var res []chunk.Chunk
 	for _, c := range chunks {
-		for _, sc := range m.chunks {
+		for index, sc := range m.chunks {
+			// We have decalared 7 chunks in the mock store. Mark 5th chunk as invalid chunk
+			if len(chunks) == 1 && index == 5 {
+				return nil, chunkenc.ErrInvalidChecksum
+			}
```
Comment (adityacs) [inline pkg/storage/util_test.go]: I know this is not clean coding. However, this was the best and easiest I could think of. I am looking for other better ways to say `invalid chunk` from the loop.

File: pkg/storage/util_test.go [hunk 17]
```diff
@@ -143,10 +146,23 @@ func (m *mockChunkStore) Get(ctx context.Context, userID string, from, through m
...
+		chunks = append(chunks, [][]chunk.Chunk{refs}...)
+		count = count + i
+	}
+	return chunks, fetcher, nil
+}
+
+func (m mockChunkStore) buildFetchers(chunksLength int, count int) (*chunk.Fetcher, []chunk.Chunk) {
+	refs := make([]chunk.Chunk, 0, chunksLength)
+	for i := count; i < chunksLength+count; i++ {
+		r, err := chunk.ParseExternalKey("fake", m.chunks[i].ExternalKey())
```
Comment (adityacs) [inline pkg/storage/util_test.go]: I know this is not clean coding. However, this was the best and easiest I could think of.
Kindly guide me here if there are any other better ways

**Comment by adityacs** [comment]
@cyriltovena Have made the changes and updated tests. Kindly review.

File: pkg/storage/iterator.go (hunk 15 above)
Comment (cyriltovena) [reply pkg/storage/iterator.go]: We should use the err not the stringer, as the stringer function could change.

If it can also come from cortex you can also check that since they are exposing it.

File: pkg/storage/util_test.go (hunk 16 above)
Comment (cyriltovena) [reply pkg/storage/util_test.go]: I thinik it's fine.

Comment (cyriltovena) [reply pkg/storage/util_test.go]: Actually do you need this ? not sure it is executed ? I don't think `GetChunks` is used ?

File: pkg/storage/util_test.go (hunk 17 above)
Comment (cyriltovena) [reply pkg/storage/util_test.go]: I suggest you write a test for only this function `fetchLazyChunks(ctx context.Context, chunks []*chunkenc.LazyChunk)`

The only interface you need to implement then is a fetcher. You can have 2 implementation of fetcher one that returns an error and one that returns the chunk.
Then use that in the test and verify that for invalid checksum errors they are stamped as invalid.


Same goes for `buildHeapIterator(ctx context.Context, chks [][]*chunkenc.LazyChunk, filter logql.LineFilter, direction logproto.Direction, from, through time.Time) (iter.EntryIterator, error)` you could write a test only for this function and verify that lazychunk that are invalid are skipped.

Now your version is also good, it test both at the same time, if you just want to improve it. Then create a seperate mock for your own usage and separate test cases, feel free to copy or create a function for code that could be reuse between your new test function and the current one.

TLDR; the reason why it's ugly is because you're mixin different type of tests in the same table tests.

File: pkg/storage/util_test.go (hunk 16 above)
Comment (adityacs) [reply pkg/storage/util_test.go]: Cortex has this as an interface https://github.com/cortexproject/cortex/blob/master/pkg/chunk/chunk_store_utils.go#L156
Since we are passing mockStorageClient, it will call GetChunks here declared in util_test

File: pkg/storage/iterator.go (hunk 15 above)
Comment (adityacs) [reply pkg/storage/iterator.go]: There is a catch here. Cortex returns errors with different types. Here it is `promql` https://github.com/cortexproject/cortex/blob/master/pkg/chunk/chunk_store_utils.go#L165.

So, comparing `err == chunkenc.ErrInvalidChecksum` is not possible since `chunkenc.ErrInvalidChecksum` is of type `errors.Error` and `err` will be of type `promql.ErrStorage`

File: pkg/storage/util_test.go (hunk 16 above)
Comment (cyriltovena) [reply pkg/storage/util_test.go]: Yep you're right !

File: pkg/storage/util_test.go [hunk 18]
```diff
@@ -143,10 +146,23 @@ func (m *mockChunkStore) Get(ctx context.Context, userID string, from, through m
 }
 
 func (m *mockChunkStore) GetChunkRefs(ctx context.Context, userID string, from, through model.Time, matchers ...*labels.Matcher) ([][]chunk.Chunk, []*chunk.Fetcher, error) {
-	refs := make([]chunk.Chunk, 0, len(m.chunks))
-	// transform real chunks into ref chunks.
-	for _, c := range m.chunks {
-		r, err := chunk.ParseExternalKey("fake", c.ExternalKey())
+	var chunks [][]chunk.Chunk
+	var fetcher []*chunk.Fetcher
+	chunksWithFetcher := []int{4, 1, 2}
```
Comment (cyriltovena) [inline pkg/storage/util_test.go]: This might need a small comment as to why.

File: pkg/storage/iterator.go (hunk 15 above)
Comment (cyriltovena) [reply pkg/storage/iterator.go]: Totally understand I think you should make a function.

`func isInvalidCheckSum(err error) bool`

You could check if it is a `promql.ErrStorage` first, if so unwrap the error, then check it.

Bonus point this means this function can be easily testable and you should send it chunkenc.ErrInvalidChecksum from cortex and from Loki and wrapped with promql.ErrStorage and with a random error.

File: pkg/storage/util_test.go (hunk 18 above)
Comment (adityacs) [reply pkg/storage/util_test.go:151]: Sure. Will add

File: pkg/storage/iterator.go (hunk 15 above)
Comment (adityacs) [reply pkg/storage/iterator.go:409]: Perfect. Will add this

File: pkg/storage/util_test.go (hunk 17 above)
Comment (adityacs) [reply pkg/storage/util_test.go]: Have added separate test for buildHeapIterator. 
I couldn't add for fetchLazyChunks since `FetchChunks` is not an interface.

File: pkg/storage/iterator.go [hunk 19]
```diff
@@ -421,7 +431,25 @@ func fetchLazyChunks(ctx context.Context, chunks []*chunkenc.LazyChunk) error {
...
+	for _, c := range chunks {
+		if c.Chunk.Data != nil {
+			c.IsValid = true
+		}
+	}
+	return nil
+}
+
+func isInvalidChunkError(err error) bool {
+	err = errors.Cause(err)
```
Comment (cyriltovena) [inline pkg/storage/iterator.go:448]: is this errors.Cause needed ? I don't think we use errors.Wrap anywhere

File: pkg/storage/iterator.go [hunk 20]
```diff
@@ -421,7 +431,25 @@ func fetchLazyChunks(ctx context.Context, chunks []*chunkenc.LazyChunk) error {
...
+	if err, ok := err.(promql.ErrStorage); ok {
+		return err.Err == chunk.ErrInvalidChecksum
```
Comment (cyriltovena) [inline pkg/storage/iterator.go:450]: I thought the error could be this one and the Loki one ? shouldn't you test that ?

Comment (adityacs) [reply pkg/storage/iterator.go:450]: Yeah, we can add the Loki one as well. It's just the same error. Will change it

Comment (adityacs) [reply pkg/storage/iterator.go]: @cyriltovena I have made this change. I will rebase on top of this https://github.com/grafana/loki/pull/1914

Comment (cyriltovena) [reply pkg/storage/iterator.go]: > I thought the error could be this one __and__ the Loki one ?

I think it can be both. You also need a small test for that function, this was the point.

Almost there !

Comment (adityacs) [reply pkg/storage/iterator.go]: Should we just use `chunk.ErrInvalidChecksum` from cortex here as well https://github.com/grafana/loki/blob/master/pkg/chunkenc/memchunk.go#L209 ?

If any change on cortex, we should make sure to bring that change to Loki as well otherwise we would break

Comment (adityacs) [reply pkg/storage/iterator.go]: @cyriltovena Added the test

Comment (adityacs) [reply pkg/storage/iterator.go]: Series test is failing. Have to identify some other way to do chunk test. Doing this doesn't work out
https://github.com/grafana/loki/blob/7c2274093f7a76f433a6fd32aad2bd0205e7c1c6/pkg/storage/util_test.go#L208

I will re work on this

Comment (adityacs) [reply pkg/storage/iterator.go]: Changed the Batchsize in `Test_store_GetSeries` test. That works.

WDYT we should?

File: pkg/storage/iterator_test.go [hunk 21]
```diff
@@ -680,3 +807,25 @@ func TestDropLabels(t *testing.T) {
 		})
 	}
 }
+
+func Test_IsInvalidChunkError(t *testing.T) {
+	tests := []struct {
+		name string
+		err  error
```
Comment (cyriltovena) [inline pkg/storage/iterator_test.go:814]: You need to add a case at least where it is not an invalid chunk error.

File: pkg/storage/store_test.go [hunk 22]
```diff
@@ -373,7 +423,7 @@ func Test_store_GetSeries(t *testing.T) {
 				{Labels: mustParseLabels("{foo=\"bar\"}")},
 				{Labels: mustParseLabels("{foo=\"bazz\"}")},
 			},
-			1,
+			2,
```
Comment (cyriltovena) [inline pkg/storage/store_test.go:426]: ? why do you need to change that ?

File: pkg/storage/iterator_test.go (hunk 21 above)
Comment (adityacs) [reply pkg/storage/iterator_test.go:814]: added

File: pkg/storage/store_test.go (hunk 22 above)
Comment (adityacs) [reply pkg/storage/store_test.go]: Not required. Reverted my change. Changed logic here https://github.com/grafana/loki/blob/30a0657e0e7e01617dc14ccd7bb78eae86d4678e/pkg/storage/util_test.go#L209

Comment (adityacs) [reply pkg/storage/store_test.go]: Still this is a hacky thing. However, I just want to keep this because this is kind of complete testing for chunk along with stream

**Comment by adityacs** [comment]
@cyriltovena tests for `isInvalidChunkError` is already added. I will try to add new tests for `fetchLazyChunks` or at least make the existing tests look better.

File: pkg/storage/iterator_test.go [hunk 23]
```diff
@@ -639,6 +643,130 @@ func TestPartitionOverlappingchunks(t *testing.T) {
...
+					Timestamp: from.Add(time.Millisecond),
+					Line:      "2",
+				},
+				{
+					Timestamp: from.Add(2 * time.Millisecond),
+					Line:      "3",
+				},
+			},
+		})
+		secondChunk = newLazyInvalidChunk(logproto.Stream{
```
Comment (cyriltovena) [inline pkg/storage/iterator_test.go:665]:
```suggestion
		invalid = newLazyInvalidChunk(logproto.Stream{
```

File: pkg/storage/util_test.go [hunk 24]
```diff
@@ -77,10 +86,11 @@ func newChunk(stream logproto.Stream) chunk.Chunk {
 	}
 	chk.Close()
 	c := chunk.NewChunk("fake", client.Fingerprint(l), l, chunkenc.NewFacade(chk), from, through)
-	// force the checksum creation
+	// // force the checksum creation
```
Comment (cyriltovena) [inline pkg/storage/util_test.go:89]:
```suggestion
	// force the checksum creation
```

File: pkg/storage/iterator_test.go [hunk 25]
```diff
@@ -639,6 +643,130 @@ func TestPartitionOverlappingchunks(t *testing.T) {
...
+							Timestamp: from.Add(5 * time.Millisecond),
+							Line:      "6",
+						},
+					},
+				},
+			},
+		},
+	} {
+		t.Run(fmt.Sprintf("%d", i), func(t *testing.T) {
+			ctx = user.InjectOrgID(context.Background(), "test-user")
```
Comment (cyriltovena) [inline pkg/storage/iterator_test.go:753]: See I think this test is sufficient. Remove any changes from the other tests in `pkg/storage/store_test.go ` and other changes for that tests, let's keep only this one. And rename the chunk variable to `invalidChunk`.

**Comment by adityacs** [comment]
@cyriltovena I have given one more try to add tests to `fetchLazyChunks`. Kindly review and let me know. If it's not good, I will revert it.

**Comment by adityacs** [comment]
I have removed the new tests. Have retained `IsInvalidChunkError` test
