### PR TITLE
Fixes Iterator boundaries

### LINKED ISSUE #2124: Query `start` is not always inclusive
By design, the `start` query parameter is supposed to be inclusive (a log entry with precisely this timestamp is supposed to be returned by a corresponding query) whereas the `end` parameter is supposed to be exclusive (a log entry with this timestamp is expected to _not_ be returned by the query).

This largely seems to hold true.

However, as part of synthetic workload testing we have found that in rare cases the query `start` parameter did not behave inclusive.

This appeared to be reproducible for the very same query (at least for a small number of repetitions `< 10`).

Example: query with `start=1590396230133000000` (Python w/ requests):

```python
>>> import requests
>>> qparams = {
...   "query": "{streamname=\"looker-1590396228-YPd0cySxXQ-00101-XW7MH-0001\",  <snip>}",
...   "direction": "FORWARD",
...   "regexp": "",
...   "limit": "60000",
...   "start": "1590396230133000000",
...   "end": "1590396230193000000"
... }
>>> data = requests.get("https://<snip>/api/prom/query", params=qparams, verify=False).json()
>>> data['streams'][0]['entries'][0]
{'ts': '2020-05-25T08:43:50.133001Z', 'line': '1590396230133001000:<snip>'}
>>> 
```
The response does *not* contain a log entry with the timestamp `1590396230133000000`.

Next query however shows that this log entry exists:

```python
>>> qparamsfine = {
...   "query": "{streamname=\"looker-1590396228-YPd0cySxXQ-00101-XW7MH-0001\", <snip>}",
...   "direction": "FORWARD",
...   "regexp": "",
...   "limit": "60000",
...   "start": "1590396230132997000",
...   "end": "1590396230133003000"
... }
>>> datafine = requests.get("https://<snip>/api/prom/query", params=qparamsfine, verify=False).json()
>>> datafine['streams'][0]['entries'][3]
{'ts': '2020-05-25T08:43:50.133Z', 'line': '1590396230133000000:<snip>''}
```

Observed with Loki version 1.4.1.

### PR DESCRIPTION
**Pull request by cyriltovena**
The start should be inclusive and the end is supposed to be exclusive.

If start and end are equal, then only one entry can be returned which needs to also be equal to start.

Fixes #2124

Those issues were edge cases where the boundaries of a block or iterator would be equal to the start.

Signed-off-by: Cyril Tovena <cyril.tovena@gmail.com>

### CODE REVIEW

File: pkg/chunkenc/memchunk.go [hunk 1]
```diff
@@ -474,9 +474,10 @@ func (c *MemChunk) Iterator(ctx context.Context, mintT, maxtT time.Time, directi
 	its := make([]iter.EntryIterator, 0, len(c.blocks)+1)
 
 	for _, b := range c.blocks {
-		if maxt > b.mint && b.maxt > mint {
-			its = append(its, b.iterator(ctx, c.readers, filter))
+		if maxt < b.mint || b.maxt < mint {
+			continue
```
Comment (jgehrcke) [inline pkg/chunkenc/memchunk.go:478]: Just thinking out loud, clarifying how this addresses https://github.com/grafana/loki/issues/2124.

With the patch: ignore the current block when none of its entries is within the interval `[mint, maxt]`. Otherwise append it for further processing. Or, in other words: if the current block has any entry within the interval `[mint, maxt]` then append it for further processing.

The special case discussed in https://github.com/grafana/loki/issues/2124 corresponds to `b.maxt == mint` in this code section here, and with the old behavior `maxt > b.mint && b.maxt > mint` a block containing an entry within the interval `[mint, maxt]` was erroneously ignored for further processing.

File: pkg/iter/iterator.go [hunk 2]
```diff
@@ -503,11 +503,18 @@ func (i *timeRangedIterator) Next() bool {
...
 		ok = i.EntryIterator.Next()
+		if !ok {
+			continue
+		}
 		ts = i.EntryIterator.Entry().Timestamp
 	}
-
-	if ok && (i.maxt.Before(ts) || i.maxt.Equal(ts)) { // The maxt is exclusive.
-		ok = false
+	if ok {
```
Comment (owen-d) [inline pkg/iter/iterator.go:511]: couldn't this more simply be expressed as 
```go
	if i.maxt.Before(ts) || i.maxt.Equal(ts) {
		ok = false
	}
```

Comment (cyriltovena) [reply pkg/iter/iterator.go:511]: No this is a very specific path covering the case where both maxt == mint == ts.

Comment (cyriltovena) [reply pkg/iter/iterator.go:511]: The shortcut is required. I tried it but the test wasn't passing.
