### PR TITLE
start and stop modules in correct order

### LINKED ISSUE #105: Ingester crashes on exit
Spotted on one of the ingesters:
```
level=info ts=2018-12-14T09:13:39.379995933Z caller=gokit.go:36 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
level=info ts=2018-12-14T09:13:39.382026879Z caller=loki.go:158 msg=stopping module=store
level=info ts=2018-12-14T09:13:39.382126813Z caller=loki.go:158 msg=stopping module=ingester
level=info ts=2018-12-14T09:13:39.382174645Z caller=lifecycler.go:443 msg="changing ingester state from" old_state=ACTIVE new_state=LEAVING
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xbbfa8c]

goroutine 88517526 [running]:
github.com/grafana/loki/vendor/cloud.google.com/go/storage.(*Writer).open.func1(0xc077ed3860, 0xc15b1dc780, 0xc06cc148c0, 0xc231538280, 0x1, 0x1)
	/go/src/github.com/grafana/loki/vendor/cloud.google.com/go/storage/writer.go:118 +0xfc
created by github.com/grafana/loki/vendor/cloud.google.com/go/storage.(*Writer).open
	/go/src/github.com/grafana/loki/vendor/cloud.google.com/go/storage/writer.go:108 +0x471
```

### PR DESCRIPTION
**Pull request by woodsaj**
When starting up, start all dependencies first then start the target
module.  When stopping, reverse the order to ensure we dont try and
stop a module while there is still something running that needs it.

fixes #105

### CODE REVIEW

File: pkg/loki/loki.go [hunk 1]
```diff
@@ -111,15 +111,20 @@ func (t *Loki) setupAuthMiddleware() {
...
 		}
 	}
+	// lastly, initialize the requested module
+	return t.initModule(m)
+}
+
+func (t *Loki) initModule(m moduleName) error {
+	if _, ok := t.inited[m]; ok {
+		return nil
+	}
```
Comment (tomwilkie) [inline pkg/loki/loki.go]: What purpose does this serve now?  It used to exist to ensure we only stated/stopped modules once, but it that now guaranteed by `getDeps`?

File: pkg/loki/modules.go [hunk 2]
```diff
@@ -178,6 +178,55 @@ func (t *Loki) stopStore() error {
...
 }
 
+// listDeps recursively gets a list of dependencies for a passed moduleName
+func listDeps(m moduleName) []moduleName {
+	deps := modules[m].deps
+	for _, d := range modules[m].deps {
+		deps = append(deps, listDeps(d)...)
+	}
+	return deps
+}
```
Comment (tomwilkie) [inline pkg/loki/modules.go]: As this is only used in `getDeps`, I'd be tempted to move the body in there.

Comment (tomwilkie) [reply pkg/loki/modules.go]: Ahh it recurses.  Missed that.

File: pkg/loki/modules.go [hunk 3]
```diff
@@ -178,6 +178,55 @@ func (t *Loki) stopStore() error {
...
+	deps := listDeps(m)
+
+	// get a unique list of moduleNames, with a flag for whether they have been added to our result
+	uniq := make(map[moduleName]bool)
+	for _, d := range deps {
+		uniq[d] = false
+	}
+
+	result := make([]moduleName, len(uniq))
+	numAdded := 0
```
Comment (tomwilkie) [inline pkg/loki/modules.go]: For readability, I'd probably have done without the `numAdded` var, and gone with `for len(result) < len(uniq)` and `result = append(result, d)`.

Comment (tomwilkie) [reply pkg/loki/modules.go]: (Super nit picky, sorry)

File: pkg/loki/modules.go [hunk 4]
```diff
@@ -178,6 +178,55 @@ func (t *Loki) stopStore() error {
...
+
+	// keep looping through all modules until they have all been added to the result.
+	for numAdded < len(uniq) {
+		for d, s := range uniq {
```
Comment (tomwilkie) [inline pkg/loki/modules.go]: Nit: I'm not keen on single letter variables (except the obvious i, j etc).  I think this would be more readable is it were `for module, added := range modules`.

File: pkg/loki/modules.go [hunk 5]
```diff
@@ -178,6 +178,55 @@ func (t *Loki) stopStore() error {
...
+	}
+	return deps
+}
+
+// getDeps gets a list of all dependencies ordered so that items are always after any of their dependencies.
+func getDeps(m moduleName) []moduleName {
+	deps := listDeps(m)
+
+	// get a unique list of moduleNames, with a flag for whether they have been added to our result
+	uniq := make(map[moduleName]bool)
```
Comment (tomwilkie) [inline pkg/loki/modules.go]: Throughout the Loki codebase I've preferred `map[moduleName]bool{}` over make, unless we know the size.  Super nit picky, sorry.

File: pkg/loki/modules.go [hunk 6]
```diff
@@ -178,6 +178,55 @@ func (t *Loki) stopStore() error {
...
+func listDeps(m moduleName) []moduleName {
+	deps := modules[m].deps
+	for _, d := range modules[m].deps {
+		deps = append(deps, listDeps(d)...)
+	}
+	return deps
+}
+
+// getDeps gets a list of all dependencies ordered so that items are always after any of their dependencies.
+func getDeps(m moduleName) []moduleName {
```
Comment (tomwilkie) [inline pkg/loki/modules.go]: Naming: orderedDeps might be more descriptive?

File: pkg/loki/modules.go [hunk 7]
```diff
@@ -178,6 +178,55 @@ func (t *Loki) stopStore() error {
...
+	uniq := make(map[moduleName]bool)
+	for _, d := range deps {
+		uniq[d] = false
+	}
+
+	result := make([]moduleName, len(uniq))
+	numAdded := 0
+
+	// keep looping through all modules until they have all been added to the result.
+	for numAdded < len(uniq) {
```
[the remark this answers is not in the document]
Comment (woodsaj) [reply pkg/loki/modules.go]: This loop will never enter an infinite loop.  For that to happen, there would need to be a circular dependency.   But, if that is true, then the recursive listDeps() would encounter a fatal stack overflow error.

File: pkg/loki/loki.go [hunk 8]
```diff
@@ -145,21 +146,20 @@ func (t *Loki) Stop() error {
...
+func (t *Loki) stopModule(m moduleName) {
 	level.Info(util.Logger).Log("msg", "stopping", "module", m)
-	if err := modules[m].stop(t); err != nil {
-		level.Error(util.Logger).Log("msg", "error stopping", "module", m, "err", err)
+	if modules[m].stop != nil {
+		if err := modules[m].stop(t); err != nil {
+			level.Error(util.Logger).Log("msg", "error stopping", "module", m, "err", err)
+		}
 	}
+	delete(t.inited, m)
```
Comment (tomwilkie) [inline pkg/loki/loki.go]: Is this needed still?

File: pkg/loki/modules.go [hunk 9]
```diff
@@ -178,6 +178,52 @@ func (t *Loki) stopStore() error {
...
+func orderedDeps(m moduleName) []moduleName {
+	deps := listDeps(m)
+
+	// get a unique list of moduleNames, with a flag for whether they have been added to our result
+	uniq := map[moduleName]bool{}
+	for _, dep := range deps {
+		uniq[dep] = false
+	}
+
+	result := make([]moduleName, 0)
```
Comment (tomwilkie) [inline pkg/loki/modules.go]: Lets do `[]moduleName{}` or `make([]moduleName, 0, len(uniq)`.  Anything but this!

File: pkg/loki/loki.go (hunk 8 above)
Comment (woodsaj) [reply pkg/loki/loki.go]: I guess the `inited` field can be removed completely from the Loki struct

**Comment by tomwilkie** [comment]
LGTM with 2 nits.
