### PR TITLE
fix: handle `INIT` from frontend in running scheduler which is not in `shouldRun` state

### LINKED ISSUE #19528: queries are not processed if frontend connects to scheduler too early
**Describe the bug**
We observe that quite often when the scheduler restarts, querying stop workings.
We run Loki in microservice mode with `use_scheduler_ring = true` on Nomad.

After putting a lot of log statements into Loki we observed that the `frontend` reconnects to the scheduler before the scheduler [`shouldRun` state is set to `true`](https://github.com/grafana/loki/blob/b95bfabd422a9b458dbbbde3eda33a95ed768a3a/pkg/scheduler/scheduler.go#L650), which is initially `false` as we use the `use_scheduler_ring = true`. For some timing reason (memberlist state?)  the frontend reconnects before that which then causes the [scheduler skip the response to frontends `INIT` ](https://github.com/grafana/loki/blob/b95bfabd422a9b458dbbbde3eda33a95ed768a3a/pkg/scheduler/scheduler.go#L248).
Thus the frontend starts piling up in progress query requests until they timeout.

As I haven't any issue yet and this happens quite often, there might be something wonky in our config. Still I think this can be considered a bug as system locks in a strange unresponsive way.

**To Reproduce**
I'm still facing issue to reproduce this in a deterministic way as I've not understand the full memberlist/scheduler ring/frontend/scheduler connect protocol. Happy to get some pointers here

**Expected behavior**
Scheduler restart, frontend reconnects, frontends continues scheduling queries
**Environment:**
 - Loki 3.5.7 (also experienced earlier), microservice mode, memberlist, use_scheduler_ring
 - Infrastructure: Nomad, Consul, Vault
 - Deployment tool: Nomad Job files :)

### PR DESCRIPTION
**Pull request by mxab**
**What this PR does / why we need it**:

We expirience the situation where the scheduler is not yet in a "shouldRun" state but receives an init message from the frontend.
[In this case the scheduler](https://github.com/grafana/loki/blob/main/pkg/scheduler/scheduler.go#L249)  will not reply with an `OK` but rather will just [wait for the next message](https://github.com/grafana/loki/blob/main/pkg/scheduler/scheduler.go#L258)

This means the frontend worker is then [blocked as it waits for any kind of reply](https://github.com/grafana/loki/blob/main/pkg/lokifrontend/frontend/v2/frontend_scheduler_worker.go#L265) from the scheduler.
Therefore the frontend worker connects to the scheduler but does not forward incoming queries

**Which issue(s) this PR fixes**:

Fixes #19528

This PR mitigates this issue by sending as the scheduler now sends an `ERROR` in case it's RUNNING but shouldRun is still false

This PR is the "smaller" version of this [PR](https://github.com/grafana/loki/pull/19540) as I hope its easier to review while the other one also add an additional timeout on the frontend side

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

---

> [!NOTE]
> **Medium Risk**
> Medium risk because it changes the scheduler/frontend handshake behavior in `FrontendLoop`, which can affect query routing and reconnect behavior during ring transitions, though the change is small and covered by a new test.
> 
> **Overview**
> Fixes a frontend connection stall by **explicitly responding to `INIT` when the scheduler service is `Running` but `shouldRun` is still false** (eg, not yet in the ring replication set).
> 
> Instead of silently proceeding without an `INIT` response, the scheduler now logs and sends `schedulerpb.ERROR` so the frontend can immediately retry a different scheduler. Adds a focused unit test and enhances the frontend loop mock to support scripted `Recv()` behavior.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 8320a291c8c49b5a9e69be1623b6b0e54a9c3368. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -250,6 +250,10 @@ func (s *Scheduler) FrontendLoop(frontend schedulerpb.SchedulerForFrontend_Front
 		if err := frontend.Send(&schedulerpb.SchedulerToFrontend{Status: schedulerpb.OK}); err != nil {
 			return err
 		}
+	} else if s.State() == services.Running && !s.shouldRun.Load() {
```
Comment (spiridonov) [inline pkg/scheduler/scheduler.go]: Lets make it one if for `if s.State() == services.Running {` and another if-else inside that for `if s.shouldRun.Load() { } else {}` to avoid double reading `shouldRun`.

File: pkg/scheduler/scheduler_test.go [hunk 2]
```diff
@@ -63,6 +65,56 @@ func TestScheduler_setRunState(t *testing.T) {
...
+
+	// not_running, shouldRun == false
+	assert.False(t, s.shouldRun.Load())
+
+	err := s.FrontendLoop(mock)
+	assert.NoError(t, err)
+
+	// not_running -> running, shouldRun == true
+	// to simulate last "setRunState(true)" happening after FrontendLoop started
+	s.setRunState(true)
```
Comment (spiridonov) [inline pkg/scheduler/scheduler_test.go]: Correct me if I'm wrong. This call does not effectively change anything in the test results or in the `mock` since `FrontendLoop` func has already returned by that moment, right?

**Review by spiridonov — CHANGES_REQUESTED** [review]
Thank you for tackling that bug @mxab !

File: pkg/scheduler/scheduler.go (hunk 1 above)
Comment (mxab) [reply pkg/scheduler/scheduler.go]: done

File: pkg/scheduler/scheduler_test.go (hunk 2 above)
Comment (mxab) [reply pkg/scheduler/scheduler_test.go]: Ok If i remember it correctly my intention was to "simulate" the rest of the behaviour in case something happens in the future.
But yes doesn't make to much sense. I removed the setRunState(true) and the assertion

**Review by spiridonov — APPROVED** [review]

**Comment by spiridonov** [comment]
@mxab thank you!

**Comment by mxab** [comment]
Great to get this merged. Btw I previously opened a more complex pr that introduced a general failsafe from the frontend side. I assumed it was to big and therefore ignored.

Would you mind sharing your opinion on that one as well?

@spiridonov

https://github.com/grafana/loki/pull/19540
