### PR TITLE
fluentbit: JSON encoding: avoid base64 encoding of []byte inside other slices

### LINKED ISSUE #1889: fluent-bit output plugin accidentally encodes all strings values inside arrays in base64
**Describe the bug**

Any log object with strings inside arrays (directly or indirectly) gets inserted int Loki with these strings base64-encoded, e.g. (abbreviated):
```
{"Object":{"metadata":{"taints":[{"effect":"Tm9TY2hlZHVsZQ==","key":"bm9kZS1yb2xlLmt1YmVybmV0ZXMuaW8vbWFzdGVy"}]}}}
```

**To Reproduce**
1. Started Loki (any version)
2. Started `fluent-bit` from `master`
3. Published a log message with a string inside a `[]`
4. Queried this log message, got base64-encoding.

**Expected behavior**

Strings inside arrays don't get base64-encoded.

### PR DESCRIPTION
**Pull request by dottedmag**
**What this PR does / why we need it**:

Without this fix any strings inside arrays (directly or indirectly) end up being
base64-encoded.

**Which issue(s) this PR fixes**:
Fixes #1889

**Special notes for your reviewer**:

**Checklist**
- [X] Tests updated
- [X] Documentation added

### CODE REVIEW

**Comment by cyriltovena** [comment]
Nice ! Looks good ! Are you able to sign the CLA ?

File: cmd/fluent-bit/loki.go [hunk 1]
```diff
@@ -68,6 +68,26 @@ func (l *loki) sendRecord(r map[interface{}]interface{}, ts time.Time) error {
 	return l.client.Handle(lbs, ts, line)
 }
 
+// prevent base64-encoding []byte values (default json.Encoder rule) by
+// converting them to strings
+
```
Comment (cyriltovena) [inline cmd/fluent-bit/loki.go:73]: I would remove that empty space and add the function name instead such as `toStringSlice prevent....`

Comment (dottedmag) [reply cmd/fluent-bit/loki.go:73]: This comment is related to the next two functions, so I kept it separate.

**Comment by dottedmag** [comment]
@cyriltovena Sure, let me pass it by the legal dept.

**Comment by dottedmag** [comment]
@cyriltovena All done.
