### PR TITLE
Fix Loki Chunks Dashboard

### LINKED ISSUE #1045: "Loki / Chunks" dashboard uses undefined metrics
The "Loki / Chunks" dashboard in the Loki mixin [here](https://github.com/grafana/loki/blob/7794d15b6ac7e7553710851f2e26d25e9662c061/production/loki-mixin/dashboards.libsonnet#L84) references the following metrics that are not defined in Loki:

- `loki_ingester_memory_chunks` 
- `loki_ingester_memory_series`
- `loki_ingester_chunk_utilization`
- `loki_ingester_chunk_length`
- `loki_chunk_store_index_entries_per_chunk`
- `loki_ingester_flush_queue_length` 

It is not clear to me if these metrics need to be defined or if the mixin needs to be updated to use the appropriate currently existing metrics.

### LINKED ISSUE #1105: Loki defines metrics that it never updates
Referring to the [list of metrics](https://github.com/grafana/loki/blob/master/docs/operations/observability.md) that Loki exposes, it seems that a subset of them are defined but never incremented. One example of this is `loki_ingester_chunks_flushed_total`, although there may be others.

### PR DESCRIPTION
**Pull request by joe-elliott**
**What this PR does / why we need it**:
This PR cleans up the Loki Chunks dashboard either by renaming incorrectly named series or adding needed metrics.

- Added new metrics
  - loki_ingester_memory_chunks
  - loki_ingester_memory_streams (added instead of loki_ingester_memory_series)
  - loki_ingester_chunk_utilization
  - loki_ingester_chunk_compression_ratio
- The following metrics were already being published with a different name.  Fixed in the dashboard:
  - cortex_chunk_store_index_entries_per_chunk
  - cortex_ingester_flush_queue_length
  - loki_ingester_chunk_entries

**Which issue(s) this PR fixes**:
Fixes #1045
Fixes #1105

**Special notes for your reviewer**:
I'm concerned about the method used to calculate `loki_ingester_chunk_utilization` and would like a close review.  In `gzip.go` I am calculating the total percentage of blocks used in the chunk and returning that as utilization.  I think a more interesting metric would be %age of block size used, but this would require uncompressing the log entries or storing on the block the uncompressed size when it was cut.

**Checklist**
- [x] Documentation added
- [ ] Tests updated

### CODE REVIEW

File: pkg/ingester/instance.go [hunk 1]
```diff
@@ -89,10 +93,16 @@ func (i *instance) consumeChunk(ctx context.Context, labels []client.LabelAdapte
...
 		i.streamsCreatedTotal.Inc()
+		memoryStreams.Inc()
 		i.addTailersToNewStream(stream)
 	}
 
-	return stream.consumeChunk(ctx, chunk)
+	err := stream.consumeChunk(ctx, chunk)
+	if err != nil {
+		memoryChunks.Inc()
+	}
```
Comment (rfratto) [inline pkg/ingester/instance.go]: Is this right? i.e., only increase the number of memory chunks if there was an error?

Comment (joe-elliott) [reply pkg/ingester/instance.go]: Nope.  Good catch.  Fixed.

File: docs/operations/observability.md [hunk 2]
```diff
@@ -24,22 +24,26 @@ The Loki Distributors expose the following metrics:
...
+| `cortex_ingester_flush_queue_length`         | Gauge       | The total number of series pending in the flush queue.                                      |
+| `cortex_chunk_store_index_entries_per_chunk` | Histogram   | Number of index entries written to storage per chunk.                                       |
+| `loki_ingester_memory_chunks`                | Gauge       | The total number of chunks in memory.                                                       |
+| `loki_ingester_memory_streams`               | Gauge       | The total number of streams in memory.                                                      |
+| `loki_ingester_chunk_age_seconds`            | Histogram   | Distribution of chunk ages when flushed.                                                    |
+| `loki_ingester_chunk_encode_time_seconds`    | Histogram   | Distribution of chunk encode times.                                                         |
+| `loki_ingester_chunk_entries`                | Histogram   | Distribution of entries per-chunk when flushed.                                             |
```
Comment (slim-bean) [inline docs/operations/observability.md]: is this the length of the entries?

Comment (slim-bean) [reply docs/operations/observability.md]: i'm not entirely sure what an "entry" is here

Comment (slim-bean) [reply docs/operations/observability.md]: ok it looks like entries = log lines, wonder if we should make that clearer in the description

File: pkg/chunkenc/gzip.go [hunk 3]
```diff
@@ -313,6 +313,13 @@ func (c *MemChunk) SpaceFor(*logproto.Entry) bool {
 	return len(c.blocks) < blocksPerChunk
 }
 
+// Utilization implements Chunk.
+func (c *MemChunk) Utilization() float64 {
+	// Here we're just reporting the block utilization which is not super exciting.  It would be more interesting to see
+	// for each block what %age of c.blocksize was used, but that would require uncompressing the data in every block
+	return float64(len(c.blocks)) / float64(blocksPerChunk)
```
Comment (slim-bean) [inline pkg/chunkenc/gzip.go]: you could do it as an average maybe? keep a sum of all the uncompressed bytes and then divide by the (# of blocks * block size)?

File: docs/operations/observability.md (hunk 2 above)
Comment (joe-elliott) [reply docs/operations/observability.md]: Agreed.  Updated the description to include the word "lines" instead of "entries" to ease confusion.

File: pkg/chunkenc/gzip.go (hunk 3 above)
Comment (joe-elliott) [reply pkg/chunkenc/gzip.go]: I think I'm just generally concerned about adding the additional state of "uncompressed size in bytes" to each block.  If you think that knowing the difference between max block size and utilized block size is valuable I will add it.

Comment (joe-elliott) [reply pkg/chunkenc/gzip.go]: Changing the definition of utilization to be the total number of uncompressed bytes in the chunk divided by the total number of possible uncompressed bytes in the chunk.

**Comment by joe-elliott** [comment]
@rfratto @slim-bean 

This should be ready to go.  Utilization changes complete.  Compression ratio metric added.

File: docs/operations/observability.md [hunk 4]
```diff
@@ -24,22 +24,26 @@ The Loki Distributors expose the following metrics:
...
+| `loki_ingester_memory_chunks`                | Gauge       | The total number of chunks in memory.                                                       |
+| `loki_ingester_memory_streams`               | Gauge       | The total number of streams in memory.                                                      |
+| `loki_ingester_chunk_age_seconds`            | Histogram   | Distribution of chunk ages when flushed.                                                    |
+| `loki_ingester_chunk_encode_time_seconds`    | Histogram   | Distribution of chunk encode times.                                                         |
+| `loki_ingester_chunk_entries`                | Histogram   | Distribution of lines per-chunk when flushed.                                               |
+| `loki_ingester_chunk_size_bytes`             | Histogram   | Distribution of chunk sizes when flushed.                                                   |
+| `loki_ingester_chunk_utilization`            | Histogram   | Distribution of chunk utilization when flushed.                                             |
```
Comment (slim-bean) [inline docs/operations/observability.md]:
```suggestion
| `loki_ingester_chunk_utilization`            | Histogram   | Distribution of chunk utilization (filled uncompressed bytes vs maximum uncompressed bytes) when flushed.                                             |
```

**Comment by slim-bean** [comment]
Last question: 

Do we want to also observe the uncompressed size per tenant?

I'm not sure if we would really care about this much?  It might be interesting to know on a per-tennant basis what the encryption looks like but i'm not sure this is interesting enough to warrant a growing per-tennant metric.

**Comment by joe-elliott** [comment]
Uncompressed size per tenant should basically be captured in `loki_distributor_bytes_received_total`.  Do we feel like there is something to be gained from metricing it when flushing to blocks?  I suppose differences in the values could reveal issues?

**Comment by slim-bean** [comment]
Yeah I agree we wouldn't want to do a per tenant histogram, and hadn't considered using the received_bytes_total metric. 

Ok, lets just leave things the way they are now and get this merged!

**Comment by CyberoxiDevops** [comment]
Hi, any updates about loki_ingester_chunk_utilization?
