### PR TITLE
[Promtail] resolve issue with promtail not scraping target if only path changed in a simpler way that dont need mutex to sync threads

### LINKED ISSUE #4581: Promtail may fail to scrape pods if the only label that changes is the filename
**Describe the bug**

The code which decides if a file target is a duplicate to an existing target compares all the labels __except__ the filename label (which at this point in the code is `__path__` pulled from the scrape_config).

This means if the *only* label that changes is the filename label when a pod is restarted, it will fail to be scraped because the code will consider it a duplicate of an existing target and ignore it.

A workaround would be to add any label which changes when the pod is restarted. 

Add something like this to each job in your scrape config
```
- action: replace
   source_labels:
     - __meta_kubernetes_pod_uid
   target_label: pod_uid
```

Reminder, this is a workaround until a proper fix is put in place in Promtail.

Note: 

This is likely largely not seen previously because a lot of the example scrape configs we've provided have always included a section which maps all the pod labels to Loki labels, which includes things like `pod_template_hash` and `controller_revision_hash` that will always change when pods are restarted.  

Our more recent guidance suggests not mapping all pod labels to Loki as they often have little value for querying and result in wasted index space, as a result we have since discovered this issue on more recently provided scrape configs such as provided with the Grafana Agent.

### PR DESCRIPTION
**Pull request by rsteneteg**
resolve issue with promtail not scraping target if only path changed in a simpler way that dont need mutex to sync threads

Signed-off-by: Roger Steneteg <rsteneteg@ea.com>

**What this PR does / why we need it**:
Resolves an issue in a better way, that don't require sharing variables between theads that would require a mutex to synchronize goroutines.

**Which issue(s) this PR fixes**:
Fixes #4581 #4460

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

File: clients/pkg/promtail/targets/file/filetargetmanager.go [hunk 1]
```diff
@@ -243,16 +243,12 @@ func (s *targetSyncer) sync(groups []*targetgroup.Group) {
...
 			targets[key] = struct{}{}
-			if tgt, ok := s.targets[key]; ok {
-				if tgt.UpdatePath(string(path)) {
-					level.Debug(s.log).Log("msg", "updating target, path changed", "labels", labels.String())
-				} else {
-					dropped = append(dropped, target.NewDroppedTarget("ignoring target, already exists", discoveredLabels))
-					level.Debug(s.log).Log("msg", "ignoring target, already exists", "labels", labels.String())
-					s.metrics.failedTargets.WithLabelValues("exists").Inc()
-				}
+			if _, ok := s.targets[key]; ok {
```
Comment (kavirajk) [inline clients/pkg/promtail/targets/file/filetargetmanager.go:248]: Not an promtail expert. Leave it @slim-bean for the final approval. 

I still do think we need some tests to lock this behaviour!

Comment (cyriltovena) [reply clients/pkg/promtail/targets/file/filetargetmanager.go:248]: Yeah that be great.

**Comment by cyriltovena** [comment]
@slim-bean should we merge ?

**Review by slim-bean — APPROVED** [review]
LGTM!

**Review by rfratto — COMMENTED** [review]
Just had a chance to look at this. Looks great, thank you!

**Comment by Mario-Hofstaetter** [comment]
@rsteneteg may I ask if this PR is going to fix #3698 also? I fear it does not.
I could test on the weekend with a `main` build whether this changes the behavior.

**Comment by rsteneteg** [comment]
@Mario-Hofstaetter it looks like this change would also fix #3698, since the path variable is used within the key it would no longer be seen as a duplicate and ignored.
