### PR TITLE
Run `loki -version` without needing a config defined

### LINKED ISSUE #6770: loki -version should work without config file
**Describe the bug**
`loki -version` currently requires a configuration file to be passed or found at default location. This is unexpected, since it does not use the config file and causes troubles when deployments first check version to then install proper configuration file

**To Reproduce**
1. Make sure no config file is at the default location.
2. `loki -version`

**Expected behavior**
Print version information.

**Screenshots, Promtail config, or terminal output**
```
# /usr/local/bin/loki  -version
failed parsing config: config.yaml,config/config.yaml does not exist, set config.file for custom config path
```

### PR DESCRIPTION
**Pull request by gyanesh-m**
**What this PR does / why we need it**:
It doesn't throw error during version check if config file isn't present.

**Which issue(s) this PR fixes**:
Fixes #6770 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

File: cmd/loki/main.go [hunk 1]
```diff
@@ -24,14 +24,14 @@ import (
 func main() {
 	var config loki.ConfigWrapper
 
+	if config.PrintVersion || len(os.Args[1:]) == 1 && os.Args[1] == "version" {
```
Comment (dannykopping) [inline cmd/loki/main.go:27]:
```suggestion
	if len(os.Args) >= 1 && os.Args[1] == "-version" {
```

`config.PrintVersion` will never be set, and the arg should be `-version`

**Review by dannykopping — CHANGES_REQUESTED** [review]

**Review by dannykopping — APPROVED** [review]
Thanks for your contribution @gyanesh-m :+1:
