### PR TITLE
fix: allow comparison against zero bytes

### LINKED ISSUE #14993: Unexpected zero value comparison operation error: `binary literal has no digits`
**Describe the bug**
Every comparison operation on a "duration" or "bytes" field requires a unit, except when the field is "bytes" and the value is 0.

**To Reproduce**
1. Run this query:  ```{service_name=`loki/loki`} | json | logfmt | drop __error__, __error_details__ | throughput>=0B```
2. Cry in the tub
3. (workaround) delete the unit

**Expected behavior**
Users might be using variables within grafana, or frameworks like scenes to build dynamic dashboards, as such, one would expect the same query to run with different numeric inputs without needing to adjust the units for specific cases.
So I would expect  ```{service_name=`loki/loki`} | json | logfmt | drop __error__, __error_details__ | throughput>=0B```, and ```{service_name=`loki/loki`} | json | logfmt | drop __error__, __error_details__ | throughput>=1B```, to both be valid logQL, however the former throws the  `binary literal has no digits` error.

I understand that the `throughput>=0B` is not a good filter, and the workaround is to drop the unit or change the filter to `throughput!=""`, but imagine an application like Explore logs tries to create some UI for helping users write comparison operation filters, for every (duration/bytes) comparison a unit is required, and users might be fiddling with values in the UI, and instead of removing a filter, they change the value to 0 temporarily. Currently I'd need to either code in a unit-less filter for the 0 case, or remove the filter entirely, both of which could confuse the end-user. Also since I'm using a variable value to concatenate the users selection for unit with the value in the logQL output, removing the unit from the value will reset their unit selection, upsetting the users expectation that whatever unit they entered in the filter will persist in the future when they make edits

TL;DR: This query would run without error:
```{service_name=`loki/loki`} | json | logfmt | drop __error__, __error_details__ | throughput>=0B | throughput <10GB```

Not a high priority, but hopefully a quick fix.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

### PR DESCRIPTION
**Pull request by trevorwhitney**
**What this PR does / why we need it**:

Allows query comparisons against zero bytes, ie `{foo="bar"} | logfmt | bytes < 0b`.

**Which issue(s) this PR fixes**:
Fixes #14993

**Special notes for your reviewer**:

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [x] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [x] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

File: pkg/logql/syntax/query_scanner.go [hunk 1]
```diff
@@ -409,8 +409,10 @@ func (s *Scanner) scanNumber(ch rune, seenDot bool) (rune, rune) {
 				ch = s.next()
 				base, prefix = 8, 'o'
 			case 'b':
-				ch = s.next()
-				base, prefix = 2, 'b'
+				if s.Peek() == '1' || s.Peek() == '0' {
```
Comment (grobinson-grafana) [inline pkg/logql/syntax/query_scanner.go:412]: To avoid doing the work of `next()` twice what about:
```suggestion
				if peek := s.Peek(); peek == '0' || peek == '1' {
```

Comment (trevorwhitney) [reply pkg/logql/syntax/query_scanner.go]: I like it 👍

**Review by cyriltovena — APPROVED** [review]
LGTM
