### PR TITLE
fluentd: Fix bug that caused lines to be dropped when containing non utf-8 characters

### LINKED ISSUE #5099: When log line from fluentd contains non-UTF-8 characters, the whole log line is dropped in Loki
**Describe the bug**
A customer is running into an issue where a Cisco device sends a log line that contains non UTF-8 characters into fluentd, when that is forwarded to Loki (using the fluentd-loki-output plugin), Loki drops the whole log line

**Debugging steps**
Customer debugging and troubleshooting involved the following steps:

**1.** 
```
After activating logforwarding to Loki fluentd regularly (every minute) logs following error:
Fluentd Error "invalid byte sequence in UTF-8"
2021-12-08 07:43:51 +0100 [warn]: #0 got unrecoverable error in primary and no secondary error_class=ArgumentError error="invalid byte sequence in UTF-8"
2021-12-08 07:43:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-grafana-loki-1.2.16/lib/fluent/plugin/out_loki.rb:282:in `gsub'
2021-12-08 07:43:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-grafana-loki-1.2.16/lib/fluent/plugin/out_loki.rb:282:in `block in record_to_line'
2021-12-08 07:43:51 +0100 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-grafana-loki-1.2.16/lib/fluent/plugin/out_loki.rb:280:in `each'
```

**2**
They came back with specific excerpts of the log lines that were causing trouble
```
Excerpt of fluentd chunk output:
<92>×^@a±<98>¨
È×<8a>§Unified Audit[277897]: LENGTH: '199' TYPE:"9" DBID:"263689621" SESID:"879601414" CLIENTID:"'©#004A " ENTRYID:"0" STMTID:"605" DBUSER:"SYS" CURUSER:"" ACTION:"47" RETCODE:"0" SCHEMA:"" OBJNAME:"" PDB_GUID:"BDEB1E2377C11BD2E0537AA2B60A85E6" ©timestampª1639028904\(ö£tag¢na

Inside Graylog (using another another output plugin, not fluentd loki output plugin, to transfer identical) we see following message:
Unified Audit[277897]: LENGTH: '199' TYPE:"9" DBID:"263689621" SESID:"879601414" CLIENTID:"'�#004A " ENTRYID:"0" STMTID:"605" DBUSER:"SYS" CURUSER:"" ACTION:"47" RETCODE:"0" SCHEMA:"" OBJNAME:"" PDB_GUID:"BBED1E2377E11BD2E0537AA2B60A85E6"
 ```

**3**
Suggested the customer to use [fluentd plugin to force valid encoding](https://github.com/okkez/fluent-plugin-force-encoding/) but they weren't comfortable with using it in production due to the last commit being over a year ago and not looking like an officially supported plugin which may cause future fluentd migration issues.

**4**
Finally, customer tried the following different configurations with fluent-plugin-record-modifier to address the problem:

```
<filter **>
  @type record_modifier
  char_encoding utf-8
  char_encoding ASCII-8BIT:utf-8
</filter>

<filter **>
  @type record_modifier
  char_encoding utf-8
  char_encoding ASCII-8BIT:utf-8
</filter>

<filter **>
  @type record_modifier
  char_encoding ASCII-8BIT:utf-8
</filter>
```

But none of these worked always returning the same error messages regarding invalid chars by loki output plugin: „got unrecoverable error in primary and no secondary error_class=ArgumentError error="invalid byte sequence in UTF-8"“

Customer notes that the [official fluent documention](https://docs.fluentd.org/v/0.12/quickstart/faq#i-got-enconding-error-inside-plugin.-how-to-fix-it) states:

> Fluentd and almost [all] plugins treat the logs as a ASCII-8BIT by default but some libraries assume the log encoding is UTF-8. This is why this error happens.“

Could this be a loki-output-plugin issue/

**Expected behavior**
If any non UTF-8 characters are seen, they should be replaced and the log line should be saved rather then having the whole log line get dropped.

**Environment:**
- Single binary deployment of Loki (during POC)
- Fluentd -> fluentd-loki-output -> Loki

### PR DESCRIPTION
**Pull request by chaudum**
**What this PR does / why we need it**:

When a log line in hash format contains non UTF-8 characters fluentd
would drop the complete line because it failed to convert the line in
key-value format.

By forcing UTF-8 encoding and replacing non UTF-8 characters with empty
strings the log line will not be dropped but only contain the valid
UTF-8 characters.

**Which issue(s) this PR fixes**:

Fixes #5099

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [x] Tests updated
- [x] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Comment by chaudum** [comment]
@cyriltovena is bumping the fluentd plugin version here the right thing to do? https://github.com/grafana/loki/pull/5107/commits/7fd4c40df21ab6cf72942f599a0dbd9f8e63d087

File: clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb [hunk 1]
```diff
@@ -278,6 +278,8 @@ def record_to_line(record)
           when :key_value
             formatted_labels = []
             record.each do |k, v|
+              # Remove non UTF-8 characters by force-encoding the string and replacing said chars with empty string
+              v = v.encode('utf-8', invalid: :replace, replace: '')
```
Comment (cyriltovena) [inline clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb:282]: should we replace with another special character may be ? Not sure if we can empty string will not tell users there was an issue there ? WDYT ?

File: clients/cmd/fluentd/fluent-plugin-grafana-loki.gemspec [hunk 2]
```diff
@@ -4,7 +4,7 @@ $LOAD_PATH.push File.expand_path('lib', __dir__)
 
 Gem::Specification.new do |spec|
   spec.name    = 'fluent-plugin-grafana-loki'
-  spec.version = '1.2.16'
+  spec.version = '1.2.17'
```
Comment (cyriltovena) [inline clients/cmd/fluentd/fluent-plugin-grafana-loki.gemspec:7]: 👍  this will do !

File: clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb (hunk 1 above)
Comment (cyriltovena) [reply clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb:282]: would � work ?

Comment (chaudum) [reply clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb:282]: You can let Ruby decide how to replace the invalid characters, like so:

`              v = v.encode('utf-8', invalid: :replace)`

File: clients/cmd/fluentd/spec/gems/fluent/plugin/loki_output_spec.rb [hunk 3]
```diff
@@ -122,7 +139,7 @@
     expect(body[:streams][0]['stream'].empty?).to eq true
     expect(body[:streams][0]['values'].count).to eq 1
     expect(body[:streams][0]['values'][0][0]).to eq '1546270458000000000'
-    expect(body[:streams][0]['values'][0][1]).to eq 'message="' + content[0] + '" stream="stdout"'
+    expect(body[:streams][0]['values'][0][1]).to eq 'message="' + content[0] + '" stream=stdout'
```
Comment (chaudum) [inline clients/cmd/fluentd/spec/gems/fluent/plugin/loki_output_spec.rb:142]: This test was failing since c298514793ddf49ec8d15972b35cdae5f225b5d2

**Review by cyriltovena — APPROVED** [review]
LGTM

**Comment by cyriltovena** [comment]
Thank you so much @chaudum
