### PR TITLE
Enhance logging on timeout tailing logs on canary

### LINKED ISSUE #4821: Loki canary missing error context when log format mismatch
**Describe the bug**
When Loki canary try to read logs from websocket, and if the logs are not in proper format (sent by promtail) then currently it gives strange error (without context or proper wrapping) that is hard to debug what is the cause of the error.

```
error reading websocket, will retry in 10 seconds: read tcp 10.0.36.157:59798->18.224.9.71:443: i/o timeout
```

** Proposal **
Add error wrapping!

### PR DESCRIPTION
**Pull request by salvacorts**
**What this PR does / why we need it**:
When the Loki canary opens a WebSockets stream to tail logs, it sets a deadline. This deadline can expire if the ingester doesn't get a new log for the query within that deadline. The problem is that the error message logged on the canary is misleading as it states:
```
error reading websocket [...]
``` 

This is not true as there was no error reading from WebSockets but rather a timeout error. In this PR, we change the error handling to print a timeout message if the tailing times out, or the `error reading websocket [...]` message if the operation does not timeout but there is any other error.

**Which issue(s) this PR fixes**:
Fixes #4821

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

File: pkg/canary/reader/reader.go [hunk 1]
```diff
@@ -349,7 +349,16 @@ func (r *Reader) run() {
...
 		err := unmarshal.ReadTailResponseJSON(tailResponse, r.conn)
 		if err != nil {
-			fmt.Fprintf(r.w, "error reading websocket, will retry in 10 seconds: %s\n", err)
+			var reason string
+			netErr, ok := err.(net.Error)
+			if ok && netErr.Timeout() {
+				reason = "timeout tailing new logs"
+			} else {
+				reason = "error reading websocket"
+			}
```
Comment (dannykopping) [inline pkg/canary/reader/reader.go:358]: You could simplify this a little (this is also a bit more _idiomatic_ Go):

```suggestion
			reason := "error reading websocket"
			
			if e, ok := err.(net.Error); ok && e.Timeout() {
				reason = "timeout tailing new logs"
			}
```

**Review by dannykopping — APPROVED** [review]
Looks good! Left a suggestion to make the code a bit more idiomatic.

File: pkg/canary/reader/reader.go (hunk 1 above)
Comment (dannykopping) [reply pkg/canary/reader/reader.go:358]: I think we should also include the timeout interval in the message.
It's not configurable, so folks will have to examine the source to find it otherwise

**Review by jeschkies — APPROVED** [review]

File: pkg/canary/reader/reader.go [hunk 2]
```diff
@@ -344,12 +344,19 @@ func (r *Reader) run() {
...
+		timeoutInterval := 10 * r.interval
+		_ = r.conn.SetReadDeadline(time.Now().Add(timeoutInterval))
 		// I assume this is a blocking call that either reads from the websocket connection
 		// or times out based on the above SetReadDeadline call.
 		err := unmarshal.ReadTailResponseJSON(tailResponse, r.conn)
 		if err != nil {
-			fmt.Fprintf(r.w, "error reading websocket, will retry in 10 seconds: %s\n", err)
+			reason := "error reading websocket"
+			if e, ok := err.(net.Error); ok && e.Timeout() {
+				reason = fmt.Sprintf("timeout tailing new logs (timeout period: %.2fs)", timeoutInterval.Seconds())
```
Comment (kavirajk) [inline pkg/canary/reader/reader.go:355]: [Q]: May be I failed to understand something here. Can you help me understand?

Wondering how does it can help catching `log_format` errors in promtail? (which was original source of error)

Basically I'm trying to understand, what happens when setting wrong format in promtail in this case. that won't even send logs to Loki? or canary's `unmarshal.ReadTailResponseJSON` timesout because it was expecting the correct format? (in that should we add some message saying something like `timesout because it was expecting different log format`)

Comment (dannykopping) [reply pkg/canary/reader/reader.go:355]: How can we distinguish between a log line that doesn't match a filter and a log line that doesn't exist?

**Review by dannykopping — APPROVED** [review]
LGTM :+1:

File: pkg/canary/reader/reader.go (hunk 2 above)
Comment (salvacorts) [reply pkg/canary/reader/reader.go:355]: @kavirajk 

> Basically I'm trying to understand, what happens when setting wrong format in promtail in this case. that won't even send logs to Loki? 

From my understanding, promtail does send logs to loki since you can actually run logcli to retrieve written logs.
E.g.
```
2021-11-25T14:20:07+01:00 {container="loki-canary", job="loki-dev-002/loki-canary", name="loki-canary", pod="loki-canary-8c49fcf8f-dm9qd", pod_template_hash="8c49fcf8f"}                                                       {"log":"1637846407189390762 ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\n","stream":"stdout","time":"2021-11-25T13:20:07.189497945Z"}
```

> or canary's unmarshal.ReadTailResponseJSON timesout because it was expecting the correct format?

Not quite; the problem, I believe, is that the query that the canary reader sends to the ingesters does not match any log because of the format is different from the expected one. Hence, since there are no matching logs, the tailing operation times out since no logs are streamed to the canary reader within the given amount of time specified as the deadline.

Comment (kavirajk) [reply pkg/canary/reader/reader.go:355]: So the error is due to missing log line correct?

in that case, should we also error something on the promtail side? why logs not being sent?

Forgive my ignore there, basically I’m trying to relate how could we improve our error handling so that operator can easily catch the log format error in future!.

Comment (kavirajk) [reply pkg/canary/reader/reader.go:355]: Thanks @salvacorts for the clarification!. 

>I believe, is that the query that the canary reader sends to the ingesters does not match any log because of the format is different from the expected one

Can we somehow catch this behaviour?

(btw. not a blocker anymore!. this error handling makes sense for the actual error)

**Review by kavirajk — APPROVED** [review]
LGTM! 🎉

File: pkg/canary/reader/reader.go (hunk 2 above)
Comment (dannykopping) [reply pkg/canary/reader/reader.go:355]: I don't _think_ we can, unfortunately.

The log message will be pretty clear now though: it will timeout looking for the logs, so naturally the operator will try to validate that the logs are indeed being sent to Loki. They will most likely see that they are in the wrong format at that point.
