### PR TITLE
promtail: added action_on_failure support to timestamp stage

### LINKED ISSUE #1093: Timestamp stage add a fudged timestamp for lines missing a timestamp
If using the timestamp stage and processing multi-line log lines, (or log lines that might not have a timestamp), the behavior could be a bit unpredictable.   

If the timestamp stage fails to match the timestamp, the promtail system time will be used for the log line, this creates a race between the last processed log lines timestamp and the system time, potentially leading to Loki rejecting the log line which had no timestamp as being older than the previous, or possibly the next log line with a timestamp being rejected if it's timestamp is older than what the system time applied was.

I am suggesting an option be added to the timestamp stage to allow fudging a timestamp onto log lines which do not have one.  The stage should keep track of the previous lines timestamp and if the next line coming in doesn't have a timestamp, increment the previous timestamp by one nanosecond and use that as the timestamp.

Fudging a timestamp is not great and could potentially lead to problems however, with nanosecond precision I would hope this to be very unlikely.

I also think the default for this behavior should be enabled, with an option to disable it

### PR DESCRIPTION
**Pull request by pracucci**
**What this PR does / why we need it**:

Currently, when the timestamp stage fails to parse the timestamp on a log entry, it keeps the time of when the entry has been scraped by Promtail. This may cause logs to fail to ingest due to out of order timestamps, because the "scrape timestamp" of an entry which failed parsing may be more recent than the "parsed timestamp" of a subsequent log entry.

In this PR I'm introducing the timestamp stage setting `action_on_failure` which can be:
- `fudge` (new default): change the timestamp to the last known timestamp, summing up 1 nanosecond
- `skip` (old behavior): do not change the timestamp and keep the time when the log entry has been scraped by Promtail

Unfortunately, just keeping an overall "last parsed timestamp" is not enough, because a single pipeline instance can process multiple targets (ie. logs from multiple files) and log timestamps should be expected to be ordered per single file only. For this reason, I've introduced an LRU cache to keep the "last known timestamp per target file" (the reason why I used an LRU is to add a cap to the max number of entries stored). So far, I haven't found a good solution for the journal target: any suggestion?

**Which issue(s) this PR fixes**:
Fixes #1093

**Special notes for your reviewer**:
- I've picked `github.com/hashicorp/golang-lru` for the LRU, which is already a dependency of other dependecies we have 

**Checklist**
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

**Comment by rfratto** [comment]
I'm trying to think of other ways we might be able to implement this so we can include journal support. One way might be to add extra metadata into the [entry handler](https://github.com/grafana/loki/blob/67f8ff8c64185cf8b541462e6ec0d07646411dc1/pkg/promtail/targets/tailer.go#L106) so we can pass a unique identifier to the pipeline instead of having the pipeline figure it out per target. Then we could also configure the journal target to pass through the unit name as the unique ID, which should be good enough in most cases. 

This is just a rough idea though, WDYT?

**Comment by pracucci** [comment]
Thanks @rfratto for the feedback. I do agree with you that guessing the ID in the timestamp stage is not the right approach.

> One way might be to add extra metadata into the entry handler so we can pass a unique identifier to the pipeline instead of having the pipeline figure it out per target. Then we could also configure the journal target to pass through the unit name as the unique ID, which should be good enough in most cases.

The unique identifier passed through the pipeline has no real value until that identifier is added as value of a label, because we need to guarantee uniqueness to the log streams pushed to Loki. So in the case we pick the unit name as "unique stream ID" (within a promtail instance) we'll need to also guarantee the unit name is always added to the labels, in the same way we do with `filename` for the file target.

What do you think?

**Comment by rfratto** [comment]
> The unique identifier passed through the pipeline has no real value until that identifier is added as value of a label, because we need to guarantee uniqueness to the log streams pushed to Loki.

I think I'm following you here; is the issue that the unique identifier may not be pushed to Loki, causing a bad entry in the LRU cache? 

>  So in the case we pick the unit name as "unique stream ID" (within a promtail instance) we'll need to also guarantee the unit name is always added to the labels, in the same way we do with filename for the file target.

I'm a little hesitant about this. I do think users will almost always include the unit name as a label for journal targets, but I don't want to take away the choice of omitting it. 

Overall I'm not sure why we couldn't just compute the fingerprint from the overall labelset and use that as the key into the LRU cache. I think it's fair to rely on the labelset passed through to the pipeline to be unique enough for the invoking stream without having to explicitly check for a specific label (filename/uid).

**Comment by pracucci** [comment]
> I think I'm following you here; is the issue that the unique identifier may not be pushed to Loki, causing a bad entry in the LRU cache?

Yes, correct.

> Overall I'm not sure why we couldn't just compute the fingerprint from the entire labelset

I thought about it, but unless the user doesn't add a "unique stream ID" (ie. unit name) as label via the relabelling config, the labels set may not guarantee stream uniqueness anyway, so we're shifting this responsability to the user instead of forcing it. Am I missing anything?

**Comment by rfratto** [comment]
No, you're right. It's already the user's responsibility to guarantee uniqueness per-file/unit if they're using a pipeline with a timestamp stage. I guess it's a question of whether or not it's a good idea to make it a hard requirement. 

I'm not sure I'm informed enough to have an opinion on this. We could make the unique identifier label configurable in the stage, but that might be over engineering this. 

/cc @cyriltovena @slim-bean any thoughts?

File: pkg/logentry/stages/timestamp.go [hunk 1]
```diff
@@ -67,49 +94,130 @@ func newTimestampStage(logger log.Logger, config interface{}) (*timestampStage,
...
+	// Fudge the timestamp
+	*t = lastTimestamp.(time.Time).Add(1 * time.Nanosecond)
+
+	// Store the fudged timestamp, so that a subsequent fudged timestamp will be 1ns after it
+	ts.lastKnownTimestamps.Add(streamID, *t)
+}
+
+func (ts *timestampStage) getStreamID(labels model.LabelSet) string {
+	// If the filename label is set, we assume it's a file target
+	if value, ok := labels["filename"]; ok {
```
Comment (cyriltovena) [inline pkg/logentry/stages/timestamp.go]: I think you should use `FastFingerprint()` from the `model.LabelSet` and use that for your map.

**Comment by cyriltovena** [comment]
I'm fine with this solution.  AFAIK you can have pipeline with journald targets ? Not sure what's the problem there.

**Comment by pracucci** [comment]
@rfratto @cyriltovena Thanks for your feedback. I've switched the "stream ID" to "labels fingerprint", which is a better solution compared to the previous one.

> AFAIK you can have pipeline with journald targets ? Not sure what's the problem there.

My only concern is that - contrary to the file target (which always has the `filename` label) - the journal target doesn't have any default labels, so it's the user responsability to add a label - before the `timestamp` stage - which uniquely identify the source log stream, otherwise the fudging will not be per source stream (required to avoid issues).
