### PR TITLE
Aggregate inotify watcher to file target manager

### LINKED ISSUE #4740: Promtail using lots of inotify instances
#### Description

On a system with 1189 containers (yes, really), promtail fails to register new watchers:

```
level=error ts=2021-10-28T11:35:44.792212392Z caller=filetargetmanager.go:263 msg="Failed to create target" key="{container_id=\"c517dad0337ef4991ed311d1c0efd2ab008102af1b730b8da31b4f3ffa3fe050\", container_name=\"elegant_meninsky\", container_status=\"exited\", instance=\"play64\"}" error="filetarget.fsnotify.NewWatcher: too many open files"
```

Looking at ulimits first, those don't seem to be the issue:

```py
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 566
```

However, promtail holds 111 inotify file-descriptors, which is quite close to the **user-wide** limit of 128:

```sh
# inside container, pid 1 is promtail
$ lsof -p 1 | grep inotify | wc -l
111

$ sysctl fs.inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 128
fs.inotify.max_user_watches = 8192
```

#### (Likely) cause

Promtail allocates a new `fsnotify.Watcher` for each target:

https://github.com/grafana/loki/blob/0116aa61c86fa983ddcbbd5e30a2141d2e89081a/clients/pkg/promtail/targets/file/filetarget.go#L80-L83

#### Solution

Raising `fs.inotify.max_user_instances` higher than the container count should allow promtail to operate fine (probably).

However, based on [this SE reply](https://unix.stackexchange.com/a/532844), it seems promtail should not allcoate an inotify handler for each target it watches, but use one for all.

This would only limit promtail to the 8192 inotify watches any user is permitted (which can also raised if anyone really has more containers than that). All in all promtail would run well in default setups more likely.

**To Reproduce**
1. Start a ridiculous amount of containers (they don't need to run, just log something once)
2. Run promtail (`grafana/promtail` on Docker, Image ID `8be4e7d21c56`)

Maybe related: https://github.com/grafana/loki/issues/1153

### PR DESCRIPTION
**Pull request by taisho6339**
**What this PR does / why we need it**:

Currently, Promtail creates inotify instances for each target.
`max_user_instances` isn't often high very much so I've made it singleton to reduce usage of the instances.

**Which issue(s) this PR fixes**:
Fixes #4740 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated
- [x] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Comment by taisho6339** [comment]
Input
```
scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs1
          __path__: /tmp/promtail/logs/1/*log
      - targets:
          - localhost
        labels:
          job: varlogs2
          __path__: /tmp/promtail/logs/2/*log
      - targets:
          - localhost
        labels:
          job: varlogs3
          __path__: /tmp/promtail/logs/3/*log
      - targets:
          - localhost
        labels:
          job: varlogs4
          __path__: /tmp/promtail/logs/4/*log
      - targets:
          - localhost
        labels:
          job: varlogs1
          __path__: /tmp/promtail/logs/5/*log
      - targets:
          - localhost
        labels:
          job: varlogs2
          __path__: /tmp/promtail/logs/6/*log
      - targets:
          - localhost
        labels:
          job: varlogs3
          __path__: /tmp/promtail/logs/7/*log
      - targets:
          - localhost
        labels:
          job: varlogs4
          __path__: /tmp/promtail/logs/8/*log
```

Before
```
root@b16260d2ebcc:/# lsof -p 1 | grep inotify | wc -l
8
```

After
```
root@9bc24279e1fa:/# lsof -p 1  | grep inotify | wc -l
1
```

File: clients/pkg/promtail/targets/file/filetarget.go [hunk 1]
```diff
@@ -156,24 +151,13 @@ func (t *FileTarget) run() {
...
-				matched, err := doublestar.Match(t.path, event.Name)
-				if err != nil {
-					level.Error(t.logger).Log("msg", "failed to match file", "error", err, "filename", event.Name)
-					continue
-				}
-				if !matched {
-					level.Debug(t.logger).Log("msg", "new file does not match glob", "filename", event.Name)
-					continue
-				}
 				t.startTailing([]string{event.Name})
```
Comment (taisho6339) [inline clients/pkg/promtail/targets/file/filetarget.go:157]: moved this logic to file target syncer

File: clients/pkg/promtail/targets/file/filetargetmanager.go [hunk 2]
```diff
@@ -105,30 +119,52 @@ func NewFileTargetManager(
...
+			entryHandler:      pipeline.Wrap(client),
+			targetConfig:      targetConfig,
+			fileEventWatchers: map[string]chan fsnotify.Event{},
 		}
 		tm.syncers[cfg.JobName] = s
 		configs[cfg.JobName] = cfg.ServiceDiscoveryConfig.Configs()
 	}
 
 	go tm.run()
+	go tm.watch()
```
Comment (taisho6339) [inline clients/pkg/promtail/targets/file/filetargetmanager.go:138]: To avoid channel deadlock, I separated this logic from `tm.run`

File: clients/pkg/promtail/targets/file/filetargetmanager.go [hunk 3]
```diff
@@ -105,30 +119,61 @@ func NewFileTargetManager(
...
+		case event := <-tm.watcher.Events:
+			// we only care about Create events
+			if event.Op == fsnotify.Create {
+				for _, s := range tm.syncers {
+					s.sendFileCreateEvent(event)
+				}
+			}
+		case err := <-tm.watcher.Errors:
+			level.Error(tm.log).Log("msg", "error from fswatch", "error", err)
+		case <-tm.watchDone:
```
Comment (cyriltovena) [inline clients/pkg/promtail/targets/file/filetargetmanager.go:167]: why not use the context line 69 ?

Comment (taisho6339) [reply clients/pkg/promtail/targets/file/filetargetmanager.go:167]: Ah, Right! We can use it.

File: clients/pkg/promtail/targets/file/filetargetmanager.go [hunk 4]
```diff
@@ -277,8 +324,23 @@ func (s *targetSyncer) sync(groups []*targetgroup.Group) {
 	s.droppedTargets = dropped
 }
 
-func (s *targetSyncer) newTarget(path string, labels model.LabelSet, discoveredLabels model.LabelSet) (*FileTarget, error) {
-	return NewFileTarget(s.metrics, s.log, s.entryHandler, s.positions, path, labels, discoveredLabels, s.targetConfig)
+func (s *targetSyncer) sendFileCreateEvent(event fsnotify.Event) {
```
Comment (jeschkies) [inline clients/pkg/promtail/targets/file/filetargetmanager.go:327]: Nit: Could you add a doc string? If I understand correctly the event is sent to the matching file target, right?

File: clients/pkg/promtail/targets/file/filetarget_test.go [hunk 5]
```diff
@@ -17,6 +21,43 @@ import (
 	"github.com/grafana/loki/clients/pkg/promtail/targets/testutils"
 )
 
+func createWatchers(ctx context.Context, path string) (chan fsnotify.Event, chan fileTargetEvent, error) {
```
Comment (jeschkies) [inline clients/pkg/promtail/targets/file/filetarget_test.go:24]: Now that `FileTaget` is not depending on any files anymore I wonder if this actually required. There's no need to write actual files to test `FileTarget`. This could be tested with the `FileTargetManager`. However, such a refactoring is a big ask.

**Review by jeschkies — APPROVED** [review]
This awesome! I just have a comment on the tests but it should not block this PR IMHO :slightly_smiling_face:

File: clients/pkg/promtail/targets/file/filetargetmanager.go (hunk 4 above)
Comment (taisho6339) [reply clients/pkg/promtail/targets/file/filetargetmanager.go:327]: > If I understand correctly the event is sent to the matching file target, right?

Right.
OK, I'll add the description to this function.

File: clients/pkg/promtail/targets/file/filetarget_test.go (hunk 5 above)
Comment (taisho6339) [reply clients/pkg/promtail/targets/file/filetarget_test.go:24]: > There's no need to write actual files to test FileTarget. 
I think so too and I think such a change is a little bit large as you said 😭 
If you are OK, can I refactor this test in another PR?

Comment (jeschkies) [reply clients/pkg/promtail/targets/file/filetarget_test.go:24]: > If you are OK, can I refactor this test in another PR?

Of course. Be my guest :slightly_smiling_face:

**Review by cyriltovena — APPROVED** [review]
LGTM

**Comment by ableuler** [comment]
This is a great improvement that we are desperately waiting for. Am I interpreting the release notes of [4.2.4](https://github.com/grafana/loki/releases/tag/v2.4.2) correctly in that there is no release yet which includes the changes introduced by this PR?

**Comment by tonychoe** [comment]
@ableuler looks like it was released in v2.5.0 
 https://github.com/grafana/loki/blob/main/CHANGELOG.md
