### PR TITLE
Setting sane defaults for ruler in SSD "read" mode

### LINKED ISSUE #5460: if target=read and ruler not configured, error about invalid configdb storage
**Describe the bug**
Trying to run the simple-scalable target for target=write/target=read and the read container threw this error and crashed:

> level=error ts=2022-02-23T14:12:56.608070392Z caller=log.go:106 msg="error running loki" err="configdb is not supported as a Loki rules backend type\nerror initialising module: ruler-storage\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:322\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"	

We are not using the Ruler and didn't have it configured at all in the config file. It looks like the defaults are set to a 'configdb' which isn't even a valid option according to the docs.

**To Reproduce**
1. Started Loki with target=read, using a config file that does NOT specify the `ruler` section
2. read container should crash/restart with the error about configdb

**Expected behavior**
Defaults values for ruler should probably be local file storage

**Environment:**
 - Infrastructure: AWS ECS-fargate
- Deployment tool: terraform
- Loki version: 2.4.2

### PR DESCRIPTION
**Pull request by dannykopping**
**What this PR does / why we need it**:
Allows the ruler to fail to start gracefully, if no ruler storage is configured.
Also removes support for `configdb`, since this is not supported but was the default storage type in the ruler code we forked from Cortex.

**Which issue(s) this PR fixes**:
Fixes #5460

**Special notes for your reviewer**:
If Loki SSD is run without ruler storage being configured, you get this nasty error:

```
configdb is not supported as a Loki rules backend type
error initialising module: ruler-storage
github.com/grafana/dskit/modules.(*Manager).initModule
        /home/danny/Code/open-source/loki/vendor/github.com/grafana/dskit/modules/modules.go:122
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
        /home/danny/Code/open-source/loki/vendor/github.com/grafana/dskit/modules/modules.go:92
github.com/grafana/loki/pkg/loki.(*Loki).Run
        /home/danny/Code/open-source/loki/pkg/loki/loki.go:344
main.main
        /home/danny/Code/open-source/loki/cmd/loki/main.go:105
runtime.main
        /home/danny/sdk/go1.17.8/src/runtime/proc.go:255
runtime.goexit
        /home/danny/sdk/go1.17.8/src/runtime/asm_amd64.s:1581
```

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

**Comment by trevorwhitney** [comment]
@dannykopping what's the status of this one? Happy to give it a review if you think it's ready?

**Comment by dannykopping** [comment]
> @dannykopping what's the status of this one? Happy to give it a review if you think it's ready?

Think I was waiting for CI to pass. Thanks for the nudge! Please review it :+1:

File: pkg/ruler/base/storage.go [hunk 1]
```diff
@@ -72,7 +70,7 @@ func (cfg *RuleStoreConfig) Validate() error {
 
 // IsDefaults returns true if the storage options have not been set
 func (cfg *RuleStoreConfig) IsDefaults() bool {
-	return cfg.Type == "configdb" && cfg.ConfigDB.ConfigsAPIURL.URL == nil
+	return cfg.Type == ""
```
Comment (trevorwhitney) [inline pkg/ruler/base/storage.go:73]: should we maybe default to local storage instead of nothing?

Comment (dannykopping) [reply pkg/ruler/base/storage.go:73]: I think the problem with defaulting to local storage is that it's not likely to work without configuration.
We can't assume that certain directories (or indeed even the filesystem) is writeable, and I'd rather push folks to have to configure the storage themselves. If we default local storage and they get errors, it'll be a bit confusing because they didn't explicitly set anything.

**Review by owen-d — APPROVED** [review]
I'm happy to improve this in the future, but I think this is a good improvement as-is.
