### PR TITLE
Collapse multiline logs based on a start line.

### LINKED ISSUE #74: Feature: multi-line logs
Currently when an multi-line event is written to a logfile promtail will take this as each row is its own entry and send the separately to loki. 

It would be great if Loki could handle multi-line events due to stacktraces.

This might also be a bug if promtail already should handle multi-lines.

### PR DESCRIPTION
**Pull request by jeschkies**
Summary:
This is a very simple approach based on #1380 to provide multiline
or block log entries in promtail.

A `multiline` stage is added to pipelines. This stages matches a start
line. Once a start line is matched all following lines are appended
to an entry and not passed on to downstream stages. Once a new start
line is matched the former block of multilines is sent.

If no new line arrives within `max_wait_time` the block is flushed to
the next stage and a new block is started.

If a block exceeds `max_lines` it is flushed as well.

**Which issue(s) this PR fixes**:
Resolves #74

**Checklist**
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

File: pkg/logentry/stages/multiline.go [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+	defer wg.Done()
+
+	state := &multilineState{
+		buffer:       new(bytes.Buffer),
+		currentLines: 0,
+	}
+
+	for {
+		select {
+		case <-time.After(m.cfg.maxWait):
```
Comment (cyriltovena) [inline pkg/logentry/stages/multiline.go:134]: I think we should also exit the goroutine after some time, a stream could stop sending data because the upstream pod/file/application is dead and a new one could start, over a long period of time we could end up with a lot of staled goroutines.

This could be after x cycle of maxWait that didn't flush anything. Careful you'll need to protect that map with a lock now and you might have a race when closing all stream vs one stream closing itself.

Comment (jeschkies) [reply pkg/logentry/stages/multiline.go:134]: > because the upstream pod/file/application is dead and a new one could start

Shouldn't the input channel close in this case? Ideally we would have a timer for the whole pipeline. What do you think?

Comment (cyriltovena) [reply pkg/logentry/stages/multiline.go:135]: In most cases the `in` would close, for the file case for instance yep. I'm not sure what would happen for syslog or other types of targets.

We can go like this and add an issue to cleanup goroutine when a stream go stale, and prioritize if someone has this issue later.

Another way to see it is should we make the goroutine only if `isFirstLine := m.cfg.regex.MatchString(e.Line)` is true ?

Comment (jeschkies) [reply pkg/logentry/stages/multiline.go:135]: That's a good point. Right now we would wait some time and try to flush an empty block and wait again. We only create a new goroutine when a new line with a new finger print arrives. I think we do need the first goroutine to manage the incoming lines and labels though. Should we add a timeout there? I.e. if nothing arrives we close? Which we might not want to do either though since the stage above might be sending new entries.

Comment (jeschkies) [reply pkg/logentry/stages/multiline.go:135]: Hm, I'd say we land this and create an issue to cleanup goroutines. It feels this is more evolved.

File: pkg/logentry/stages/multiline.go [hunk 2]
```diff
@@ -0,0 +1,195 @@
...
+	go func() {
+		defer close(out)
+
+		streams := make(map[model.Fingerprint](chan Entry))
+		wg := new(sync.WaitGroup)
+
+		for e := range in {
+			key := e.Labels.FastFingerprint()
+			s, ok := streams[key]
+			if !ok {
```
Comment (cyriltovena) [inline pkg/logentry/stages/multiline.go:104]: if there's no stream forming multiline and the line is not a first line, you should just send to out and continue.

I'm thinking a single promtail might handle thousand of streams, we don't need to create a goroutine if there's no sign of multiline yet.

We can do the cleanup later, but that seems easy enough. The only price we pay is doing the regex multiple times, but I'd guess it's fine or you can find a way to also signal this is the first line.

File: pkg/logentry/stages/multiline.go (hunk 1 above)
Comment (cyriltovena) [reply pkg/logentry/stages/multiline.go:135]: Let's do that for the cleanup but still check my other comment.

File: pkg/logentry/stages/multiline.go (hunk 2 above)
Comment (cyriltovena) [reply pkg/logentry/stages/multiline.go:104]:
```suggestion
			if !ok {
			  if !m.cfg.regex.MatchString(e.Line) {
			    out <- e
			    continue
			  }
```

Comment (jeschkies) [reply pkg/logentry/stages/multiline.go:104]: Ah, so we pass it through until a start line arrives. Cool. Will make the change.

Comment (cyriltovena) [reply pkg/logentry/stages/multiline.go:104]: yes I think that will buy is even more time.

File: docs/sources/clients/promtail/stages/multiline.md [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+multiline:
+  # RE2 regular expression, if matched will start a new multiline block.
+  # This expresion must be provided.
+  firstline: <string>
+
+  # The maximum wait time will be parsed as a Go duration: https://golang.org/pkg/time/#ParseDuration.
+  # If now new logs arrive withing this maximum wait time the current block will be sent on.
+  # This is useful if the opserved application dies with e.g. an exception. No new logs will arrive and the exception
+  # block is sent *after* the maximum wait time expired.
+  max_wait_time: <duration>
```
Comment (cyriltovena) [inline docs/sources/clients/promtail/stages/multiline.md:23]: Can we make this one optional, a good default is 3s like in the example.

Comment (cyriltovena) [reply docs/sources/clients/promtail/stages/multiline.md:23]: The reasoning is that I rarely see this needed to be different.

File: pkg/logentry/stages/multiline.go [hunk 4]
```diff
@@ -0,0 +1,203 @@
...
+	}
+}
+
+func (m *multilineStage) flush(out chan Entry, s *multilineState) {
+	if s.buffer.Len() == 0 {
+		level.Debug(m.logger).Log("msg", "nothing to flush", "buffer_len", s.buffer.Len())
+		return
+	}
+
+	collapsed := &Entry{
```
Comment (cyriltovena) [inline pkg/logentry/stages/multiline.go:184]: This doesn't have to be a pointer.

File: pkg/logentry/stages/multiline.go [hunk 5]
```diff
@@ -0,0 +1,203 @@
...
+			state.currentLines++
+
+			if state.currentLines == *m.cfg.MaxLines {
+				m.flush(out, state)
+			}
+		}
+	}
+}
+
+func (m *multilineStage) flush(out chan Entry, s *multilineState) {
```
Comment (cyriltovena) [inline pkg/logentry/stages/multiline.go:178]:
```suggestion
flush(out chan Entry, s *multilineState) {
```

File: pkg/logentry/stages/multiline.go [hunk 6]
```diff
@@ -0,0 +1,210 @@
...
+		streams := make(map[model.Fingerprint](chan Entry))
+		wg := new(sync.WaitGroup)
+
+		for e := range in {
+			key := e.Labels.FastFingerprint()
+			s, ok := streams[key]
+			if !ok {
+				// Pass through entries until we hit first start line.
+				if !m.cfg.regex.MatchString(e.Line) {
+					level.Debug(m.logger).Log("msg", "pass through entry", "stream", key)
```
Comment (cyriltovena) [inline pkg/logentry/stages/multiline.go:114]: This sucks but all debug logs that are in the hot path should be using:

```
if Debug{
}
```

This is because the logger is really not performant, even if the debug log is deactivated. (expensation of strings still happen).

see https://github.com/grafana/loki/blob/master/cmd/promtail/main.go#L85

File: pkg/logentry/stages/multiline.go [hunk 7]
```diff
@@ -0,0 +1,210 @@
...
+			state.currentLines++
+
+			if state.currentLines == *m.cfg.MaxLines {
+				m.flush(out, state)
+			}
+		}
+	}
+}
+
+flush(out chan Entry, s *multilineState) {
```
Comment (cyriltovena) [inline pkg/logentry/stages/multiline.go:185]: sorry the func is missing :p my bad

```suggestion
func flush(out chan Entry, s *multilineState) {
```

**Review by cyriltovena — APPROVED** [review]
LGTM Great work @jeschkies 

I know some folks that will be happy !

There's one last comment before we merge, about logging.

File: pkg/logentry/stages/multiline.go (hunk 7 above)
Comment (jeschkies) [reply pkg/logentry/stages/multiline.go]: Just found that I use `m` for logging.

Comment (cyriltovena) [reply pkg/logentry/stages/multiline.go]: Sorry 🤦

**Comment by yacut** [comment]
Wow, great work @jeschkies 🥇

**Review by owen-d — APPROVED** [review]
A bit late on my review, but LGTM.

The one area I think we're lacking to address is log files which have many different structures (where the `firstline` concept feels a bit lacking). Not something we need to solve now though.

File: docs/sources/clients/promtail/stages/multiline.md [hunk 8]
```diff
@@ -0,0 +1,67 @@
+---
+title: multiline 
+---
+
+# `multiline` stage
+
+The `multiline` stage multiple lines into a multiline block before passing it on to the next stage in the pipeline.
```
[the remark this answers is not in the document]
Comment (jeschkies) [reply docs/sources/clients/promtail/stages/multiline.md:7]: Thanks. I've addressed it in https://github.com/grafana/loki/pull/3029

File: docs/sources/clients/promtail/stages/multiline.md [hunk 9]
```diff
@@ -0,0 +1,67 @@
...
+    return self.view_functions[rule.endpoint](**req.view_args)
+  File "/home/pallets/src/deployment_tools/hello.py", line 10, in error
+    raise Exception("Sorry, this route always breaks")
+Exception: Sorry, this route always breaks
+[2020-12-03 11:36:23] "GET /error HTTP/1.1" 500 -
+[2020-12-03 11:36:26] "GET /hello HTTP/1.1" 200 -
+[2020-12-03 11:36:27] "GET /hello HTTP/1.1" 200 -
+```
+
+We would like to collapse all lines of the traceback into one multiline block. All blocks start with a timestamp in brackets. Thus we configure a `multiline` stage with the `firstline` regular expression `^\[\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}\]`. This will match the start of the traceback but not the following lines until `Exception: Sorry, this route always breaks`. These will be part of a multiline block and one log entry in Loki.
```
[the remark this answers is not in the document]
Comment (jeschkies) [reply docs/sources/clients/promtail/stages/multiline.md:59]: Thanks. I've addressed it in https://github.com/grafana/loki/pull/3029
