### PR TITLE
Fix Series API slowness

### LINKED ISSUE #2121: Loki API /series can be too slow
`loki_api_v1_series` endpoint fetches chunks serially in batches of 50. This can make it very slow if many chunks need to be fetched.

Here is a screenshot, and trace that triggered an alarm.

Screenshot 2020-05-25 at 08 59 14

[5f0d55710be2dbcd.json.txt](https://github.com/grafana/loki/files/4675665/5f0d55710be2dbcd.json.txt)

### PR DESCRIPTION
**Pull request by adityacs**
**What this PR does / why we need it**:
Fix Series API slowness

**Which issue(s) this PR fixes**:
Fixes #2121 

**Checklist**
- [x] Tests updated

### CODE REVIEW

**Comment by adityacs** [comment]
This is just an attempt to fix the API slowness. I may be wrong. How do we write test for this with actual store to know the latency?

**Comment by adityacs** [comment]
> The problem with the current approach is that you may load a lot of chunks in memory that can cause the querier to OOM. Currently it's limited by s.cfg.MaxChunkBatchSize which is 50 at the time.

Got your point. I didn't realize this

**Comment by owen-d** [comment]
Oh yes, I'd much rather we solve this via parallelization in the frontend the same way we do for other queries. Would you like to pick up that approach instead?

File: pkg/querier/queryrange/split_by_interval.go [hunk 1]
```diff
@@ -166,22 +166,41 @@ func (h *splitByInterval) Do(ctx context.Context, r queryrange.Request) (queryra
 		return h.next.Do(ctx, r)
 	}
 
-	intervals := splitByTime(lokiRequest, interval)
-	h.metrics.splits.Observe(float64(len(intervals)))
+	var intervals []queryrange.Request
+	var limit int64
+	switch req := r.(type) {
+	case *LokiRequest:
```
Comment (owen-d) [inline pkg/querier/queryrange/split_by_interval.go:172]: I don't think you need all this duplicate logic:
```go
		intervals = splitByTime(req, interval)
		h.metrics.splits.Observe(float64(len(intervals)))
		// no interval should not be processed by the frontend.
		if len(intervals) == 0 {
			return h.next.Do(ctx, r)
		}
```

Instead I think you can perform just one type switch, checking if it's a series request and then setting the limit to 0 as all the other logic is identical

File: pkg/querier/queryrange/split_by_interval.go [hunk 2]
```diff
@@ -219,3 +238,20 @@ func splitByTime(r *LokiRequest, interval time.Duration) []queryrange.Request {
 	}
 	return reqs
 }
+
+func splitSeriesByTime(r *LokiSeriesRequest, interval time.Duration) []queryrange.Request {
```
Comment (owen-d) [inline pkg/querier/queryrange/split_by_interval.go:242]: This can be consollidated by having the `splitByTime` function accept a `queryrange.Request` instead of a `*LokiRequest` and then using the `WithStartEnd` method of that interface.

File: pkg/querier/queryrange/split_by_interval.go [hunk 3]
```diff
@@ -193,29 +203,21 @@ func (h *splitByInterval) Do(ctx context.Context, r queryrange.Request) (queryra
...
 }
 
-func splitByTime(r *LokiRequest, interval time.Duration) []queryrange.Request {
+func splitByTime(req queryrange.Request, interval time.Duration) []queryrange.Request {
 	var reqs []queryrange.Request
-	for start := r.StartTs; start.Before(r.EndTs); start = start.Add(interval) {
-		end := start.Add(interval)
-		if end.After(r.EndTs) {
-			end = r.EndTs
+	for start := req.GetStart(); start < req.GetEnd(); start = start + interval.Milliseconds() {
```
Comment (adityacs) [inline pkg/querier/queryrange/split_by_interval.go:215]: This change limits us to use only `millisecond`. Since, `GetStart` and `GetEnd` methods converts the time to `milliseconds` we won't able to measure anything below `millisecond`

**Comment by adityacs** [comment]
@owen-d Have made the changes based on your comments. Kindly review.

File: pkg/querier/queryrange/split_by_interval.go (hunk 3 above)
Comment (owen-d) [reply pkg/querier/queryrange/split_by_interval.go:215]: Great point, I didn't think of that.

I think your original approach is better :)

File: pkg/querier/queryrange/codec_test.go [hunk 4]
```diff
@@ -168,6 +184,35 @@ func Test_codec_EncodeRequest(t *testing.T) {
 	require.Equal(t, "/loki/api/v1/query_range", req.(*LokiRequest).Path)
 }
 
+func Test_codec_sereis_EncodeRequest(t *testing.T) {
```
Comment (owen-d) [inline pkg/querier/queryrange/codec_test.go:187]:
```suggestion
func Test_codec_series_EncodeRequest(t *testing.T) {
```

**Comment by owen-d** [comment]
Thanks for addressing my comments; it looks great. Just a bit of cleanup then we can get this merged
