### PR TITLE
fix(logcli): timestamp timezone handling

### LINKED ISSUE #798: Mixed UTC and Local timezone on "logcli query"
If `loki` is running on a system with the timezone different than UTC, then the output of `logcli query` will display log entries with mixed timezone (UTC and Local).

The reason is that `logcli query` will query both the ingesters and the store. The ingesters internally store the timestamps with a `time.Time` in `UTC` timezone, while the storage reads the entries timestamp from chunk blocks in the `Local` timezone.

In particular, the parsing of a log entry timestamp is done in `pkg/chunkenc/gzip.go` at `bufferedIterator.Next()`:
```
si.cur.Timestamp = time.Unix(0, ts)
```

`time.Unix()` parses an unix epoch timestamp in UTC timezone returning a `time.Time` in the `Local` timezone.

I would like to work on an improvement, and I'm suggesting the following:
1. Always enforce UTC inside loki, so changing the timestamp parsing into `si.cur.Timestamp = time.Unix(0, ts).UTC()`
2. Add an option to `logcli query` to specify the timezone with which the user prefers the timestamps (can be `UTC` or `Local`) and then enforce it while formatting the output

What's your take?

### PR DESCRIPTION
**Pull request by pracucci**
**What this PR does / why we need it**:
The `logcli query` command prints the timestamp in the same timezone the `time.Time` was instantiated by `loki`, which currently is a mix of UTC and Local (depends on where the log entry comes from: storage or ingester).

In this PR I'm suggesting to enforce the output timestamp in `logcli` to keep it consistent and introduce a cli flag `--timezone / -z` which currently accepts `UTC` or `Local` (default).

**Which issue(s) this PR fixes**:
Fixes #798

**Special notes for your reviewer**:

In this PR I didn't pick the shortest path to implement the `--timezone` option, while I'm proposing to refactor the code to make it easier testable (and hopefully cleaner). In details:
1. Moved the output implementation to `pkg/logcli/output/` + tests
2. The `LogOutput` instance is no more a global variable
3. In `cmd/logcli/query.go` you will notice I've also fixed a bug, from `ls = subtract(common, ls)` to `ls = subtract(ls, common)`
4. I've also added `--no-labels` support to `jsonl` output mode

_If the proposed refactoring structure will be accepted, I would be glad to continue the refactoring in subsequent PRs in order to cover the other `logcli` features with tests._

The following shows an example of `logcli query` after the changes:

```
$ ./logcli query --addr="http://localhost:3100" '{type="test"}' -z UTC

2019/07/31 13:05:03 http://localhost:3100/api/prom/query?query=%7Btype%3D%22test%22%7D&limit=3&start=1564567503262037000&end=1564571103262037000&direction=BACKWARD&regexp=
2019/07/31 13:05:03 Common labels: {type="test"}
2019-07-31T11:05:01Z {filename="/tmp/test-1.json"}    test
2019-07-31T11:04:56Z {filename="/tmp/test-2000.json"} test
2019-07-31T11:04:54Z {filename="/tmp/test-2.json"}    test

$ ./logcli query --addr="http://localhost:3100" '{type="test"}' -z Local

2019/07/31 13:05:25 http://localhost:3100/api/prom/query?query=%7Btype%3D%22test%22%7D&limit=3&start=1564567525885051000&end=1564571125885051000&direction=BACKWARD&regexp=
2019/07/31 13:05:25 Common labels: {type="test"}
2019-07-31T13:05:01+02:00 {filename="/tmp/test-1.json"}    test
2019-07-31T13:04:56+02:00 {filename="/tmp/test-2000.json"} test
2019-07-31T13:04:54+02:00 {filename="/tmp/test-2.json"}    test

$ ./logcli query --addr="http://localhost:3100" '{type="test"}' -z UTC --exclude-label filename

2019/07/31 13:06:01 http://localhost:3100/api/prom/query?query=%7Btype%3D%22test%22%7D&limit=3&start=1564567561691020000&end=1564571161691020000&direction=BACKWARD&regexp=
2019/07/31 13:06:01 Common labels: {type="test"}
2019/07/31 13:06:01 Ignoring labels key: filename
2019-07-31T11:05:01Z {} test
2019-07-31T11:04:56Z {} test
2019-07-31T11:04:54Z {} test

$ ./logcli query --addr="http://localhost:3100" '{type="test"}' -z UTC --include-label type

2019/07/31 13:06:21 http://localhost:3100/api/prom/query?query=%7Btype%3D%22test%22%7D&limit=3&start=1564567581382353000&end=1564571181382353000&direction=BACKWARD&regexp=
2019-07-31T11:05:01Z {filename="/tmp/test-1.json", type="test"}    test
2019-07-31T11:04:56Z {filename="/tmp/test-2000.json", type="test"} test
2019-07-31T11:04:54Z {filename="/tmp/test-2.json", type="test"}    test
```

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: pkg/logcli/output/default_test.go [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+
+import (
+	"testing"
+	"time"
+
+	"github.com/prometheus/prometheus/pkg/labels"
+	"github.com/stretchr/testify/assert"
+)
+
+func TestDefaultOutput_Format(t *testing.T) {
```
Comment (sh0rez) [inline pkg/logcli/output/default_test.go]: You could test whether labels are padded correctly as well here ;)

File: pkg/logcli/output/jsonl_test.go [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+
+import (
+	"testing"
+	"time"
+
+	"github.com/prometheus/prometheus/pkg/labels"
+	"github.com/stretchr/testify/assert"
+)
+
+func TestJSONLOutput_Format(t *testing.T) {
```
Comment (sh0rez) [inline pkg/logcli/output/jsonl_test.go]: maybe test whether this is even valid json

File: pkg/logcli/output/output.go [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+	"fmt"
+	"time"
+
+	"github.com/prometheus/prometheus/pkg/labels"
+)
+
+// LogOutput is the interface any output mode must implement
+type LogOutput interface {
+	Format(ts time.Time, lbls *labels.Labels, maxLabelsLen int, line string) string
+	Print(ts time.Time, lbls *labels.Labels, maxLabelsLen int, line string)
```
Comment (sh0rez) [inline pkg/logcli/output/output.go]: I would remove this function from the `interface`. It is kind of redundant to make every implementation include `fmt.Println(line)`. This could be easily handled outside, either by just returning a string to logcli and printing it there, or by wrapping the actual output:

```go
type LogFormatter interface {
  Format(ts time.Time, lbls *labels.Labels, maxLabelsLen int, line string) string
}

type LogOutput struct {
  f *LogFormatter
}

func (o LogOutput) Print(ts time.Time, lbls *labels.Labels, maxLabelsLen int, line string) {
  fmt.Println(o.f.Format(ts, lbls, maxLabelsLen, line)
}

func NewLogOutput(mode string, options *LogOutputOptions) (LogOutput, error) {
  var formatter *LogFormatter  
  switch mode {
    // ...
  }
  return LogOutput{f: formatter}
}

File: pkg/logcli/output/default_test.go (hunk 1 above)
Comment (pracucci) [reply pkg/logcli/output/default_test.go]: From my perspective, it's what the test `max labels length longer than input labels` does. Do you have something different in mind?

File: pkg/logcli/output/output.go (hunk 3 above)
Comment (pracucci) [reply pkg/logcli/output/output.go]: I agree with you. I'm going to pick the shortest path here (calling `fmt.Println()` from outside) and we can eventually re-iterate on it on a second step, if you agree.

File: pkg/logcli/output/default_test.go (hunk 1 above)
Comment (sh0rez) [reply pkg/logcli/output/default_test.go]: I thought of pushing some lines and checking whether they are properly aligned ... nice to have, but the current one suffices as well

File: pkg/logcli/output/jsonl_test.go (hunk 2 above)
Comment (pracucci) [reply pkg/logcli/output/jsonl_test.go]: Good idea, done.

File: pkg/logcli/output/default_test.go (hunk 1 above)
Comment (pracucci) [reply pkg/logcli/output/default_test.go]: I'm always in favour of having a good tests coverage. Let me work on it.

Comment (pracucci) [reply pkg/logcli/output/default_test.go]: What do you think about the approach [taken here](https://github.com/grafana/loki/pull/821/commits/50e4a1ae8909f96a4e7de913b7ffcb1423bcb898)?

Comment (sh0rez) [reply pkg/logcli/output/default_test.go]: That's pretty neat! Thanks :)
