### PR TITLE
Fix loki exit on jaeger agent not being present

### LINKED ISSUE #1397: Loki exits when the configured jaeger is not present
I'd argue that Loki should not just exit when a configured jaeger is not present.

This came up when testing loki and jaeger together in the grafana's devenv docker-compose snippets: Loki would no longer start on its own, and I had to remove the env vars: https://github.com/grafana/grafana/pull/20967

Here is the docker compose output:
```
loki_1         | Could not initialize jaeger tracer: lookup jaeger on 127.0.0.11:53: no such host
```

### PR DESCRIPTION
**Pull request by adityacs**
**What this PR does / why we need it**:
Fix loki exit on jaeger agent not being present

**Which issue(s) this PR fixes**:
Fixes #1397

### CODE REVIEW

File: cmd/loki/main.go [hunk 1]
```diff
@@ -51,12 +51,18 @@ func main() {
...
+		level.Error(util.Logger).Log("msg", "error in initializing tracing. tracing will not be enabled", "err", err)
+	}
 	defer func() {
-		if err := trace.Close(); err != nil {
-			level.Error(util.Logger).Log("msg", "error closing tracing", "err", err)
-			os.Exit(1)
+		if trace != nil {
+			if err := trace.Close(); err != nil {
+				level.Error(util.Logger).Log("msg", "error closing tracing", "err", err)
+				os.Exit(1)
```
Comment (cyriltovena) [inline cmd/loki/main.go]: I don't think we need this os.Exit(1) I know it was there but I'm willing to get rid of it.

Comment (adityacs) [reply cmd/loki/main.go]: removed

Comment (cyriltovena) [reply cmd/loki/main.go]: There is some go mod sync issue still.
