### PR TITLE
Fix fluent-bit newline and tab characters

### LINKED ISSUE #2246: Fluent-bit plugin encoded characters
**Describe the bug**
When sending events (which are Java Logs in json) from Fluent-bit to Loki encoded  characters within record are shown as plain text in Grafana. For example instead of newline there is `\n`
I think there is some issue with plugin itself as fluent-bit logs are ok.
Also tested the same log messages with FluentD and FluentD Loki plugin - everything is ok in Grafana

**To Reproduce**
Send JSON Log Message with stacktrace (Java exceptions for example)

**Expected behavior**
Grafana displays newlines and tabs instead of `\n` `\t`

**Environment:**
Fluent-bit-->Loki<--Grafana
 - Infrastructure: Kubernetes
 - Deployment tool: helm (loki/fluent-bit, loki/loki charts)

**Screenshots, Promtail config, or terminal output**
Fluent-bit logs:
```
[1] kube.var.log.containers.cst-gap-6f99986fff-hpzbt_cst-gap-dev_cst-gap-dd17add6b3620f756565aedfc9f3aae578fdf09f22e641c6e0fc3d458c5b94c9.log: [1592739931.069359238, {"app"=>"spring.application.name_IS_UNDEFINED", "ts"=>"2020-06-21T11:45:31.031Z", "logger"=>"org.zalando.problem.spring.web.advice.AdviceTrait", "level"=>"ERROR", "class"=>"org.zalando.problem.spring.web.advice.AdviceTrait", "method"=>"log", "file"=>"AdviceTrait.java", "line"=>246, "thread"=>"http-nio-8088-exec-3", "stack"=>"com.intellecteu.miml.ug.annotationsui.controller.errors.InternalServerErrorException: Could not fetch collections from database
	at com.intellecteu.miml.ug.annotationsui.utils.IOUtils.convertStreamIntoCollection(IOUtils.java:91)
	at com.intellecteu.miml.ug.annotationsui.service.GridFsServiceImpl.lambda$fetchCollections$1(GridFsServiceImpl.java:100)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.intellecteu.miml.ug.annotationsui.service.CollectionServiceImpl.getCollections(CollectionServiceImpl.java:167)
...
```
Fluent-bit config:
```
 [SERVICE]
        HTTP_Server    On
        HTTP_Listen    0.0.0.0
        HTTP_PORT      2020
        Flush          1
        Daemon         Off
        Log_Level      warn
        Parsers_File   parsers.conf
    [INPUT]
        Name           tail
        Tag            kube.*
        Path           /var/log/containers/*.log
        Parser         docker
        DB             /run/fluent-bit/flb_kube.db
        Mem_Buf_Limit  5MB
    [FILTER]
        Name           kubernetes
        Match          kube.*
        Kube_URL       https://kubernetes.default.svc:443
        Merge_Log On
        K8S-Logging.Parser Off
    [Output]
        Name loki
        Match *
        Url http://RELEASE-NAME-loki:3100/api/prom/push
        TenantID ""
        BatchWait 1
        BatchSize 10240
        Labels {job="fluent-bit"}
        RemoveKeys kubernetes,stream
        AutoKubernetesLabels false
        LabelMapPath /fluent-bit/etc/labelmap.json
        LineFormat json
        LogLevel warn
  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

  labelmap.json: |-
    {
      "kubernetes": {
        "container_name": "container",
        "host": "node",
        "labels": {
          "app": "app",
          "release": "release"
        },
        "namespace_name": "namespace",
        "pod_name": "instance"
      },
      "stream": "stream"
    }
```
Grafana output with Fluent-bit as collector and  shipper
image

Grafana output with FluentD as collector and shipper
image

### PR DESCRIPTION
**Pull request by adityacs**
**What this PR does / why we need it**:
Fixes fluent-bit newline and tab characters

**Which issue(s) this PR fixes**:
Fixes #2246

### CODE REVIEW

File: cmd/fluent-bit/loki.go [hunk 1]
```diff
@@ -226,12 +227,17 @@ func createLine(records map[string]interface{}, f format) (string, error) {
...
 	default:
 		return "", fmt.Errorf("invalid line format: %v", f)
 	}
 }
 
+func replaceNewLineAndTab(line string) string{
+	replacer := strings.NewReplacer(`\n`, "\n", `\t`, "\t")
+	return replacer.Replace(line)
+}
+
```
Comment (adityacs) [inline cmd/fluent-bit/loki.go:240]: This is a hacky solution. Somewhere the encoding by Json and logfmt is treating `\n` and `\t` as escaped. So, we have to replace those with actual `\n` and `\t`.

Any better ways?

Comment (cyriltovena) [reply cmd/fluent-bit/loki.go:240]: well I guess the replacer can be global for sure.

Comment (cyriltovena) [reply cmd/fluent-bit/loki.go:240]: And so you probably don't need this function.

Comment (cyriltovena) [reply cmd/fluent-bit/loki.go:240]: Yeah looks like a fine solution to me. Basically unescaping those characters.

Comment (cyriltovena) [reply cmd/fluent-bit/loki.go:240]: Have you tried to see what fluentd send for those ? I'm curious to see if they do the same.

Comment (adityacs) [reply cmd/fluent-bit/loki.go:240]: Fluent-bit records are fine as well. I just checked the content before Marshaling the record here 
https://github.com/grafana/loki/blob/7399beff4aaacb1a1c0c925101d88bedf2cd9666/cmd/fluent-bit/loki.go#L203
`\n` and `\t` looks fine here. 

But after the marshaling, result from `jsoniter.ConfigCompatibleWithStandardLibrary.Marshal(records)` doesn't respect `\n` and `\t`. Looks like Marshaling is escaping these characters. 

Same applies to `logfmt` encoding as well
https://github.com/grafana/loki/blob/7399beff4aaacb1a1c0c925101d88bedf2cd9666/cmd/fluent-bit/loki.go#L217

Comment (cyriltovena) [reply cmd/fluent-bit/loki.go]: Which is correct everything is enclosed by "" and \ must be escaped. May be this is more a Grafana issue ? when reading \\n it should read \n ? cc @aocenas WDYT ?

File: cmd/fluent-bit/loki.go [hunk 2]
```diff
@@ -115,12 +118,13 @@ func autoLabels(records map[string]interface{}, kuberneteslbs model.LabelSet) er
 		return errors.New("kubernetes labels not found, no labels will be added")
 	}
 
-	replacer := strings.NewReplacer("/", "_", ".", "_", "-", "_")
+	keyReplacer := strings.NewReplacer("/", "_", ".", "_", "-", "_")
```
Comment (cyriltovena) [inline cmd/fluent-bit/loki.go:121]: that could be global too while we are at it.

Comment (adityacs) [reply cmd/fluent-bit/loki.go:121]: Yeah initially made that global but got error https://cloud.drone.io/grafana/loki/3437/1/2

File: cmd/fluent-bit/loki.go (hunk 1 above)
Comment (adityacs) [reply cmd/fluent-bit/loki.go]: Yeah, this can be handled from Grafana side as well. However, line would be this `Hello\nworld` and not `Hello\\nworld`. So, on Grafana they can replace `\n` with actual newline.

File: cmd/fluent-bit/loki.go (hunk 2 above)
Comment (cyriltovena) [reply cmd/fluent-bit/loki.go:121]: not sure what you mean moving this to a new global variable, should be fine ?

Comment (adityacs) [reply cmd/fluent-bit/loki.go:121]: For example if the log message has `12.2 foo bar` as value, doing replace with this global replacer `strings.NewReplacer("/", "_", ".", "_", "-", "_", `\n`,, "\n", `\t`, "\t")` will make the log message as `12_2 foo bar` which is not desired.

Comment (cyriltovena) [reply cmd/fluent-bit/loki.go:121]: that is not what I was really asking to use a single replace, but two globals, one for key one for line.

Comment (adityacs) [reply cmd/fluent-bit/loki.go:121]: you mean we can have 2 separate global variables?

Comment (cyriltovena) [reply cmd/fluent-bit/loki.go:121]: yes !

Comment (adityacs) [reply cmd/fluent-bit/loki.go]: Done

**Comment by RomanBadiornyi** [comment]
Hi guys, we're running into the same issue. Can you please help to understand at what version this fix included? We use grafana 8.3.3, loki 2.3.0 and fluent bit 1.8.11
