### PR TITLE
reduce number of list calls on shared object store when using boltdb-shipper

### LINKED ISSUE #3258: Seeing unnatural high amount of calls to S3ListObject when running BoltDB Shipper
**Describe the bug**
After activating detailed metrics on our S3 Loki Bucket, we saw that we had a very large volume of calls to S3ListObject, about 3M per day, which seemed way too high. I talked a bit with @owen-d about it, and after some digging around I found the following:
- We have 62 tables in S3 stored with BoltDB
- We run 5 queriers

Each querier seem to be doing multiple calls per minute to `sync` tables, as evident by the following log query:
`{namespace="kube-loki"} |~"(?i)todownload" !="query_type"`:
image

I also looked at the metric `loki_boltdb_shipper_tables_sync_operation_total`, and summed by `job`, it looks like this for the last 24 hours (`sum by (job) (loki_boltdb_shipper_tables_sync_operation_total)`):
image

Basically, `querier` has about 80000 and `ruler` about 17000 for the last 24 hours.

According to the code, this gets incremented here https://github.com/grafana/loki/blob/cd723c0479fc8bbdd1a01b6cee0e129503f58d08/pkg/storage/stores/shipper/downloads/table_manager.go#L205
A few lines after, it does a `table.Sync` call for each table in `tableManager`, which ends up here as a call to S3 ListObjects https://github.com/grafana/loki/blob/6d442673b7279eef4b7aa88d0af0ceb72bba7fe9/pkg/storage/stores/shipper/downloads/table.go#L401

**Expected behavior**
Fewer calls to S3ListObjects

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Manual
 - Loki 2.1

Tagging @owen-d and @sandeepsukhani as requested by Owen :)

### PR DESCRIPTION
**Pull request by sandeepsukhani**
**What this PR does / why we need it**:
We as of now do a LIST calls per table when we need to find its objects.
If someone has a lot of tables cached locally or has query readiness set to a large number of days, it results in a lot of list calls because each querier tries to sync tables every 5 mins by default.
This PR reduces the number of LIST calls we make when using hosted object stores(S3, GCS, Azure Blob Storage and Swift) as a shared store for boltdb-shipper.

The idea is to do a flat listing of objects which is only supported by hosted object stores mentioned above.
In case of boltdb files stored by the shipper, the listed objects would have keys like <table-name>/<filename>.
For each List call without a prefix(which is actually done to get a list of tables), we would build a map of `TableName` -> `chunk.StorageObject` which would be used as a cache for subsequent List calls for getting the list of objects for tables.
Cache items are evicted after the first read or a timeout. The cache is rebuilt during List call for table names or we encounter a cache miss.

**Special notes for your reviewer**:
I am going to send a subsequent PR to move all the code for ObjectClient and object key processing to a common package to contain all the complexity of processing the object keys, responses and delimiters with a goal to provide a simplified interface to the shipper which would have methods like `ListTables`, `ListTableObjects` etc. 

Fixes #3258 

**Checklist**
- [x] Tests updated

### CODE REVIEW

File: pkg/storage/stores/shipper/util/cached_client.go [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+
+	// requested element not found in the cache, rebuild the cache.
+	_, err := c.listTables(ctx)
+	if err != nil {
+		return nil, err
+	}
+
+	objects = c.tables[tableName]
+	// evict the element read from cache
+	delete(c.tables, tableName)
```
Comment (cyriltovena) [inline pkg/storage/stores/shipper/util/cached_client.go:109]: why do we evict element read from cache ?

Comment (sandeepsukhani) [reply pkg/storage/stores/shipper/util/cached_client.go:109]: This is to avoid any possible bugs if the caller misses refreshing the cache explicitly.
The cache is integrated to make it look seamless for consumers since it only works for hosted object stores.
Removing it should not be big of a problem since we have a ttl but I just added it as an extra protection mechanism.

Comment (cyriltovena) [reply pkg/storage/stores/shipper/util/cached_client.go:109]: but if we ask twice the same table then we will call twice List on the objectstore ?

**Review by cyriltovena — APPROVED** [review]
LGTM don't want to block you but I don't fully understand how cache eviction works.

File: pkg/storage/stores/shipper/util/cached_client.go (hunk 1 above)
Comment (sandeepsukhani) [reply pkg/storage/stores/shipper/util/cached_client.go:109]: yeah but we don't have a use case where we will list objects from the same table twice. We usually circle through a list of tables for sync or compaction so we will not hit this case most likely. The only case it can happen is if someone has a really low sync interval and the non-deterministic [iteration of maps](https://github.com/grafana/loki/blob/923671a17e250542e10037f514e8f5c21fa205b9/pkg/storage/stores/shipper/downloads/table_manager.go#L210) in go can make the same table to be synced back to back.

Comment (sandeepsukhani) [reply pkg/storage/stores/shipper/util/cached_client.go:109]: We can always remove this if we see it causing a problem.
