### PR TITLE
fix bugs in processing delete requests with line filters and add proper tests

### LINKED ISSUE #7590: Loki Compactor Log Deletion Not Working When Using Line Filters
**Describe the bug**
Loki Compactor `/loki/api/v1/delete` endpoint does not delete logs when line filters are included in the query. On the other hand, logs are deleted if only stream filters are included.
* `query={facility="archilogen"}` works
* `query={facility="archilogen"}|="archilogen-warn"` does not work

**To Reproduce**
1. Start Loki 2.6.1
2. Generate and Forward logs with custom labels and messages. Example: `{facility:archilogen} '{"message":"archilogen-warn"}'`
3. Wait for Chunk to become idle and be sent to the object store
4. Request deletion of Logs
```
curl -I -X POST -H 'X-scope-OrgID: main' -g 'http://<loki_address>/loki/api/v1/delete?query={facility="archilogen"}|="archilogen-warn"'
HTTP/1.1 204 No Content
```
5. verify that the deletion request was successfully initiated:
```
curl -H 'X-scope-OrgID: main' 'http://xxx:3020/loki/api/v1/delete' | jq '.[] | select(.status=="received")'

{
  "request_id": "7cdae6e5",
  "start_time": 0,
  "end_time": 1667381172.093,
  "query": "{facility=\"archilogen\"}|=\"archilogen-warn\"",
  "status": "received",
  "created_at": 1667381172.093
}
```
6. Wait for the deletion request to be processed.
7. check whether logs were deleted either in Grafana or via `loki/api/v1/query_range` endpoint

**Expected behavior**
All logs matching the `{facility="archilogen"} |= "archilogen-warn"` query should be deleted.

**Environment:**
 - Infrastructure: Kubernetes, S3
 - Deployment tool: Kubernetes manifests, Initially generated via Helm and then modified.
 - Loki: `2.6.1`, Distributed deployment model, including various components. See the picture below.

**Screenshots, Configs, etc**
Loki Components:
image

Relevant Loki Config:
```
common:
  compactor_address: loki-distributed-compactor.loki.svc.cluster.local:3100

compactor:
  compaction_interval: 10m
  delete_request_cancel_period: 15m
  deletion_mode: filter-and-delete
  retention_delete_delay: 2h
  retention_enabled: true
  shared_store: s3

ingester:
  chunk_idle_period: 30m
  chunk_retain_period: 1m

query_range:
  cache_results: true
  results_cache:
    cache:
       enable_fifocache: false
       memcached_client:
         addresses: dns+loki-distributed-memcached-frontend.loki.svc.cluster.local:11211

storage_config:
  boltdb_shipper:
     cache_ttl: 24h
     shared_store: s3
```
Relevant Loki Runtime Config:
```
overrides:
  main:
     allow_deletes: true
```
Relevant Loki Gateway Config:
```
location = /loki/api/v1/delete {
    set $loki_api_v1_delete_backend http://loki-distributed-compactor.loki.svc.cluster.local;
    proxy_pass       $loki_api_v1_delete_backend:3100$request_uri;
    proxy_http_version 1.1;
}
```

I also created a [topic on Grafana Community](https://community.grafana.com/t/loki-log-deletion-with-line-filtering-not-working/75275)

### PR DESCRIPTION
**Pull request by sandeepsukhani**
**What this PR does / why we need it**:
It fixes the following issues:
* Whole chunks being deleted with a line filter were skipped.
* Chunks partially covered by delete requests with a line filter were not properly processed. The part that **was not covered** by the delete request was rewritten with a line filter, while the part that **was covered** by the delete request was completely deleted.

The issue went unnoticed because it seems we continue to do query time filtering of data even after the delete requests are processed.

**Which issue(s) this PR fixes**:
Fixes #7590 

**Special notes for your reviewer**:
If multiple delete requests with a line filter touch the same chunk, then I am considering just the first request that marks it for deletion to keep this PR simple. I have left a to-do to see if we can make it work efficiently.

**Checklist**
- [x] Tests updated
- [x] `CHANGELOG.md` updated

### CODE REVIEW

File: pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager.go [hunk 1]
```diff
@@ -279,7 +290,7 @@ func (d *DeleteRequestsManager) Expired(ref retention.ChunkEntry, _ model.Time)
 		}
 	}
 
-	if len(d.chunkIntervalsToRetain) == 1 && d.chunkIntervalsToRetain[0].Interval.Start == ref.From && d.chunkIntervalsToRetain[0].Interval.End == ref.Through {
```
Comment (sandeepsukhani) [inline pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager.go:282]: This check here was causing us to skip whole chunks covered by delete requests with line filters

File: pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager.go [hunk 2]
```diff
@@ -23,7 +23,7 @@ const (
 )
 
 type userDeleteRequests struct {
-	requests []DeleteRequest
+	requests []*DeleteRequest
```
Comment (MasslessParticle) [inline pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager.go:26]: Why is a pointer preferable?

File: pkg/storage/stores/indexshipper/compactor/deletion/delete_request.go [hunk 3]
```diff
@@ -133,23 +139,47 @@ func (d *DeleteRequest) IsDeleted(entry retention.ChunkEntry) (bool, []retention
...
+		// Add the deleted part with Filter func
+		if ff != nil {
+			intervals = append(intervals, retention.IntervalFilter{
+				Interval: model.Interval{
+					Start: d.StartTime,
+					End:   entry.Through,
+				},
+				Filter: ff,
+			})
+		}
```
Comment (sandeepsukhani) [inline pkg/storage/stores/indexshipper/compactor/deletion/delete_request.go:153]: Delete request with a line filter that partially covers a chunk should have the deleted interval with a line filter.

File: pkg/storage/stores/indexshipper/compactor/deletion/delete_request.go [hunk 4]
```diff
@@ -133,23 +139,47 @@ func (d *DeleteRequest) IsDeleted(entry retention.ChunkEntry) (bool, []retention
...
+
+		// Add non-deleted part without Filter func
 		intervals = append(intervals, retention.IntervalFilter{
 			Interval: model.Interval{
 				Start: entry.From,
 				End:   d.StartTime - 1,
 			},
-			Filter: ff,
```
Comment (sandeepsukhani) [inline pkg/storage/stores/indexshipper/compactor/deletion/delete_request.go:142]: and the non-deleted part without a line filter

**Review by MasslessParticle — APPROVED** [review]
I have a small question but this looks good. Good catch

File: pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager.go (hunk 2 above)
Comment (sandeepsukhani) [reply pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager.go:26]: because we are losing updates due to working on different copies; for example, we are always printing 0 lines deleted even when we have incremented it here https://github.com/grafana/loki/blob/c3e12d76a0144ba9d060bb972e070b000789fb81/pkg/storage/stores/indexshipper/compactor/deletion/delete_request.go#L72
