### PR TITLE
Fix panic in tailer when an ingester is removed from the ring while tailing

### LINKED ISSUE #845: Panic in tailing code
Stumble on this today

```
/go/src/github.com/grafana/loki/pkg/querier/tail.go:193 +0x295
created by github.com/grafana/loki/pkg/querier.(*Tailer).checkIngesterConnections	
/go/src/github.com/grafana/loki/pkg/querier/tail.go:219 +0xa8
github.com/grafana/loki/pkg/querier.(*Tailer).readTailClient(0xc020d72000, 0xc000504840, 0x10, 0x0, 0x0)
goroutine 95605 [running]:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x105e078]
panic: runtime error: invalid memory address or nil pointer dereference
```

We should make sure this doesn't happen. Might be already fixed.

/cc @sandlis

### PR DESCRIPTION
**Pull request by pracucci**
**What this PR does / why we need it**:

If an ingester is removed from the ring while tailing, `tailDisconnectedIngesters()` returns the tail clients map containing the removed ingester with `nil` value, causing a panic.

**Which issue(s) this PR fixes**:
Fixes #845

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: pkg/querier/querier.go [hunk 1]
```diff
@@ -321,34 +321,43 @@ func (q *Querier) Tail(ctx context.Context, req *logproto.TailRequest) (*Tailer,
...
-		tailClients[connectedIngestersAddr[i]] = nil
+	// Build a map to easily check if an ingester address is already connected
+	connectedIngestersAddrs := make(map[string]bool)
+	for _, addr := range connectedIngestersAddr {
+		connectedIngestersAddrs[addr] = true
 	}
 
-	disconnectedIngesters := []ring.IngesterDesc{}
+	// Get the current replication set from the ring
 	replicationSet, err := q.ring.GetAll()
```
Comment (rfratto) [inline pkg/querier/querier.go]: `GetAll` returns all ingesters inside the ring that are either `ACTIVE` or `LEAVING`, but in this case we only want the `ACTIVE` ones; could you filter the list?

example:
 ```
// filterLiveIngesters returns a copy of a replication set where the set of ingesters
// only containers ingesters that are ACTIVE and not LEAVING
func filterLiveIngesters(rs ring.ReplicationSet) ring.ReplicationSet {
	ingesters := make([]ring.IngesterDesc, 0, len(rs.Ingesters))
	for _, ingester := range rs.Ingesters {
		if ingester.State != ring.ACTIVE {
			continue
		}
		ingesters = append(ingesters, ingester)
	}
	return ring.ReplicationSet{Ingesters: ingesters, MaxErrors: rs.MaxErrors}
}
```

Not filtering the list doesn't cause any crashes, but it will continuously get removed from the `connectedIngestersAddr` list until it finally leaves and clutters up the logs with `Ingester is stopping` messages..

File: pkg/querier/querier.go [hunk 2]
```diff
@@ -321,34 +321,43 @@ func (q *Querier) Tail(ctx context.Context, req *logproto.TailRequest) (*Tailer,
 
 // passed to tailer for (re)connecting to new or disconnected ingesters
 func (q *Querier) tailDisconnectedIngesters(ctx context.Context, req *logproto.TailRequest, connectedIngestersAddr []string) (map[string]logproto.Querier_TailClient, error) {
-	tailClients := make(map[string]logproto.Querier_TailClient)
-	for i := range connectedIngestersAddr {
-		tailClients[connectedIngestersAddr[i]] = nil
+	// Build a map to easily check if an ingester address is already connected
+	connectedIngestersAddrs := make(map[string]bool)
```
Comment (rfratto) [inline pkg/querier/querier.go]: Could we change the name of this or of the argument? They're so similar that it's a bit hard to read.

File: pkg/querier/querier.go (hunk 1 above)
Comment (pracucci) [reply pkg/querier/querier.go]: Very good point. I agree. What's about `PENDING` and `JOINING` states? Should they be filtered out like `LEAVING`?

Comment (rfratto) [reply pkg/querier/querier.go]: I think `JOINING` should be filtered out too since they're not ready to accept traffic. `PENDING` is already filtered out. Here's the code that does the filtering from Cortex (in this instance, Operation will be Read):

https://github.com/grafana/loki/blob/79333add88f28be425acee607cdb6fa612e8b5a4/vendor/github.com/cortexproject/cortex/pkg/ring/replication_strategy.go#L49-L57

I think in this case the only state we want is ACTIVE.

Comment (pracucci) [reply pkg/querier/querier.go]: _In the meanwhile, I've filtered out ingesters in the `LEAVING` state ([70b419a](https://github.com/grafana/loki/pull/897/commits/70b419ae9b264184a74f95967a1b2e5a61d5a6c7))._

**Comment by pracucci** [comment]
@rfratto May you re-review the PR, please? Comments should have been addressed 🙏
