### PR TITLE
[RFR] fix vector() function produces wrong timestamp on instant query

### LINKED ISSUE #8240: vector() function produces wrong timestamp on remote write
**Describe the bug**
If `vector()` function is used to produce a default value for extracted metrics from logs, it's being sent to prometheus using `remote write` with **bad** timestamp. Related to https://github.com/grafana/loki/issues/6946

The major issue it brings, is that Prometheus fully stops accepting any new metrics after this event. The only way to resume Prometheus operations is to stop and completely clear TSDB.

**To Reproduce**
1. Started Loki 2.7.1 with the following config snippet for `ruler`
```
ruler:
  storage:
    type: local
    local:
      directory: /rules
  wal:
    dir: /loki/rules-wal
  rule_path: /tmp/rules
  enable_api: true
  remote_write:
    enabled: true
    client:
      url: http://prometheus.my.internal/api/v1/write

```
2. Started Promtail 2.7.1
3. Started Prometheus with remote write option enabled.
4. Rule: 
    ```logql
    groups: 
    - name: Traefik
      interval: 1m
     rules:
     - record: traefic_count
       expr: |
         sum(count_over_time({namespace="traefik"}[5m]))
         or
         vector(0)
    ```
**Expected behavior**
Exported metrics to prometheus endpoint using `remote write` should use correct timestamp.

**Environment:**
 - Infrastructure: bare-metal with docker
 - Deployment tool: ansible

**Screenshots, Promtail config, or terminal output**
Screenshot 2023-01-23 at 12 37 08

### PR DESCRIPTION
**Pull request by liguozhong**
**What this PR does / why we need it**:
fix vector() function produces wrong timestamp on instant query
**Which issue(s) this PR fixes**:
Fixes #8240

**Special notes for your reviewer**:
**error snapshot**
error timestamp in grafana 7.x
image
error timestamp in grafana 9.x
image

**with this PR**
fix logql:
` vector(5)
`image

with this PR
fix logql:
```
sum(count_over_time({namespace="traefik"}[5m]))
     or
     vector(5)
```
image

**Checklist**
- [x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [x] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

File: pkg/logql/engine.go [hunk 1]
```diff
@@ -426,7 +426,10 @@ func (q *query) evalVector(_ context.Context, expr *syntax.VectorExpr) (promql_p
 	}
 
 	if GetRangeType(q.params) == InstantType {
-		return s, nil
+		return promql.Vector{promql.Sample{
+			Point:  promql.Point{T: q.params.Start().UnixNano() / int64(time.Millisecond), V: value},
```
Comment (chaudum) [inline pkg/logql/engine.go:430]: Instead of `t.UnixNano()/int64(time.Millisecond)` we should use `t.UnixMilli()`

From the docs:

> // UnixMilli returns t as a Unix time, the number of milliseconds elapsed since
> // January 1, 1970 UTC. The result is undefined if the Unix time in
> // milliseconds cannot be represented by an int64 (a date more than 292 million
> // years before or after 1970). The result does not depend on the
> // location associated with t.

File: pkg/logql/evaluator.go [hunk 2]
```diff
@@ -232,7 +232,7 @@ func (ev *DefaultEvaluator) StepEvaluator(
 		if err != nil {
 			return nil, err
 		}
-		return newVectorIterator(val, q.Step().Nanoseconds(), q.Start().UnixNano(), q.End().UnixNano()), nil
+		return newVectorIterator(val, q.Step().Milliseconds(), q.Start().UnixNano()/int64(time.Millisecond), q.End().UnixNano()/int64(time.Millisecond)), nil
```
Comment (chaudum) [inline pkg/logql/evaluator.go:235]: Same as above.

**Review by chaudum — COMMENTED** [review]
Otherwise lgtm. Thanks for the fix!

File: pkg/logql/engine.go (hunk 1 above)
Comment (liguozhong) [reply pkg/logql/engine.go]: done.thanks👍

File: pkg/logql/evaluator.go (hunk 2 above)
Comment (liguozhong) [reply pkg/logql/evaluator.go]: ok

**Review by chaudum — APPROVED** [review]
LGMT. Maybe a second pair of eyes from someone with a bit more experience with the LogQL engine would be good.

**Comment by liguozhong** [comment]
thanks！

**Review by dannykopping — APPROVED** [review]
LGTM!
