### PR TITLE
storage: fix missing logs with batched chunk iterator

### LINKED ISSUE #1187: Logs disappear after the chunks were removed from memory
**Describe the bug**
Logs that have been ingested disappear after the chunks were removed from the
ingesters' memory. Before the chunks are flushed and removed, all of the logs
are queryable via `logcli` and Grafana.

Reproduced with commit hash [`fa79c2469c59c90cfb8e0415b0998665d5db2601`](https://github.com/grafana/loki/tree/fa79c2469c59c90cfb8e0415b0998665d5db2601)
in single process mode, but also happened in microservice mode with S3-DynamoDB
and Cassandra-Cassandra index-chunk storage.

**To Reproduce**
1. Started Loki (`fa79c24`)
2. Started Promtail (`fa79c24`) to tail [`random2.txt`](https://pastebin.com/1xmdC6DN)
3. Query with logcli: `{filename!=""}`, there are 450 log lines as expected
4. Wait until the `loki_ingester_memory_chunks` metric dropped to 0
5. Query with logcli: `{filename!=""}`, there are less than 450 log lines. The remaining log lines are [here](https://pastebin.com/bLzq6jBr).

**Expected behavior**
The number of logs returned after the chunks are removed from memory to be equal
with when the logs haven't been flushed yet.

**Environment:**
 - Infrastructure:
    - `Linux 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
    - `go version go1.13.3 linux/amd64`

 - Deployment tool: single process mode

**Screenshots, Promtail config, or terminal output**

logcli outputs:
```console
$ date; logcli --addr=http://localhost:3100 query '{filename!=""}' --limit 1000 | wc -l
Mon 21 Oct 18:10:59 WIB 2019
http://localhost:3100/loki/api/v1/query_range?direction=BACKWARD&end=1571656259418474786&limit=1000&query=%7Bfilename%21%3D%22%22%7D&start=1571652659418474786
Common labels: {filename="/home/isattvika/workspace/personal/2019-10-01_centralized-logging/random2.log", kube_container="my-container", kube_namespace="my-service", kube_replicaset="my-service-569d4f4f85"}
450

$ date; logcli --addr=http://localhost:3100 query '{filename!=""}' --limit 1000 | wc -l
Mon 21 Oct 18:13:22 WIB 2019
http://localhost:3100/loki/api/v1/query_range?direction=BACKWARD&end=1571656402404992865&limit=1000&query=%7Bfilename%21%3D%22%22%7D&start=1571652802404992865
Common labels: {filename="/home/isattvika/workspace/personal/2019-10-01_centralized-logging/random2.log", kube_container="my-container", kube_namespace="my-service", kube_replicaset="my-service-569d4f4f85"}
109
```

Loki configuration:
```yaml
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  max_transfer_retries: 1
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2019-10-01
    store: boltdb
    object_store: filesystem
    schema: v10
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: /tmp/loki/boltdb/index

  filesystem:
    directory: /tmp/loki/boltdb/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: false
  retention_period: 0
```

Promtail config:
```yaml
server:
  http_listen_port: 10080
  grpc_listen_port: 19095

clients:
  - url: http://localhost:3100/loki/api/v1/push

positions:
  filename: /home/isattvika/programs/promtail/positions.yml

scrape_configs:
  - job_name: testing

    static_configs:
      - targets:
          - localhost

        labels:
          __path__: /home/isattvika/workspace/personal/2019-10-01_centralized-logging/random2.log

    pipeline_stages:
      - json:
          expressions:
            message:
            timestamp:
            labels:

      - json:
          expressions:
            kube_container: container
            kube_pod: pod
            kube_replicaset: replicaset
            kube_namespace: namespace
            kube_node: node
          source: labels

      - labels:
          kube_container:
          kube_pod:
          kube_replicaset:
          kube_namespace:
          kube_node:

      - timestamp:
          source: timestamp
          format: 2006-01-02T15:04:05.000000Z

      - output:
          source: message
```

### PR DESCRIPTION
**Pull request by putrasattvika**
**What this PR does / why we need it**:
This PR addresses bugs that cause missing logs issue described in #1187:
  - Removed `__name__` label matcher for queries against the chunk storage. The `__name__` chunk label is removed from all chunks that are passed into `buildHeapIterator()`. Overlapping chunks (according to `batchSize`) will go through that function multiple times, and they will be filtered out on the second call since they no longer have the chunk label.
  - Reversed inclusivity of backward query iterators from `[from, through)` to `(from, through]`. This fixes an issue where the last log entry of the first chunk of a batch is not retrieved.
  - Fixed `from`/`through` for batched iterator with more than two batches

**Which issue(s) this PR fixes**:
Fixes #1187

**Checklist**
- [x] Tests updated

### CODE REVIEW

File: pkg/storage/iterator_test.go [hunk 1]
```diff
@@ -306,4 +554,18 @@ func Test_newBatchChunkIterator(t *testing.T) {
 		})
 	}
 
+	for name, tt := range tests {
+		tt := tt
+		t.Run(fmt.Sprintf("large-batchsize/%s", name), func(t *testing.T) {
+			it := newBatchChunkIterator(context.Background(), tt.chunks, 1000, newMatchers(tt.matchers), nil, newQuery("", tt.start, tt.end, tt.direction))
```
Comment (owen-d) [inline pkg/storage/iterator_test.go]: Could you explain the benefit of the large batchsize tests? Additionally, would it be better to use `len(tt.chunks)` instead of `1000` here for extensibility to ensure the the batch is always large enough to hold all the chunks?

File: pkg/storage/iterator.go [hunk 2]
```diff
@@ -77,6 +77,17 @@ type batchChunkIterator struct {
 
 // newBatchChunkIterator creates a new batch iterator with the given batchSize.
 func newBatchChunkIterator(ctx context.Context, chunks []*chunkenc.LazyChunk, batchSize int, matchers []*labels.Matcher, filter logql.Filter, req *logproto.QueryRequest) *batchChunkIterator {
+	// overlapping chunks (according to batchSize) will go through
+	// buildHeapIterator() multiple times. Because of that, we can't use the
+	// __name__ matcher since buildHeapIterator() will remove that label from the
+	// chunks that went through it.
```
Comment (owen-d) [inline pkg/storage/iterator.go]: Is splicing out the `__name__` label necessary? It appears that `buildHeapIterator` removes that label if present, which is an idempotent action. If this does need to stay, I'd be interested to know why and a test case which fails if this is removed would be helpful.

File: pkg/storage/iterator_test.go (hunk 1 above)
Comment (putrasattvika) [reply pkg/storage/iterator_test.go]: To be honest I don't know whether these tests are needed or not. I added these tests for debugging purposes since the bug described in #1187 don't happen when the batchsize is big enough to hold all of the chunks. I can remove those if deemed unnecessary.

File: pkg/storage/iterator.go (hunk 2 above)
Comment (putrasattvika) [reply pkg/storage/iterator.go]: > Is splicing out the __name__ label necessary? It appears that buildHeapIterator removes that label if present, which is an idempotent action.
It is required to remove the `__name__` label matcher as long as `buildHeapIterator` removes that label from the chunks. Chunks will be mutated by `buildHeapIterator`, but those mutated chunks might be re-evaluated if they overlap. Those mutated chunks then will be discarded by the iterators since they no longer match the `__name__` label matcher.

> If this does need to stay, I'd be interested to know why and a test case which fails if this is removed would be helpful.
Every test case with overlapping chunks should fail if this is removed. It seems I botched the test cases, though. I'll fix it in the next commit and you should be able to test it with:
```shell
GOGC=10 go test -mod=vendor -p=4 pkg/storage/iterator_test.go pkg/storage/util_test.go pkg/storage/iterator.go
```
When L84-L89 are commented out, all `*_with_overlap` tests should fail.

**Comment by owen-d** [comment]
Nice work @putrasattvika!
