### PR TITLE
Disable sharding of count/avg when labels are mutated

### LINKED ISSUE #5461: count() result is inaccurate
**Describe the bug**

When comparing the number of returned series from a query to the same query with `count()` wrapped around it the results are different.

The same `count` query sent directly to a querier and bypassing the query-frontend returns the correct result.

### PR DESCRIPTION
**Pull request by cyriltovena**
**What this PR does / why we need it**:

Counting distinct values cannot be sharded when mutating labels over multiple shards, since the same label can appears across multiple shard and will be counted twice.

Since avg() uses count then the same logic is applied for it too.

**Which issue(s) this PR fixes**:
Fixes #5461

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

File: pkg/logql/ast.go [hunk 1]
```diff
@@ -964,6 +962,18 @@ func (e *VectorAggregationExpr) String() string {
 
 // impl SampleExpr
 func (e *VectorAggregationExpr) Shardable() bool {
+	if e.Operation == OpTypeCount || e.Operation == OpTypeAvg {
```
Comment (owen-d) [inline pkg/logql/ast.go:965]: We really need a way to express operations that aren't `always` or `never` shardable, but shardable depending on how they're combined with other operations. This is a great start 👍.

**Review by owen-d — APPROVED** [review]
