### PR TITLE
Test & fix queries return multiple streams.

### LINKED ISSUE #323: Stream labels same of all streams
Probably related to #308?

### PR DESCRIPTION
**Pull request by tomwilkie**
[My advice](https://github.com/grafana/loki/pull/308#discussion_r255439688) to @woodsaj in #308 was completely bogo.  Whats more, when doing the multiple-entries-with-same-timestamp work, I conflated entries from different streams.  

This fixes and adds tests for them.  Fixes #323

Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

### CODE REVIEW

File: pkg/ingester/ingester_test.go [hunk 1]
```diff
@@ -45,10 +49,33 @@ func TestIngester(t *testing.T) {
...
+			Line:      fmt.Sprintf("line %d", i),
+		})
 	}
 
-	_, err = i.Push(user.InjectOrgID(context.Background(), "test"), &req)
+	ctx := user.InjectOrgID(context.Background(), "test")
+	_, err = i.Push(ctx, &req)
+	require.NoError(t, err)
+
+	fmt.Println("hehe")
```
Comment (woodsaj) [inline pkg/ingester/ingester_test.go]: i dont think we need this. :)
