### PR TITLE
Asynchronous Promtail stages

### LINKED ISSUE #74: Feature: multi-line logs
Currently when an multi-line event is written to a logfile promtail will take this as each row is its own entry and send the separately to loki. 

It would be great if Loki could handle multi-line events due to stacktraces.

This might also be a bug if promtail already should handle multi-lines.

### PR DESCRIPTION
**Pull request by cyriltovena**
This PR essentially changes promtail stages interface to uses channel, the idea is from @jeschkies based on https://blog.golang.org/pipelines .

The old interface was synchronous:

```golang
type Stage interface {
	Process(labels model.LabelSet, extracted map[string]interface{}, time *time.Time, entry *string)
	Name() string
}
```

Which means it was difficult to buffer/skip/duplicate entries before passing them down to another stages. For instance we were using a drop label that was interpreted by the pipeline to skip entries.

Now this is much simpler, the new interface uses two channels; one inbound and one outbound:

```golang
type Stage interface {
	Name() string
	Run(chan Entry) chan Entry
}
```

The pipeline will chain all channels together, in->out -> in -> out -> .... etc...

Unfortunately once you start going async, you have to go async bottom-up in the whole stack, this means promtail client interface has also changed from:

```golang
type Client interface {
  Handle(labels model.LabelSet,time time.Time,line string) err
  Stop()
}
```

to 

```golang
type Client interface {
  Chan() chan<- api.Entry
  Stop()
}
```

Now as you can imagine, we can wrap the Client chanel (sink) with the new pipeline to introduce mutation/buffering/deletion  and so on before sending them.

This means we will be able to move forward with #74 much more easily without hacking around the synchronous limitation, @jeschkies has a PR already in good shape that will be following.

**Special notes for your reviewer**:

Lot of channel and goroutine usage !

All tests are still the same, this is a Noop from the user point of view, I've backported all stages.

**Checklist**
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

File: pkg/logentry/stages/drop.go [hunk 1]
```diff
@@ -88,55 +88,71 @@ func newDropStage(logger log.Logger, config interface{}) (Stage, error) {
...
 }
 
-// Process implements Stage
-func (m *dropStage) Process(labels model.LabelSet, extracted map[string]interface{}, t *time.Time, entry *string) {
+func (m *dropStage) Run(in chan Entry) chan Entry {
+	out := make(chan Entry)
+	go func() {
+		defer close(out)
+		for e := range in {
+			if !m.shouldDrop(e) {
```
Comment (cyriltovena) [inline pkg/logentry/stages/drop.go:109]: No more weird drop label, we just don't send entries down to the outbound channel.

File: pkg/logentry/stages/stage.go [hunk 2]
```diff
@@ -27,19 +29,38 @@ const (
...
+		s.Process(e.Labels, e.Extracted, &e.Timestamp, &e.Line)
+		return e
+	})
+}
 
-// Process implements EntryHandler.
-func (s StageFunc) Process(labels model.LabelSet, extracted map[string]interface{}, time *time.Time, entry *string) {
-	s(labels, extracted, time, entry)
+func toStage(p Processor) Stage {
+	return &stageProcessor{Processor: p}
```
Comment (jeschkies) [inline pkg/logentry/stages/stage.go:63]: There is no way to implement `Stage` for `Processor` directly, right?

File: pkg/logentry/stages/timestamp_test.go [hunk 3]
```diff
@@ -455,9 +475,17 @@ func TestTimestampStage_ProcessActionOnFailure(t *testing.T) {
...
+				out := processEntries(s, Entry{
+					Extracted: extracted,
+					Entry: api.Entry{
+						Labels: inputEntry.labels,
+						Entry: logproto.Entry{
+							Line:      entry,
+							Timestamp: timestamp,
+						},
+					},
+				})[0]
```
Comment (jeschkies) [inline pkg/logentry/stages/timestamp_test.go:487]: The `Entry` construction spans all tests. Would it make sense to add a `NewEntry` method? This could ease groking the code.

File: pkg/promtail/api/types.go [hunk 4]
```diff
@@ -1,48 +1,91 @@
...
+func NewEntryHandler(entries chan<- Entry, stop func()) EntryHandler {
+	return entryHandler{
+		stop:    stop,
+		entries: entries,
+	}
+}
+
+// NewEntryMutatorHandler creates a EntryHandler that mutates incoming entries from another EntryHandler.
+func NewEntryMutatorHandler(next EntryHandler, f EntryMutatorFunc) EntryHandler {
+	out, wg, once := make(chan Entry), sync.WaitGroup{}, sync.Once{}
```
Comment (jeschkies) [inline pkg/promtail/api/types.go:68]: Maybe I misunderstand but `out` seems to be the input channel of the entry handler if I'm not mistaken.

File: pkg/promtail/client/client.go [hunk 5]
```diff
@@ -349,30 +340,17 @@ func (c *client) getTenantID(labels model.LabelSet) string {
 
 // Stop the client.
 func (c *client) Stop() {
-	c.once.Do(func() { close(c.quit) })
+	close(c.entries)
```
Comment (jeschkies) [inline pkg/promtail/client/client.go:343]: Is there a reason to drop `once`? Or are we considering it a bug if `Stop` is called multiple times?

File: pkg/promtail/client/logger.go [hunk 6]
```diff
@@ -51,22 +51,30 @@ func NewLogger(log log.Logger, externalLabels lokiflag.LabelSet, cfgs ...Config)
...
+	entries := make(chan api.Entry)
+	l := &logger{
+		Writer:  tabwriter.NewWriter(os.Stdout, 0, 8, 0, '\t', 0),
+		entries: entries,
+	}
+	go l.run()
+	return l, nil
 }
 
 func (*logger) Stop() {}
```
Comment (jeschkies) [inline pkg/promtail/client/logger.go:63]: Should this `close(l.entries)`?

**Review by jeschkies — COMMENTED** [review]
Thanks for this great effort.

Did you mean `The old interface was sync:` instead of `The old interface was async:` in the PR message?

File: pkg/logentry/stages/drop_test.go [hunk 7]
```diff
@@ -47,8 +50,8 @@ func Test_dropStage_Process(t *testing.T) {
 		config     *DropConfig
 		labels     model.LabelSet
 		extracted  map[string]interface{}
-		t          *time.Time
-		entry      *string
+		t          time.Time
+		entry      string
```
[the remark this answers is not in the document]
Comment (cyriltovena) [reply pkg/logentry/stages/drop_test.go:54]: Handle signature was `Handle(labels,*time,*string)` this was the only way to modify input without return. Bad choice were made, but it's over now :)

File: pkg/logentry/stages/stage.go (hunk 2 above)
Comment (cyriltovena) [reply pkg/logentry/stages/stage.go:63]: I haven't found a better way or a less verbose way.

**Comment by cyriltovena** [comment]
> Thanks for this great effort.
> 
> Did you mean `The old interface was sync:` instead of `The old interface was async:` in the PR message?

Yep sorry :)

File: pkg/logentry/stages/drop_test.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (jeschkies) [reply pkg/logentry/stages/drop_test.go:54]: Ah, thanks for explaining.

File: pkg/logentry/stages/stage.go (hunk 2 above)
Comment (jeschkies) [reply pkg/logentry/stages/stage.go:63]: I thought Golang would support `func (p *Processor) Run(...)` but I was wrong.

File: pkg/logentry/stages/stage.go [hunk 8]
```diff
@@ -27,19 +29,38 @@ const (
 	StageTypeDrop      = "drop"
 )
 
-// Stage takes an existing set of labels, timestamp and log entry and returns either a possibly mutated
+// Processor takes an existing set of labels, timestamp and log entry and returns either a possibly mutated
```
Comment (owen-d) [inline pkg/logentry/stages/stage.go:32]:
```suggestion
// Processor takes an existing set of labels, timestamp and log entry and possibly mutates the
```

File: pkg/promtail/client/client.go (hunk 5 above)
Comment (owen-d) [reply pkg/promtail/client/client.go:343]: I'd like to leave the once call in unless there's a distinct reason not to. I'd rather propagate an error than panic, although this may already be guaranteed due to how this is used, I'm not sure.

**Review by owen-d — APPROVED** [review]
I gave it a quick review but spent some extra time in the `api` and `stage` packages. I like this new approach and think it looks good. I'm curious to see how well the runtime handles the new work (more goroutines, etc) but I expect it'll be much better.

That being said, I don't spend a ton of time in these packages usually.

**Comment by cyriltovena** [comment]
> I gave it a quick review but spent some extra time in the `api` and `stage` packages. I like this new approach and think it looks good. I'm curious to see how well the runtime handles the new work (more goroutines, etc) but I expect it'll be much better.
> 
> 
> 
> That being said, I don't spend a ton of time in these packages usually. 

Thanks @owen-d I still need to address Karsten feedback before merging.

I also want to take it for a spin in dev.

File: cmd/docker-driver/loki.go [hunk 9]
```diff
@@ -60,7 +66,14 @@ func (l *loki) Log(m *logger.Message) error {
...
 		lbs["source"] = model.LabelValue(m.Source)
 	}
-	return l.handler.Handle(lbs, m.Timestamp, string(m.Line))
+	l.handler.Chan() <- api.Entry{
+		Labels: lbs,
+		Entry: logproto.Entry{
+			Timestamp: m.Timestamp,
+			Line:      string(m.Line),
+		},
+	}
```
[the remark this answers is not in the document]
Comment (cyriltovena) [reply cmd/docker-driver/loki.go:75]: Yeah we could but that's just making the interface wider, the benefits is not that huge.

File: pkg/promtail/client/client.go (hunk 5 above)
Comment (cyriltovena) [reply pkg/promtail/client/client.go:343]: yes let's keep the once.

File: pkg/promtail/api/types.go (hunk 4 above)
Comment (cyriltovena) [reply pkg/promtail/api/types.go:68]: yes bad name choice.

**Comment by cyriltovena** [comment]
Everything seems to run smoothly and CPU is lower than before 👍  Getting test to pass and I'll merge this.
