### PR TITLE
Fixes negative gauge in Promtail.

### LINKED ISSUE #3281: Negative numbers not extracted by promtail to a Gauge metric
**Describe the bug**
Negative numbers cannot be extracted as Gauge metrics from logs in promtail.

**To Reproduce**
promtail config:
```
     #<13>Jan 28 14:25:52 vehicule=1 longitude=-10.1234 latitude=15.1234
      - match:
          selector: '{host="whatever"}'
          stages:
            - regex:
                expression: 'vehicule=(?P<vehicule>\d+) longitude=(?P<longitude>[-]?\d+\.\d+) latitude=(?P<latitude>\d+\.\d+)'
            - labels:
                vehicule:
            - metrics:
                longitude:
                  type: Gauge
                  description: "longitude GPS vehicule"
                  config:
                    match_all: true
                    action: set
                latitude:
                  type: Gauge
                  description: "latitude GPS vehicule"
                  config:
                    match_all: true
                    action: set
```

**Expected behavior**
Numbers like -10.1234 should be extracted from log lines.

**Environment:**
 - linux Ubuntu 64bit
 - loki 2.1

**Screenshots, Promtail config, or terminal output**
logfmt in logql has not problem with negative numbers, but promtail cannot cast the extracted number as a signed float to a Gauge after regex extraction.

### PR DESCRIPTION
**Pull request by cyriltovena**
Fixes #3281

Signed-off-by: Cyril Tovena <cyril.tovena@gmail.com>

### CODE REVIEW

File: clients/pkg/logentry/stages/metrics.go [hunk 1]
```diff
@@ -201,7 +201,7 @@ func (m *metricStage) recordCounter(name string, counter *metric.Counters, label
 		counter.With(labels).Inc()
 	case metric.CounterAdd:
 		f, err := getFloat(v)
-		if err != nil || f < 0 {
```
Comment (dannykopping) [inline clients/pkg/logentry/stages/metrics.go:204]: That's weird; wonder why this was set. This one is for a counter - can we do a negative add in a counter? I'd assume so.

**Review by dannykopping — APPROVED** [review]

File: clients/pkg/logentry/stages/metrics.go (hunk 1 above)
Comment (cyriltovena) [reply clients/pkg/logentry/stages/metrics.go:204]: 🤷

**Review by sandeepsukhani — APPROVED** [review]
LGTM
