### PR TITLE
Fix promtail scrape config job name validation

### LINKED ISSUE #7275: Scape config `job_name` is used without sanitisation for metric name, causing panic
**Describe the bug**
When attempting to run promtail docker with loki_push_api configured as a scrape_config the docker crashes with the following errors

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000709860, {0xc0007098a0, 0x1, 0xc0000ee918})
 /src/loki/vendor/github.com/prometheus/client_golang/prometheus/registry.go:403 +0x7f
github.com/prometheus/client_golang/prometheus.MustRegister(...)
 /src/loki/vendor/github.com/prometheus/client_golang/prometheus/registry.go:178
github.com/weaveworks/common/server.New({{0xc0000ee918, 0x14}, {0x300c480, 0x3}, {0x0, 0x0}, 0xdac, 0x0, {0x300c480, 0x3}, ...})
 /src/loki/vendor/github.com/weaveworks/common/server/server.go:172 +0x20d
github.com/grafana/loki/clients/pkg/promtail/targets/lokipush.(*PushTarget).run(0xc0007dfec0)
 /src/loki/clients/pkg/promtail/targets/lokipush/pushtarget.go:96 +0x2b8
github.com/grafana/loki/clients/pkg/promtail/targets/lokipush.NewPushTarget({0x37cedc0, 0xc000108690}, {0x3802bf0, 0xc0007096a0}, {0x0, 0x0, 0x0}, {0xc0006a07d0, 0xb}, 0xc00081ec80)
 /src/loki/clients/pkg/promtail/targets/lokipush/pushtarget.go:76 +0x3f4
github.com/grafana/loki/clients/pkg/promtail/targets/lokipush.NewPushTargetManager({0x3805b20, 0xc000108aa0}, {0x37cedc0, 0xc000108690}, {0x7f52505e8048, 0xc0004b5fc0}, {0xc0007346c0, 0x445460, 0x1})
 /src/loki/clients/pkg/promtail/targets/lokipush/pushtargetmanager.go:47 +0x2ea
github.com/grafana/loki/clients/pkg/promtail/targets.NewTargetManagers({0x37cfc40, 0xc0007df080}, {0x3805b20, 0xc000108aa0}, {0x37cedc0, 0xc000108690}, {0x2540be400, {0xc0000ee7c8, 0x13}, 0x0, ...}, ...)
 /src/loki/clients/pkg/promtail/targets/manager.go:207 +0xf18
github.com/grafana/loki/clients/pkg/promtail.New({{{{0x0, 0x0}, {0x300c480, 0x3}, {0x0, 0x0}, 0x2378, 0x0, {0x300c480, 0x3}, ...}, ...}, ...}, ...)
 /src/loki/clients/pkg/promtail/promtail.go:84 +0x43e
main.main()
 /src/loki/clients/cmd/promtail/main.go:115 +0x61d
level=info ts=2022-09-28T07:15:52.266006699Z caller=pushtarget.go:85 msg="starting push server" job=central-log
panic: descriptor Desc{fqName: "promtail_central-log_tcp_connections", help: "Current number of accepted TCP connections.", constLabels: {}, variableLabels: [protocol]} is invalid: "promtail_central-log_tcp_connections" is not a valid metric name

Removing the loki_push_api scrape config section, promtail starts fine and pushes the other scrape config logs to loki.

I have also attempted to separate the promtails (1 for host logs and 1 for central) to confirm and issue still occurs.

**To Reproduce**
1. Start promtail docker with the following config file

server:
  http_listen_port: 9080
  grpc_listen_port: 0
        
positions:
  filename: /tmp/positions.yaml
        
clients:
  - url: https://xxxxx/loki/api/v1/push
    basic_auth: 
      username: xxxx
      password: xxxx
    external_labels:
     xxxx: "xxxxx"

scrape_configs:
- job_name: central-log
  loki_push_api:
    server:
      http_listen_port: 3500
      grpc_listen_port: 3600
    use_incoming_timestamp: true

**Expected behavior**
Promtail to start and accept logs from other promtail configurations on port 3500

**Environment:**
 - Infrastructure: Ubuntu 20.04.1 LTS
 - Deployment tool: docker compose

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

### PR DESCRIPTION
**Pull request by vijal-patel**
**What this PR does / why we need it**:
The current promtail scrapeConfig jobName validation only sanitizes empty spaces. If special characters are introduced it causes a panic. The implemented fix uses the label sanitzer in the strutil package.
 

**Which issue(s) this PR fixes**:
Fixes #7275

**Special notes for your reviewer**:
Not sure if I described things correctly in the PR title, I'm very new to Loki in general.
 
**Checklist**
- [x] Reviewed the `CONTRIBUTING.md` guide
- [ ] Documentation added
- [x] Tests updated
- [ ] `CHANGELOG.md` updated
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

File: clients/pkg/promtail/targets/lokipush/pushtargetmanager.go [hunk 1]
```diff
@@ -69,7 +69,7 @@ func validateJobName(scrapeConfigs []scrapeconfig.Config) error {
 		}
 		jobNames[cfg.JobName] = struct{}{}
 
-		scrapeConfigs[i].JobName = strings.Replace(cfg.JobName, " ", "_", -1)
+		scrapeConfigs[i].JobName = strutil.SanitizeLabelName(cfg.JobName);
```
Comment (dannykopping) [inline clients/pkg/promtail/targets/lokipush/pushtargetmanager.go:72]:
```suggestion
		scrapeConfigs[i].JobName = strutil.SanitizeLabelName(cfg.JobName)
```

**Review by dannykopping — COMMENTED** [review]
LGTM! One small nit

File: clients/pkg/promtail/targets/lokipush/pushtargetmanager.go (hunk 1 above)
Comment (vijal-patel) [reply clients/pkg/promtail/targets/lokipush/pushtargetmanager.go]: ah sorry, my IDE must've added that

**Review by dannykopping — APPROVED** [review]
Thanks for this @vijal-patel! Appreciate the use of the Prometheus library here to sanitise this correctly
