### PR TITLE
canary: Adds locking to prevent multiple concurrent invocations of `confirmMissing` from clobbering each other

### LINKED ISSUE #5128: Panic in canaries.
While checking on a cluster I found out a canary was panicking here is stack trace:

```
Connecting to loki at wss://../loki/api/v1/tail?query=%7Bstream%3D%22stdout%22%2Cpod%3D%22loki-canary-7c58648dc8-xwzdr%22%7D, querying for label 'pod' with value 'loki-canary-7c58648dc8-xwzdr'
error reading websocket, will retry in 10 seconds: websocket: close 1011 (internal server error): rpc error: code = Canceled desc = grpc: the client connection is closing
Connecting to loki at wss://l...t/loki/api/v1/tail?query=%7Bstream%3D%22stdout%22%2Cpod%3D%22loki-canary-7c58648dc8-xwzdr%22%7D, querying for label 'pod' with value 'loki-canary-7c58648dc8-xwzdr'
	/src/loki/pkg/canary/comparator/comparator.go:414 +0x3a5
created by github.com/grafana/loki/pkg/canary/comparator.(*Comparator).pruneEntries
	/src/loki/pkg/canary/comparator/comparator.go:446 +0x27d
github.com/grafana/loki/pkg/canary/comparator.(*Comparator).confirmMissing(0xc000230160, {0xc00055f0e0, 0xc00055f0e0, 0x1182f00})
goroutine 1661 [running]:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa4209d]
panic: runtime error: invalid memory address or nil pointer dereference
```

### PR DESCRIPTION
**Pull request by afayngelerindbx**
**What this PR does / why we need it**:
nil pointer dereferences in this code are causing panics in our deployment. It seems that confirmMissing wasn't intended to be run concurrently. The locking in this PR prevents accessing `missingEntries` while it is also being set to slice of nils(comparator.go:L482).

**Which issue(s) this PR fixes**:
Fixes #5128

### CODE REVIEW

**Review by chaudum — COMMENTED** [review]
Generally, lgtm. Could we get this covered with a test, e.g. calling `confirmMissing` concurrently when also calling `pruneEntries`?

**Review by kavirajk — COMMENTED** [review]
LGTM 👍 Thanks @afayngelerindbx.

Agree with @chaudum, can you please add a test? I will merge after that.

**Comment by afayngelerindbx** [comment]
It's pretty tricky to actually ensure that these tests run with the right sequencing to cause all the panics. Let me know if the test needs to be something smarter.  Also, do I need to add anything to the CHANGELOG? This seems like too small a change for that.

**Comment by kavirajk** [comment]
@afayngelerindbx. It can be simple test that locks this behavior :)

And for CHANGELOG. I don't think we need entry there as this is not user-visible change :)

**Comment by afayngelerindbx** [comment]
I added a fairly simple test that accomplishes two things: 
1) With my comparator.go changes removed, it panics fairly consistently. Sometimes, it even causes the exact panic in the attached issue. With the locking added back in the test passes consistently.
2) With locking removed, the race detector(`go test -race`), shows racy data access for the new test. Once locking is added, the races are resolved.

Please, let me know whether you think this is sufficient test coverage for this change.

File: pkg/canary/comparator/comparator_test.go [hunk 1]
```diff
@@ -218,6 +218,33 @@ func TestEntryNeverReceived(t *testing.T) {
...
+	maxWait := 30 * time.Millisecond
+
+	c := NewComparator(output, wait, maxWait, 50*time.Hour, 15*time.Minute, 4*time.Hour, 4*time.Hour, 0, 1*time.Minute, 0, 0, 1, make(chan time.Time), make(chan time.Time), mr, false)
+
+	for _, t := range found {
+		c.missingEntries = append(c.missingEntries, &t)
+	}
+
+	for i := 0; i < 10; i++ {
+		go func() {
```
Comment (kavirajk) [inline pkg/canary/comparator/comparator_test.go:242]: better to add `sync.WaitGroup` to makesure all goroutines are completed by end of the test?

**Comment by kavirajk** [comment]
thanks @afayngelerindbx looks good. Just added one minor suggestion to add waitGroup to the test.

Also looks like `license/cla` pending. Can you sign it? Then I will merge :)

File: pkg/canary/comparator/comparator_test.go (hunk 1 above)
Comment (afayngelerindbx) [reply pkg/canary/comparator/comparator_test.go:242]: good suggestion. adding

**Comment by afayngelerindbx** [comment]
> thanks @afayngelerindbx looks good. Just added one minor suggestion to add waitGroup to the test.
> 
> Also looks like `license/cla` pending. Can you sign it? Then I will merge :)

I *think* I  signed. The CLA bot comment says so as well: https://github.com/grafana/loki/pull/5568#issuecomment-1061333145 I'm not sure why the check isn't passing. Any suggestions?

File: pkg/canary/comparator/comparator_test.go (hunk 1 above)
Comment (kavirajk) [reply pkg/canary/comparator/comparator_test.go:244]: Thanks for adding :)

1. can we make `wg.Done()` as `defer wg.Done()` at the beginning before `assert.NotPanic` is getting called? Because that way we can make sure `wg.Done()` is run even if that code panics.
2. Not familiar with `assert.Eventually`. But shouldn't just simple `wg.Wait()` after the for loop is sufficient here? Not sure if I miss anything there.

Comment (afayngelerindbx) [reply pkg/canary/comparator/comparator_test.go:244]: I believe `assert.NotPanic` recovers from the panic and returns false. Adding the defer to make the code easier to reason about.

For 2, I would recommend keeping `Eventually` there. The expectation is that this test should return fairly quickly(within 1s) keeping a `wg.Done()` at the end will make the test suite time out(default 10m) if one of those goroutines hits a deadlock.

File: pkg/canary/comparator/comparator_test.go [hunk 2]
```diff
@@ -218,6 +218,45 @@ func TestEntryNeverReceived(t *testing.T) {
...
+
+	output := &bytes.Buffer{}
+
+	wait := 30 * time.Millisecond
+	maxWait := 30 * time.Millisecond
+
+	c := NewComparator(output, wait, maxWait, 50*time.Hour, 15*time.Minute, 4*time.Hour, 4*time.Hour, 0, 1*time.Minute, 0, 0, 1, make(chan time.Time), make(chan time.Time), mr, false)
+
+	for _, t := range found {
+		c.missingEntries = append(c.missingEntries, &t)
```
Comment (chaudum) [inline pkg/canary/comparator/comparator_test.go:238]: All items in the `missingEntries` slice will point to the same `time.Time` object, because `t` inside the range loop is reused for each iteration.

For this test it's irrelevant, but I guess it was not intended.

```suggestion
		tCopy := t
		c.missingEntries = append(c.missingEntries, &tCopy)
```

See https://go.dev/ref/spec#For_statements and https://stackoverflow.com/questions/48826460/using-pointers-in-a-for-loop

**Review by chaudum — COMMENTED** [review]
Minor thing regarding the usage of the pointer inside a range loop.

File: pkg/canary/comparator/comparator_test.go (hunk 2 above)
Comment (afayngelerindbx) [reply pkg/canary/comparator/comparator_test.go:238]: Ah good catch. This gets me in golang all the time.

**Review by chaudum — APPROVED** [review]

**Review by kavirajk — APPROVED** [review]
