### PR TITLE
promtail: Fix issue with dropping logs when a file based SD target's labels are updated

### LINKED ISSUE #7001: Promtail: Log scraping stops when changing label value for existing target in file_sd_config
When a file-based SD target is updated with a new label and the updated target shares the same filename, all scraping of this target stops until promtail is restarted.

**To Reproduce**
Promtail is actively tailing the file described in the file_sd_config below:
```
{
  "targets": [
    "localhost"
  ],
  "labels": {
    "__path__": "/var/log/0.log",
    "app": "web",
    "package_id": "1",
  }
}
```
Then, the package_id label is changed from `1` to `2` by rewriting the file_sd_config with the new label, like:
```
{
  "targets": [
    "localhost"
  ],
  "labels": {
    "__path__": "/var/log/0.log",
    "app": "web",
    "package_id": "2",
  }
}
```

All subsequent logs are dropped until promtail is restarted.

**Expected behavior**
It would be very helpful to be able to update file based SD labels and having scraping continue without a restart. I can accept a short amount of time where outdated labels are being applied to the newer logs.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: custom
 - Promtail version:
 ```
promtail, version main-d6f50ca (branch: main, revision: d6f50ca5e)
  build user:       root@4c4d203c7175
  build date:       2022-06-16T15:44:00Z
  go version:       go1.17.9
  platform:         linux/amd64
```

**Screenshots, Promtail config, or terminal output**
The race condition can be observed here where the target remove occurs within a millisecond later of the target being added. (Newer logs on top) 
```
2022-08-29 19:33:04	
level=info ts=2022-08-29T19:33:04.384548861Z caller=filetargetmanager.go:358 msg="Removing target" key="/var/log/0.log:{app=\"web\", package_id=\"1\", task_name=\"loki_compactor\"}"
2022-08-29 19:33:04	
level=info ts=2022-08-29T19:33:04.384460071Z caller=filetargetmanager.go:335 msg="Adding target" key="/var/log/0.log:{app=\"web\", package_id=\"2\", task_name=\"loki_compactor\"}"
```

### PR DESCRIPTION
**Pull request by chodges15**
**What this PR does / why we need it**:
Allows for modifying labels for a target and continuing to scrape logs afterwards.

**Which issue(s) this PR fixes**:
Fixes #7001 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated
- [x] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

File: clients/pkg/promtail/targets/file/filetargetmanager.go [hunk 1]
```diff
@@ -273,6 +272,25 @@ func (s *targetSyncer) sync(groups []*targetgroup.Group, targetEventHandler chan
 	targets := map[string]struct{}{}
 	dropped := []target.Target{}
 
+	// process target removal first to avoid cleaning up fileEventWatchers that are needed by a new or modified target
+	for key, target := range s.targets {
+		if _, ok := targets[key]; !ok {
```
Comment (chodges15) [inline clients/pkg/promtail/targets/file/filetargetmanager.go:277]: this will never evaluate to OK since targets above is empty, I need to rework this before it is ready for review

**Comment by chodges15** [comment]
this is ready for review now

**Comment by MasslessParticle** [comment]
Thanks for submitting a PR!

I've made some suggestions but this looks reasonable.

Out of curiosity, when would a target's labels be changed while reading?

**Comment by afayngelerindbx** [comment]
> I've made some suggestions but this looks reasonable.

Hi @MasslessParticle I don't see the suggestions you mentioned above. Is there something I need to do to see them?

**Comment by MasslessParticle** [comment]
Sorry about that, @afayngelerindbx! I didn't click the `submit` button 🤦

**Comment by afayngelerindbx** [comment]
> Sorry about that, @afayngelerindbx! I didn't click the `submit` button 🤦

No worries. Happens to me *all the time*

File: clients/pkg/promtail/targets/file/filetargetmanager.go [hunk 2]
```diff
@@ -373,7 +395,6 @@ func (s *targetSyncer) sync(groups []*targetgroup.Group, targetEventHandler chan
 			}
 		}
 	}
-	s.droppedTargets = dropped
```
Comment (cstyan) [inline clients/pkg/promtail/targets/file/filetargetmanager.go:376]: moving this line doesn't seem necessary to change the behaviour of keeping or removing a file watcher, so lets not move it in this PR

File: clients/pkg/promtail/targets/file/filetargetmanager.go [hunk 3]
```diff
@@ -356,15 +355,38 @@ func (s *targetSyncer) sync(groups []*targetgroup.Group, targetEventHandler chan
 		}
 	}
 
+	s.droppedTargets = dropped
+
+	// keep track of how many targets are using a fileEventWatcher
+	watcherUseCount := make(map[string]int, len(s.fileEventWatchers))
+	for _, target := range s.targets {
```
Comment (cstyan) [inline clients/pkg/promtail/targets/file/filetargetmanager.go:362]: we could simplify/remove the need for this extra loop on every `sync` call by storing the `watcherUseCount` as a field in the `targetSyncer` struct

**Review by cstyan — COMMENTED** [review]
Minor comments; along with Travis' comments there's another opportunity to simplify things.

Reviewing this PR also makes me think it would be worth it to break the logic within `sync` into multiple functions.

**Review by owen-d — APPROVED** [review]
I'm going to approve this. There's some feedback around style/code construction, but the idea LGTM. Feel free to address those, but I'd like to merge this soon.

Thanks and sorry for the late review.
