### PR TITLE
pkg/ingester: handle labels mapping to the same fast fingerprint.

### LINKED ISSUE #898: Out-of-order errors with log streams from multiple services despite unique labels
**Describe the bug**
We are getting some "400 entry out of order for stream" -errors in our multiple-sending-hosts, multiple-sending-processes setup despite every host-process combination having unique labels.

According to [this comment](https://github.com/grafana/loki/issues/168#issuecomment-465665648), we should be able to have multiple parallel log streams getting pushed into Loki as long as the labels for these streams differ.

Our setup currently consists of

1. [Fluent Bit agents](https://fluentbit.io/) on our servers, forwarding logs to a load balancer
2. the load balancer forwarding the logs to two [Fluentd](https://www.fluentd.org/) instances
3. each Fluentd instance using two threads to process the logs and forward them to Loki using fluent-plugin-grafana-loki

In each log, we include both the hostname of the Fluentd instance and the thread ID as labels. Therefore, each parallel stream should have unique labels, and out-of-order errors shouldn't happen. That is not the case, though - we do get out-of-order errors when we use two hosts with two threads each. The errors don't happen for some strange reason, however, when using only one host with two threads (e.g. when skipping the load balancing).

As building a setup as complex as ours for reproducing this isn't feasible, I wrote a script that manages to reproduce a similar scenario locally. It uses just pure protobufs to send logs to `/api/prom/push`, so this doesn't seem to be a Fluentd/Fluentd plugin problem. See the chapter below for reproduction instructions.

**To Reproduce**
1. Start the loki/production stack with docker-compose (loki version: master-78c6aa49, the other parts of the stack are not used and not relevant)
2. Run the lokitoy script, found at https://github.com/laitalaj/lokitoy , according to the instructions in [the README](https://github.com/laitalaj/lokitoy/blob/master/README.md)
3. Notice the errors in loki logs and in the script output

**Expected behavior**
The script makes sure that each parallel logging process sends it's log stream in order, and that the log streams from each process have unique label sets. According to [this comment](https://github.com/grafana/loki/issues/168#issuecomment-465665648), there should not be any out-of-order errors in this case.

**Environment:**
 - Production: Fluentd with Loki plugin, forwarding to a Loki running on Docker in a cloud hosting service
 - Local reproduction: Python script sending mock logs to a Loki running on Docker in localhost

**Screenshots, promtail config, or terminal output**
Some error lines from the loki logs:
```
loki_1      | level=warn ts=2019-08-15T08:16:09.0429259Z caller=grpc_logging.go:37 method=/logproto.Pusher/Push duration=659.1µs err="rpc error: code = Code(400) desc = entry out of order for stream: {app=\"m\", uniq0=\"0\", uniq1=\"0\"}" msg="gRPC\n"
loki_1      | level=warn ts=2019-08-15T08:16:10.5270068Z caller=grpc_logging.go:37 duration=289.4µs method=/logproto.Pusher/Push err="rpc error: code = Code(400) desc = entry out of order for stream: {app=\"l\", uniq0=\"1\", uniq1=\"1\"}" msg="gRPC\n"
```

**Some findings**
I've poked around a bit with the lokitoy script, and catalogued some behavior in https://github.com/laitalaj/lokitoy#some-findings

### PR DESCRIPTION
**Pull request by pstibrany**
**What this PR does / why we need it**:
This PR fixes problem in ingester with labels mapped to the same fast fingerprint, which then causes out of order errors.

**Which issue(s) this PR fixes**:
Fixes #898

**Special notes for your reviewer**:
Uses slightly adapted fpMapper code from Cortex.

Instead of using `[]client.LabelAdapter`, this PR changes it to `labels.Labels` in ingester stream. It also avoids conversion via `client.FromLabelAdaptersToLabels` (which breaks contract of `labels.Labels` because it doesn't check for input being sorted. https://github.com/cortexproject/cortex/issues/1813) Note that fpMapper code relies on `labels.Labels` being sorted in the equality check.

This PR doesn't change similar problem present in promtail Client.

**Checklist**
- [x] Documentation added (there is no documentation change for this)
- [x] Tests updated

### CODE REVIEW

File: pkg/ingester/instance.go [hunk 1]
```diff
@@ -156,6 +162,15 @@ func (i *instance) getOrCreateStream(labels []client.LabelAdapter) (*stream, err
 	return stream, nil
 }
 
+// Return labels associated with given fingerprint. Used by fingerprint mapper. Must hold streamsMtx.
+func (i *instance) getLabelsFromFingerprint(fp model.Fingerprint) labels.Labels {
```
Comment (cyriltovena) [inline pkg/ingester/instance.go]: you're not holding the streamMtx ? is that a problem ?

Comment (cyriltovena) [reply pkg/ingester/instance.go]: we might not see the race because:
1) -race is off
2) the current unit test is synchronous.

I think you can improve the test below to run two push async and run manually the test with -race to verify we're good to go.

File: pkg/ingester/instance_test.go [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+func TestLabelsCollisions(t *testing.T) {
+	o, err := validation.NewOverrides(validation.Limits{MaxStreamsPerUser: 1000})
+	require.NoError(t, err)
+
+	i := newInstance("test", 512, o)
+
+	tt := time.Now().Add(-5 * time.Minute)
+
+	// Notice how labels aren't sorted.
+	err = i.Push(context.Background(), &logproto.PushRequest{Streams: []*logproto.Stream{
```
Comment (cyriltovena) [inline pkg/ingester/instance_test.go]: here 2 push in different goroutines, will also help catch race condition.

File: pkg/ingester/instance.go (hunk 1 above)
Comment (cyriltovena) [reply pkg/ingester/instance.go]: I think I see why it is not a problem. Because line 89 takes the lock. 

I think it would still be useful to make the new test async (double push), so we can confirm everything is fine race wise.

File: pkg/ingester/stream.go [hunk 3]
```diff
@@ -8,7 +8,10 @@ import (
 	"sync"
 	"time"
 
-	"github.com/cortexproject/cortex/pkg/ingester/client"
+	"github.com/cortexproject/cortex/pkg/util"
+
```
Comment (cyriltovena) [inline pkg/ingester/stream.go]: can you pack everything please ?

File: pkg/ingester/instance.go (hunk 1 above)
Comment (pstibrany) [reply pkg/ingester/instance.go]: > I think I see why it is not a problem. Because line 89 takes the lock.

Exactly, line 89 and line 114. I'll make concurrent test. getLAbelsFromFingerprint is only used indirectly when calling `i.mapper.mapFP`, it's responsibility of caller of this method to hold the locks.

I will add the test and try to improve the documentation.

There is one more ugly place: mapper.go:81... it holds no lock inside the mapper, and relies on outside lock to update per-fingerprint map. This is directly from cortex, which uses locks per fingerprint. In Loki we use single global lock (streamMtx) so it is still fine, but not very clear.

File: pkg/ingester/stream.go (hunk 3 above)
Comment (pstibrany) [reply pkg/ingester/stream.go]: I leave imports formatting to Goland and goimports, so I'll try, but I won't fight them if they decide otherwise.

**Comment by pstibrany** [comment]
I've added slightly bigger test for concurrent pushes. Perhaps it can be used as basis for benchmark. I think that global (per-user) `i.streamsMtx` isn't helping much with concurrency. Something to improve in the future.

File: pkg/ingester/instance_test.go (hunk 2 above)
Comment (pstibrany) [reply pkg/ingester/instance_test.go]: Added another test for testing concurrent pushes.

**Comment by pstibrany** [comment]
@sandlis pointed out issue with this code... it may pass different fingerprint from different ingesters to the chunk storage code.

**Comment by pstibrany** [comment]
I've addressed problem where mapping series to a different fingerprint would also be reflected in chunk name, which is not what we want. Fixed now.

**Comment by pstibrany** [comment]
I now have my doubts about whether using original fingerprint for chunk ID is a good idea. By deduping chunks on original fingerprints, we may accidentally drop valid data that way, as we already know that there was fingerprint collision. I cannot find the code doing this deduping in Loki though. In Cortex, it's here: https://github.com/cortexproject/cortex/blob/77a09cc7c953ce5bc4938f042ccb588503ce8eb5/pkg/chunk/chunk_store_utils.go#L55

and with my extra fix, it would definitely drop chunk from different series than expected.

**Comment by cyriltovena** [comment]
> I now have my doubts about whether using original fingerprint for chunk ID is a good idea. By deduping chunks on original fingerprints, we may accidentally drop valid data that way, as we already know that there was fingerprint collision. I cannot find the code doing this deduping in Loki though. In Cortex, it's here: https://github.com/cortexproject/cortex/blob/77a09cc7c953ce5bc4938f042ccb588503ce8eb5/pkg/chunk/chunk_store_utils.go#L55
> 
> and with my extra fix, it would definitely drop chunk from different series than expected.

In the `pkg/storage` we don't filter same fingerprint chunks in Loki. We dedupe entries though.

File: pkg/ingester/flush_test.go [hunk 4]
```diff
@@ -103,12 +149,19 @@ func (s *testStore) Put(ctx context.Context, chunks []chunk.Chunk) error {
...
-	for _, chunk := range chunks {
+	for ix, chunk := range chunks {
 		for _, label := range chunk.Metric {
 			if label.Value == "" {
 				return fmt.Errorf("Chunk has blank label %q", label.Name)
 			}
 		}
+
+		// remove __name__ label
+		if chunk.Metric.Has("__name__") {
```
Comment (cyriltovena) [inline pkg/ingester/flush_test.go]: you could use labels.MetricName (https://github.com/prometheus/prometheus/blob/master/pkg/labels/labels.go#L30)
