### PR TITLE
fix: Remove depricated `entry_parser` from scrapeconfig

### LINKED ISSUE #2631: WARNING!!! entry_parser config is deprecated, please change to pipeline_stages
level=warn ts=2020-09-17T03:04:48.546982792Z caller=filetargetmanager.go:101 msg="WARNING!!! entry_parser config is deprecated, please change to pipeline_stages"

How to solve this problem？

### PR DESCRIPTION
**Pull request by kavirajk**
**What this PR does / why we need it**:

To remove deprecated `entry_parser` config and replace it with `pipeline_stages` everywhere.

**Which issue(s) this PR fixes**:
Fixes #2631 #2577 

**Special notes for your reviewer**:

remove deprecated `entry_parser` from scrapeconfig. use pipeline_stages instead.

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: pkg/promtail/scrapeconfig/scrapeconfig.go [hunk 1]
```diff
@@ -82,7 +80,11 @@ type PushTargetConfig struct {
 
 // DefaultScrapeConfig is the default Config.
 var DefaultScrapeConfig = Config{
-	EntryParser: api.Docker,
+	PipelineStages: []interface{}{
```
Comment (kavirajk) [inline pkg/promtail/scrapeconfig/scrapeconfig.go:83]: [q]: unfortunately coz the type of pipeline stages are just `[]interface{}`. Would love to know if there is a better way!

**Review by cyriltovena — APPROVED** [review]
LGTM
