### PR TITLE
Parse duration expressions in accordance with promql

### LINKED ISSUE #5199: d (day) and w (week) argument doesn't work with offset modifier
**Describe the bug**
Only hour (h), minute (m), milliseconds (ms) and second (s) duration format works with the offset modifier but day (d), week (w) and year (y) throws this error = `parse error at line 1, col 47: syntax error: unexpected NUMBER, expecting DURATION`

**To Reproduce**
Make the 1d and 1w query visible to reproduce the error.

[play.grafana.com link](https://play.grafana.org/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22refId%22:%22E%22,%22expr%22:%22count_over_time(%7Bagent%3D%5C%22promtail%5C%22%7D%5B1m%5D%20offset%201ms)%22,%22hide%22:true%7D,%7B%22refId%22:%22G%22,%22expr%22:%22count_over_time(%7Bagent%3D%5C%22promtail%5C%22%7D%5B1m%5D%20offset%201s)%22,%22hide%22:true%7D,%7B%22refId%22:%22A%22,%22expr%22:%22count_over_time(%7Bagent%3D%5C%22promtail%5C%22%7D%5B1m%5D%20offset%201m)%22,%22hide%22:true%7D,%7B%22refId%22:%22B%22,%22expr%22:%22count_over_time(%7Bagent%3D%5C%22promtail%5C%22%7D%5B1m%5D%20offset%201h)%22,%22hide%22:true%7D,%7B%22refId%22:%22C%22,%22expr%22:%22count_over_time(%7Bagent%3D%5C%22promtail%5C%22%7D%5B1m%5D%20offset%201d)%22,%22hide%22:true%7D,%7B%22refId%22:%22D%22,%22expr%22:%22count_over_time(%7Bagent%3D%5C%22promtail%5C%22%7D%5B1m%5D%20offset%201w)%22,%22hide%22:true%7D,%7B%22refId%22:%22F%22,%22expr%22:%22count_over_time(%7Bagent%3D%5C%22promtail%5C%22%7D%5B1m%5D%20offset%201y)%22,%22hide%22:true%7D%5D)

**Expected behavior**
I expect them to work as they work in promql.

**Environment:**
Any

**Screenshots, Promtail config, or terminal output**

image
image

### PR DESCRIPTION
**Pull request by SasSwart**
**What this PR does / why we need it**:
Add support for promql-like duration units in logql
**Which issue(s) this PR fixes**:
Fixes #5199

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

File: pkg/logql/ast_test.go [hunk 1]
```diff
@@ -78,7 +78,7 @@ func Test_SampleExpr_String(t *testing.T) {
 		`sum(count_over_time({job="mysql"} | pattern "<foo> bar <buzz>" | json [5m]))`,
 		`sum(count_over_time({job="mysql"} | unpack | json [5m]))`,
 		`sum(count_over_time({job="mysql"} | regexp "(?P<foo>foo|bar)" [5m]))`,
-		`sum(count_over_time({job="mysql"} | regexp "(?P<foo>foo|bar)" [5m] offset 10m))`,
+		`sum(count_over_time({job="mysql"} | regexp "(?P<foo>foo|bar)" [5m] offset 10y))`,
```
Comment (dannykopping) [inline pkg/logql/ast_test.go:81]: This just tests that the AST is assembled correctly; we should add a test here that ensures that the duration is parsed as expected and the value will be used correctly.

File: pkg/logql/lex.go [hunk 2]
```diff
@@ -240,21 +240,27 @@ func tryScanDuration(number string, l *scanner.Scanner) (time.Duration, bool) {
 		return 0, false
 	}
 	// we've found more characters before a whitespace or the end
-	d, err := time.ParseDuration(sb.String())
+	var duration time.Duration
+	prometheusDuration, err := model.ParseDuration(sb.String())
 	if err != nil {
-		return 0, false
+		duration, err = time.ParseDuration(sb.String())
```
Comment (dannykopping) [inline pkg/logql/lex.go:246]: I think calling `sb.String()` here will have some interesting side-effects; don't we want to try parse the _same_ token twice?

File: pkg/logql/lex.go [hunk 3]
```diff
@@ -240,21 +240,27 @@ func tryScanDuration(number string, l *scanner.Scanner) (time.Duration, bool) {
 		return 0, false
 	}
 	// we've found more characters before a whitespace or the end
-	d, err := time.ParseDuration(sb.String())
+	var duration time.Duration
+	prometheusDuration, err := model.ParseDuration(sb.String())
```
Comment (dannykopping) [inline pkg/logql/lex.go:244]: A comment here explaining why we're doing this would be helpful

File: pkg/logql/lex.go (hunk 2 above)
Comment (SasSwart) [reply pkg/logql/lex.go:246]: I'm updating this, but to ensure that I follow your reasoning, do you mind explaining which side-effects you anticipate?
Since we aren't writing to the string builder, I would expect calls to String() to be idempotent?

Comment (dannykopping) [reply pkg/logql/lex.go]: Apologies; you're right. I misread; I thought this was reading from the scanner

File: pkg/logql/lex.go (hunk 3 above)
Comment (SasSwart) [reply pkg/logql/lex.go]: Done

File: pkg/logql/ast_test.go (hunk 1 above)
Comment (SasSwart) [reply pkg/logql/ast_test.go:81]: Tests added

File: pkg/logql/lex.go [hunk 4]
```diff
@@ -240,21 +240,43 @@ func tryScanDuration(number string, l *scanner.Scanner) (time.Duration, bool) {
...
+		}
+	} else {
+		duration = time.Duration(prometheusDuration)
+	}
+
+	return duration, nil
 }
 
 func isDurationRune(r rune) bool {
 	// "ns", "us" (or "µs"), "ms", "s", "m", "h".
```
Comment (sandeepsukhani) [inline pkg/logql/lex.go:277]: I think we should keep this comment in sync with what we have in the switch case. While we are at it, can you please also order it the same manner as the switch case?

**Review by sandeepsukhani — APPROVED** [review]
Thanks for the PR! I just added a minor nit but other than that, it LGTM!

**Review by dannykopping — APPROVED** [review]
Thanks for the contribution @SasSwart! LGTM

File: pkg/logql/lex.go (hunk 4 above)
Comment (SasSwart) [reply pkg/logql/lex.go]: Thanks for the feedback! Agreed, and done.

**Review by sandeepsukhani — APPROVED** [review]
LGTM
