### PR TITLE
Fix data race in ingester

### LINKED ISSUE #2265: Data races in ingester
I've run the following and found some races:

```
❯ go test -mod=vendor -race  ./pkg/ingester
==================
WARNING: DATA RACE
Read at 0x00c00020c7f0 by goroutine 103:
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).Bounds()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:458 +0x5e
  github.com/grafana/loki/pkg/ingester.(*Ingester).sweepStream()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:174 +0x26e
  github.com/grafana/loki/pkg/ingester.(*Ingester).sweepInstance()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:157 +0x16b
  github.com/grafana/loki/pkg/ingester.(*Ingester).sweepUsers()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:148 +0x90
  github.com/grafana/loki/pkg/ingester.(*Ingester).loop()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:238 +0x112

Previous write at 0x00c00020c7f0 by goroutine 101:
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).cut()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:437 +0x378
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).Bytes()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:256 +0x12a2
  github.com/grafana/loki/pkg/chunkenc.Facade.Marshal()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/facade.go:47 +0x4b
  github.com/grafana/loki/pkg/chunkenc.(*Facade).Marshal()
      <autogenerated>:1 +0xd5
  github.com/cortexproject/cortex/pkg/chunk.(*Chunk).Encode()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/chunk.go:220 +0x4dd
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushChunks()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:330 +0x6e9
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushUserSeries()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:224 +0x2c8
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushLoop()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:196 +0x5cc

Goroutine 103 (running) created at:
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:187 +0x366
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting-fm()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:167 +0x55
  github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:134 +0x6f8

Goroutine 101 (running) created at:
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:171 +0xb3
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting-fm()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:167 +0x55
  github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:134 +0x6f8
==================
==================
WARNING: DATA RACE
Read at 0x00c0000c8020 by goroutine 103:
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).Bounds()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:459 +0x3ba
  github.com/grafana/loki/pkg/ingester.(*Ingester).sweepStream()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:174 +0x26e
  github.com/grafana/loki/pkg/ingester.(*Ingester).sweepInstance()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:157 +0x16b
  github.com/grafana/loki/pkg/ingester.(*Ingester).sweepUsers()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:148 +0x90
  github.com/grafana/loki/pkg/ingester.(*Ingester).loop()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:238 +0x112

Previous write at 0x00c0000c8020 by goroutine 101:
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).cut()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:437 +0x337
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).Bytes()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:256 +0x12a2
  github.com/grafana/loki/pkg/chunkenc.Facade.Marshal()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/facade.go:47 +0x4b
  github.com/grafana/loki/pkg/chunkenc.(*Facade).Marshal()
      <autogenerated>:1 +0xd5
  github.com/cortexproject/cortex/pkg/chunk.(*Chunk).Encode()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/chunk.go:220 +0x4dd
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushChunks()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:330 +0x6e9
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushUserSeries()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:224 +0x2c8
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushLoop()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:196 +0x5cc

Goroutine 103 (running) created at:
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:187 +0x366
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting-fm()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:167 +0x55
  github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:134 +0x6f8

Goroutine 101 (running) created at:
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:171 +0xb3
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting-fm()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:167 +0x55
  github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:134 +0x6f8
==================
==================
WARNING: DATA RACE
Read at 0x00c0000c8028 by goroutine 103:
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).Bounds()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:460 +0x43c
  github.com/grafana/loki/pkg/ingester.(*Ingester).sweepStream()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:174 +0x26e
  github.com/grafana/loki/pkg/ingester.(*Ingester).sweepInstance()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:157 +0x16b
  github.com/grafana/loki/pkg/ingester.(*Ingester).sweepUsers()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:148 +0x90
  github.com/grafana/loki/pkg/ingester.(*Ingester).loop()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:238 +0x112

Previous write at 0x00c0000c8028 by goroutine 101:
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).cut()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:437 +0x337
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).Bytes()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:256 +0x12a2
  github.com/grafana/loki/pkg/chunkenc.Facade.Marshal()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/facade.go:47 +0x4b
  github.com/grafana/loki/pkg/chunkenc.(*Facade).Marshal()
      <autogenerated>:1 +0xd5
  github.com/cortexproject/cortex/pkg/chunk.(*Chunk).Encode()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/chunk.go:220 +0x4dd
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushChunks()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:330 +0x6e9
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushUserSeries()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:224 +0x2c8
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushLoop()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:196 +0x5cc

Goroutine 103 (running) created at:
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:187 +0x366
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting-fm()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:167 +0x55
  github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:134 +0x6f8

Goroutine 101 (running) created at:
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:171 +0xb3
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting-fm()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:167 +0x55
  github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:134 +0x6f8
==================
==================
WARNING: DATA RACE
Read at 0x00c0007e71a0 by goroutine 103:
  github.com/grafana/loki/pkg/chunkenc.(*headBlock).isEmpty()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:98 +0xad
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).Bounds()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:463 +0x80
  github.com/grafana/loki/pkg/ingester.(*Ingester).sweepStream()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:174 +0x26e
  github.com/grafana/loki/pkg/ingester.(*Ingester).sweepInstance()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:157 +0x16b
  github.com/grafana/loki/pkg/ingester.(*Ingester).sweepUsers()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:148 +0x90
  github.com/grafana/loki/pkg/ingester.(*Ingester).loop()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:238 +0x112

Previous write at 0x00c0007e71a0 by goroutine 101:
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).cut()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:448 +0x456
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).Bytes()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:256 +0x12a2
  github.com/grafana/loki/pkg/chunkenc.Facade.Marshal()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/facade.go:47 +0x4b
  github.com/grafana/loki/pkg/chunkenc.(*Facade).Marshal()
      <autogenerated>:1 +0xd5
  github.com/cortexproject/cortex/pkg/chunk.(*Chunk).Encode()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/chunk.go:220 +0x4dd
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushChunks()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:330 +0x6e9
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushUserSeries()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:224 +0x2c8
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushLoop()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:196 +0x5cc

Goroutine 103 (running) created at:
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:187 +0x366
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting-fm()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:167 +0x55
  github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:134 +0x6f8

Goroutine 101 (running) created at:
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:171 +0xb3
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting-fm()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:167 +0x55
  github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:134 +0x6f8
==================
==================
WARNING: DATA RACE
Write at 0x00c00041c9b0 by goroutine 101:
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).cut()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:449 +0x49a
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).Bytes()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:256 +0x12a2
  github.com/grafana/loki/pkg/chunkenc.Facade.Marshal()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/facade.go:47 +0x4b
  github.com/grafana/loki/pkg/chunkenc.(*Facade).Marshal()
      <autogenerated>:1 +0xd5
  github.com/cortexproject/cortex/pkg/chunk.(*Chunk).Encode()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/chunk.go:220 +0x4dd
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushChunks()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:330 +0x6e9
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushUserSeries()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:224 +0x2c8
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushLoop()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:196 +0x5cc

Previous read at 0x00c00041c9b0 by goroutine 103:
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).Bounds()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:465 +0x32c
  github.com/grafana/loki/pkg/ingester.(*Ingester).sweepStream()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:174 +0x26e
  github.com/grafana/loki/pkg/ingester.(*Ingester).sweepInstance()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:157 +0x16b
  github.com/grafana/loki/pkg/ingester.(*Ingester).sweepUsers()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:148 +0x90
  github.com/grafana/loki/pkg/ingester.(*Ingester).loop()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:238 +0x112

Goroutine 101 (running) created at:
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:171 +0xb3
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting-fm()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:167 +0x55
  github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:134 +0x6f8

Goroutine 103 (running) created at:
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:187 +0x366
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting-fm()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:167 +0x55
  github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:134 +0x6f8
==================
--- FAIL: TestChunkFlushingIdle (20.61s)
    testing.go:906: race detected during execution of test
==================
WARNING: DATA RACE
Write at 0x00c00010e150 by goroutine 82:
  github.com/grafana/loki/pkg/ingester.(*Ingester).collectChunksToFlush()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:252 +0x676
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushUserSeries()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:216 +0xbf
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushLoop()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:196 +0x5cc

Previous read at 0x00c00010e150 by goroutine 83:
  github.com/grafana/loki/pkg/ingester.(*stream).Iterator()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/stream.go:261 +0x4e5
  github.com/grafana/loki/pkg/ingester.TestTransferOut()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/transfer_test.go:90 +0x11d5
  testing.tRunner()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:991 +0x1eb

Goroutine 82 (running) created at:
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:171 +0xb3
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting-fm()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:167 +0x55
  github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:134 +0x6f8

Goroutine 83 (running) created at:
  testing.(*T).Run()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:1042 +0x660
  testing.runTests.func1()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:1284 +0xa6
  testing.tRunner()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:991 +0x1eb
  testing.runTests()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:1282 +0x527
  testing.(*M).Run()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:1199 +0x2ff
  main.main()
      _testmain.go:80 +0x223
==================
==================
WARNING: DATA RACE
Write at 0x00c00010e120 by goroutine 82:
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).Bytes()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:283 +0xd6f
  github.com/grafana/loki/pkg/chunkenc.Facade.Marshal()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/facade.go:47 +0x4b
  github.com/grafana/loki/pkg/chunkenc.(*Facade).Marshal()
      <autogenerated>:1 +0xd5
  github.com/cortexproject/cortex/pkg/chunk.(*Chunk).Encode()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/chunk.go:220 +0x4dd
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushChunks()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:330 +0x6e9
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushUserSeries()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:224 +0x2c8
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushLoop()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:196 +0x5cc

Previous read at 0x00c00010e120 by goroutine 83:
  github.com/grafana/loki/pkg/chunkenc.(*MemChunk).Iterator()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/chunkenc/memchunk.go:481 +0x28d
  github.com/grafana/loki/pkg/ingester.(*stream).Iterator()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/stream.go:262 +0x621
  github.com/grafana/loki/pkg/ingester.TestTransferOut()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/transfer_test.go:90 +0x11d5
  testing.tRunner()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:991 +0x1eb

Goroutine 82 (running) created at:
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:171 +0xb3
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting-fm()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:167 +0x55
  github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:134 +0x6f8

Goroutine 83 (running) created at:
  testing.(*T).Run()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:1042 +0x660
  testing.runTests.func1()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:1284 +0xa6
  testing.tRunner()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:991 +0x1eb
  testing.runTests()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:1282 +0x527
  testing.(*M).Run()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:1199 +0x2ff
  main.main()
      _testmain.go:80 +0x223
==================
==================
WARNING: DATA RACE
Write at 0x00c00010e158 by goroutine 82:
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushUserSeries()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:231 +0x39f
  github.com/grafana/loki/pkg/ingester.(*Ingester).flushLoop()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/flush.go:196 +0x5cc

Previous read at 0x00c00010e158 by goroutine 83:
  github.com/grafana/loki/pkg/ingester.(*stream).Iterator()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/stream.go:261 +0x4e5
  github.com/grafana/loki/pkg/ingester.TestTransferOut()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/transfer_test.go:90 +0x11d5
  testing.tRunner()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:991 +0x1eb

Goroutine 82 (running) created at:
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:171 +0xb3
  github.com/grafana/loki/pkg/ingester.(*Ingester).starting-fm()
      /Users/ctovena/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:167 +0x55
  github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main()
      /Users/ctovena/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:134 +0x6f8

Goroutine 83 (running) created at:
  testing.(*T).Run()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:1042 +0x660
  testing.runTests.func1()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:1284 +0xa6
  testing.tRunner()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:991 +0x1eb
  testing.runTests()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:1282 +0x527
  testing.(*M).Run()
      /usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:1199 +0x2ff
  main.main()
      _testmain.go:80 +0x223
==================
--- FAIL: TestTransferOut (0.31s)
    testing.go:906: race detected during execution of test
FAIL
FAIL	github.com/grafana/loki/pkg/ingester	89.175s
FAIL
```

I don't think they all are legitimate, and probably generated by the tests, but we should make sure this is the case and solve them all.

### PR DESCRIPTION
**Pull request by adityacs**
**What this PR does / why we need it**:
Fixes data race in ingester

**Which issue(s) this PR fixes**:
Fixes #2265

### CODE REVIEW

File: pkg/ingester/flush.go [hunk 1]
```diff
@@ -327,9 +328,11 @@ func (i *Ingester) flushChunks(ctx context.Context, fp model.Fingerprint, labelP
 		)
 
 		start := time.Now()
+		streamsMtx.Lock()
 		if err := c.Encode(); err != nil {
 			return err
 		}
+		streamsMtx.Unlock()
```
Comment (cyriltovena) [inline pkg/ingester/flush.go:335]: I think you should do a defer here.

Comment (cyriltovena) [reply pkg/ingester/flush.go:335]: Can you explain who is racing for the stream data here ? Querying ?

Comment (adityacs) [reply pkg/ingester/flush.go:335]: I think we should not defer `Unlock`. The reason being putting chunks to store here would be locked and other flush threads won't be able to call `put` until the lock is released. This would become sequential `io` and eventually make all flush threads sequential.

https://github.com/grafana/loki/blob/e22f365025cf0dc091f343ebda75141ed733f2f5/pkg/ingester/flush.go#L337

Comment (cyriltovena) [reply pkg/ingester/flush.go:335]: If you return an error you're deadlocked.

Comment (adityacs) [reply pkg/ingester/flush.go:335]: > Can you explain who is racing for the stream data here ? Querying ?

Yeah, it is `querying` which access the stream chunks here
https://github.com/grafana/loki/blob/e22f365025cf0dc091f343ebda75141ed733f2f5/pkg/ingester/stream.go#L261

but this is Read protected with streamMtx lock here 
https://github.com/grafana/loki/blob/e22f365025cf0dc091f343ebda75141ed733f2f5/pkg/ingester/instance.go#L316

since `c.Encode` is not write locked it causes the race.

Also, reading first chunk and getting bounds on that here causes the race.
https://github.com/grafana/loki/blob/e22f365025cf0dc091f343ebda75141ed733f2f5/pkg/ingester/flush.go#L174

Comment (cyriltovena) [reply pkg/ingester/flush.go:335]: firstTime, _ := stream.chunks[0].chunk.Bounds()  ? this one is fixed or already ok ?

Comment (adityacs) [reply pkg/ingester/flush.go:335]: > If you return an error you're deadlocked

oh yeah. You are right. Didn't realize that.

Comment (adityacs) [reply pkg/ingester/flush.go:335]: > firstTime, _ := stream.chunks[0].chunk.Bounds() ? this one is fixed or already ok ?

this was already protected

Comment (cyriltovena) [reply pkg/ingester/flush.go]: Great !
