### PR TITLE
fix: Handle WAL corruption properly on startup

### LINKED ISSUE #12583: WAL corruption leads to endless restarts
**Describe the bug**

loki-write pod is dying with this log:
```
msg="error running loki" err="corruption in segment /var/loki/tsdb-shipper-active/wal/s3_2024-01-02/1712203235/00000004 at 65536: last record is torn\nerror recovering from TSDB WAL"
```
and restarts indefinitely (crashlooping).

But at each restart it reads the WAL and updates object storage.
On a big WAL this can cost a lot because all the data is sent to the object storage again and again.

**To Reproduce**

1. Running Loki 2.9.6
2. It happens once in a while on clusters that are a bit undersized and where pods tend to die OOM.
3. This does not happen consistently.

**Expected behavior**
I can understand the WAL can get corrupted when the app unexpectedly crashes.
But maybe when the WAL is corrupted it should discard it? So after it crashes once it can start properly, and not retry endlessly?

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm 5.47.2

### PR DESCRIPTION
**Pull request by Segflow**
**What this PR does / why we need it**:

Currently a WAL corruption  lead to endless restart loops, as reported in [issue #12583](https://github.com/grafana/loki/issues/12583). Users experience crashes with errors like:

```
corruption in segment /var/loki/tsdb-shipper-active/wal/s3_2024-01-02/1712203235/00000004 at 65536: last record is torn
error recovering from TSDB WAL
```

[and](https://github.com/grafana/loki/issues/12583#issuecomment-2381017345) 

```
"error running loki" err="corruption in segment /data/loki/index/wal/filesystem_2023-05-01/1727455534/00000000 at 81944: unexpected checksum 2ffb91ba, expected 5999e2d7
error recovering from TSDB WAL
```

This causes loki to crashloop indefinitely, repeatedly reading the WAL and updating object storage, which can be costly for large WALs. 

This PR adds the ability to repair the WAL on startup (if possible). It also adds unit tests which corrupt the WAL and try to recover it after. 

Notice that we only recover from the corruption at the TSDB WAL level. Any corruption in the data part (invalid chunks or invalid series) is unrecoverable and we just log the error and crash.

It also includes some documentation about the WAL format used for future reference.

The metric `wal_corruptions_repairs_total` is added to track whenever we fail or succeed to repair the corrupted WAL.

**Which issue(s) this PR fixes**:
Fixes #12583

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] Documentation added
- [x] Tests updated
- [x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

File: pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go [hunk 1]
```diff
@@ -599,16 +602,32 @@ func recoverHead(name, dir string, heads *tenantHeads, wals []WALIdentifier, leg
...
+			if err := repairWAL(werr, walPath, logger); err != nil {
+				return fmt.Errorf("repairing WAL failed: %w", err)
+			}
 		}
 	}
 	return nil
 }
 
+func repairWAL(walErr error, walPath string, logger log.Logger) error {
+	wl, err := wlog.New(util_log.SlogFromGoKit(logger), nil, walPath, compression.None)
```
Comment (paul1r) [inline pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go:625]: I think it would be good to have a metric saying we are repairing a WAL, along with a "success/fail" result as a piece of that metric

File: pkg/storage/stores/shipper/indexshipper/tsdb/head_manager_test.go [hunk 2]
```diff
@@ -267,6 +268,119 @@ func Test_HeadManager_RecoverHead(t *testing.T) {
...
 
+// test head recover from corrupted wal
+func Test_HeadManager_RecoverHead_CorruptedWAL(t *testing.T) {
+	for _, tc := range []struct {
+		name      string
+		setupFunc func(t *testing.T, walPath string, w *headWAL)
+		expectErr bool
+	}{
+		{
+			name: "las record torn",
```
Comment (paul1r) [inline pkg/storage/stores/shipper/indexshipper/tsdb/head_manager_test.go]:
```suggestion
			name: "last record torn",
```

File: pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go (hunk 1 above)
Comment (Segflow) [reply pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go:625]: Good idea, just pushed a new commit for that.

File: pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go [hunk 3]
```diff
@@ -545,7 +546,7 @@ func legacyWalPath(parent string, t time.Time) string {
 
 // recoverHead recovers from all WALs belonging to some period
 // and inserts it into the active *tenantHeads
-func recoverHead(name, dir string, heads *tenantHeads, wals []WALIdentifier, legacy bool, logger log.Logger) error {
+func recoverHead(name, dir string, heads *tenantHeads, wals []WALIdentifier, legacy bool, logger log.Logger, metric *prometheus.CounterVec) error {
```
Comment (salvacorts) [inline pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go]: I'd give the metric a more meaningfull name
```suggestion
func recoverHead(name, dir string, heads *tenantHeads, wals []WALIdentifier, legacy bool, logger log.Logger, repairsCounter *prometheus.CounterVec) error {
```

Comment (Segflow) [reply pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go]: Good point, handled.

**Comment by cedws** [comment]
We just upgraded to the latest version (3.5.2) in the hopes this fix would get us up and running again but unfortunately it hasn't worked. I do believe the corruption is in the TSDB WAL.

```
github.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.NewStore
    /src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/store.go:59
github.com/grafana/loki/v3/pkg/storage.(*LokiStore).storeForPeriod
    /src/loki/pkg/storage/store.go:294
github.com/grafana/loki/v3/pkg/storage.(*LokiStore).init
    /src/loki/pkg/storage/store.go:210
github.com/grafana/loki/v3/pkg/storage.NewStore
    /src/loki/pkg/storage/store.go:189
github.com/grafana/loki/v3/pkg/loki.(*Loki).initStore
    /src/loki/pkg/loki/modules.go:929
github.com/grafana/dskit/modules.(*Manager).initModule
    /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:136
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
    /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108
github.com/grafana/loki/v3/pkg/loki.(*Loki).Run
    /src/loki/pkg/loki/loki.go:531
main.main
    /src/loki/cmd/loki/main.go:129
runtime.main
    /usr/local/go/src/runtime/proc.go:283
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:1700
building tsdb from WALs
github.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*HeadManager).buildTSDBFromWALs
    /src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go:322
github.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*HeadManager).Start
    /src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go:283
github.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*store).init
    /src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/store.go:130
github.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.NewStore
    /src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/store.go:59
github.com/grafana/loki/v3/pkg/storage.(*LokiStore).storeForPeriod
    /src/loki/pkg/storage/store.go:294
github.com/grafana/loki/v3/pkg/storage.(*LokiStore).init
    /src/loki/pkg/storage/store.go:210
github.com/grafana/loki/v3/pkg/storage.NewStore
    /src/loki/pkg/storage/store.go:189
github.com/grafana/loki/v3/pkg/loki.(*Loki).initStore
    /src/loki/pkg/loki/modules.go:929
github.com/grafana/dskit/modules.(*Manager).initModule
    /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:136
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
    /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108
github.com/grafana/loki/v3/pkg/loki.(*Loki).Run
    /src/loki/pkg/loki/loki.go:531
main.main
    /src/loki/cmd/loki/main.go:129
runtime.main
    /usr/local/go/src/runtime/proc.go:283
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:1700
building tsdb from old WAL files
github.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*HeadManager).Start
    /src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go:284
github.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*store).init
    /src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/store.go:130
github.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.NewStore
    /src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/store.go:59
github.com/grafana/loki/v3/pkg/storage.(*LokiStore).storeForPeriod
    /src/loki/pkg/storage/store.go:294
github.com/grafana/loki/v3/pkg/storage.(*LokiStore).init
    /src/loki/pkg/storage/store.go:210
github.com/grafana/loki/v3/pkg/storage.NewStore
    /src/loki/pkg/storage/store.go:189
github.com/grafana/loki/v3/pkg/loki.(*Loki).initStore
    /src/loki/pkg/loki/modules.go:929
github.com/grafana/dskit/modules.(*Manager).initModule
    /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:136
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
    /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108
github.com/grafana/loki/v3/pkg/loki.(*Loki).Run
    /src/loki/pkg/loki/loki.go:531
main.main
    /src/loki/cmd/loki/main.go:129
runtime.main
    /usr/local/go/src/runtime/proc.go:283
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:1700
error initialising module: store
github.com/grafana/dskit/modules.(*Manager).initModule
    /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
    /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108
github.com/grafana/loki/v3/pkg/loki.(*Loki).Run
    /src/loki/pkg/loki/loki.go:531
main.main
    /src/loki/cmd/loki/main.go:129
runtime.main
    /usr/local/go/src/runtime/proc.go:283
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:1700
level=info ts=2025-07-16T05:30:15.46796609Z caller=main.go:126 msg="Starting Loki" version="(version=3.5.2, branch=release-3.5.x, revision=257d2f62)"
level=info ts=2025-07-16T05:30:15.468071312Z caller=main.go:127 msg="Loading configuration file" filename=/etc/loki/config/config.yaml
level=info ts=2025-07-16T05:30:15.47029783Z caller=server.go:368 msg="server listening on addresses" http=[::[]:3100 grpc=[::]:9095
level=info ts=2025-07-16T05:30:15.500242963Z caller=shipper.go:165 index-store=tsdb-2024-04-01 msg="starting index shipper in WO mode"
level=info ts=2025-07-16T05:30:15.500742972Z caller=table_manager.go:136 index-store=tsdb-2024-04-01 msg="uploading tables"
level=info ts=2025-07-16T05:30:15.501049247Z caller=head_manager.go:308 index-store=tsdb-2024-04-01 component=tsdb-head-manager msg="loaded wals by period" groups=0
level=info ts=2025-07-16T05:30:15.501171708Z caller=manager.go:86 index-store=tsdb-2024-04-01 component=tsdb-manager msg="loaded leftover local indices" err=null successful=true buckets=1 indices=0 failures=0
level=info ts=2025-07-16T05:30:15.501213219Z caller=head_manager.go:308 index-store=tsdb-2024-04-01 component=tsdb-head-manager msg="loaded wals by period" groups=2
level=error ts=2025-07-16T05:30:15.505194276Z caller=log.go:223 msg="error running loki" err="corruption in segment /var/loki/tsdb-shipper-active/wal/s3_2024-04-01/1752570902/00000000 at 65536: last record is torn\nerror recovering from TSDB WAL\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.recoverHead\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go:603\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*tsdbManager).BuildFromWALs\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/manager.go:290\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*HeadManager).buildTSDBFromWALs\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go:317\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*HeadManager).Start\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go:283\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*store).init\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/store.go:130\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.NewStore\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/store.go:59\ngithub.com/grafana/loki/v3/pkg/storage.(*LokiStore).storeForPeriod\n\t/src/loki/pkg/storage/store.go:294\ngithub.com/grafana/loki/v3/pkg/storage.(*LokiStore).init\n\t/src/loki/pkg/storage/store.go:210\ngithub.com/grafana/loki/v3/pkg/storage.NewStore\n\t/src/loki/pkg/storage/store.go:189\ngithub.com/grafana/loki/v3/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:929\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:136\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/v3/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:531\nmain.main\n\t/src/loki/cmd/loki/main.go:129\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:283\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700\nbuilding TSDB from WALs\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*tsdbManager).BuildFromWALs\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/manager.go:291\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*HeadManager).buildTSDBFromWALs\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go:317\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*HeadManager).Start\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go:283\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*store).init\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/store.go:130\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.NewStore\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/store.go:59\ngithub.com/grafana/loki/v3/pkg/storage.(*LokiStore).storeForPeriod\n\t/src/loki/pkg/storage/store.go:294\ngithub.com/grafana/loki/v3/pkg/storage.(*LokiStore).init\n\t/src/loki/pkg/storage/store.go:210\ngithub.com/grafana/loki/v3/pkg/storage.NewStore\n\t/src/loki/pkg/storage/store.go:189\ngithub.com/grafana/loki/v3/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:929\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:136\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/v3/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:531\nmain.main\n\t/src/loki/cmd/loki/main.go:129\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:283\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700\nbuilding tsdb from WALs\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*HeadManager).buildTSDBFromWALs\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go:322\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*HeadManager).Start\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go:283\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*store).init\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/store.go:130\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.NewStore\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/store.go:59\ngithub.com/grafana/loki/v3/pkg/storage.(*LokiStore).storeForPeriod\n\t/src/loki/pkg/storage/store.go:294\ngithub.com/grafana/loki/v3/pkg/storage.(*LokiStore).init\n\t/src/loki/pkg/storage/store.go:210\ngithub.com/grafana/loki/v3/pkg/storage.NewStore\n\t/src/loki/pkg/storage/store.go:189\ngithub.com/grafana/loki/v3/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:929\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:136\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/v3/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:531\nmain.main\n\t/src/loki/cmd/loki/main.go:129\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:283\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700\nbuilding tsdb from old WAL files\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*HeadManager).Start\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go:284\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.(*store).init\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/store.go:130\ngithub.com/grafana/loki/v3/pkg/storage/stores/shipper/indexshipper/tsdb.NewStore\n\t/src/loki/pkg/storage/stores/shipper/indexshipper/tsdb/store.go:59\ngithub.com/grafana/loki/v3/pkg/storage.(*LokiStore).storeForPeriod\n\t/src/loki/pkg/storage/store.go:294\ngithub.com/grafana/loki/v3/pkg/storage.(*LokiStore).init\n\t/src/loki/pkg/storage/store.go:210\ngithub.com/grafana/loki/v3/pkg/storage.NewStore\n\t/src/loki/pkg/storage/store.go:189\ngithub.com/grafana/loki/v3/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:929\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:136\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/v3/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:531\nmain.main\n\t/src/loki/cmd/loki/main.go:129\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:283\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700\nerror initialising module: store\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/v3/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:531\nmain.main\n\t/src/loki/cmd/loki/main.go:129\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:283\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700"
stream closed EOF for observability/loki-write-2 (loki)
```
