### PR TITLE
fix: align semantics of metric and log query label extraction

### LINKED ISSUE #11647: discrepancy between logs and metrics query when extracting nested values to the same label
**Describe the bug**
The processing of logs and metrics queries for the same selector and filters, such as `{cluster="foo", namespace="bar"} | json | line_format "{{.message}}" | json | message!="bad message"}`  and `sum by (level) (count_over_time({cluster="foo", namespace="bar"} | json | line_format "{{.message}}" | json | message!="bad message"}[1m])`, do not follow the same label parsing semantics.

Assuming a log line that has nested json, like `{"message": "{"message": "bad message"}"}`, the first query above will walk through the log line, parsing all labels sequential, and continue parsing all labels (as that's required for a logs query). As a result, it will return 0 log lines, since the inner message does not satisfy the filter.

The second query has an optimization where it only parses the requested labels (in this case level and message), and stops parsing once all required labels have been parsed. As a result, it will return 1, since the outer message does indeed satisfy the filter.

**To Reproduce**
1. Started Loki (bug is present in HEAD of `main`)
2. Ingest log lines with nested json
3. Issue queries above and see discrepancy

**Expected behavior**
The metrics query is correct, and the logs query should return the log line as it should not try to re-extract the `message` label after the first extraction.

### PR DESCRIPTION
**Pull request by trevorwhitney**
**What this PR does / why we need it**:

As a result of the query optimization work, we accidentally introduced a discrepancy between the semantics of logs and metrics queries. Metric queries can benefit from a short-circuit during label extraction, where we only need the labels needed for grouping and filtering. Log queries need to always extract all labels, as a user may want to inspect the key=value pairs of all detected fields, not just those filtered on.

However, given a query with nested labels of the same name (ie `{"message": {"message": "foo"}}`) this short circuit introduces a problem where the metric query will use the value of the first `message` (since it stops parsing the `message` key after finding it once), but the log query will use the value of the second `message` (since it will continue to extract all labels, even those it has already seen). This PR changes the semantics so that both types of queries will only use the first value.

The result of the change is a slight improvement in the hot path of label extraction, which I interpret as us having to do a few more operations due to the removal of the `len(requiredLabels) ==  0` short circuit, but those operations are quick, and thus more are done in the same runtime.

```
goos: linux
goarch: amd64
pkg: github.com/grafana/loki/pkg/logql/log
cpu: AMD Ryzen 5 3600X 6-Core Processor             
                                                    │  before.txt   │               after.txt               │
                                                    │    sec/op     │    sec/op     vs base                 │
_Parser/json/no_labels_hints-12                        4.433µ ± ∞ ¹   4.502µ ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/json/labels_hints-12                          3015.0n ± ∞ ¹   177.4n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/json/inline_stages-12                          1.066µ ± ∞ ¹   1.037µ ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/no_labels_hints-12    77.77n ± ∞ ¹   76.95n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/labels_hints-12       93.73n ± ∞ ¹   80.21n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/inline_stages-12     105.70n ± ∞ ¹   80.12n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack/no_labels_hints-12                      714.5n ± ∞ ¹   718.8n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack/labels_hints-12                         657.7n ± ∞ ¹   780.8n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack/inline_stages-12                        656.3n ± ∞ ¹   721.8n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/no_labels_hints-12        14.58n ± ∞ ¹   14.08n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/labels_hints-12           14.13n ± ∞ ¹   14.86n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/inline_stages-12          14.65n ± ∞ ¹   13.19n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/logfmt/no_labels_hints-12                      2.747µ ± ∞ ¹   3.383µ ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/logfmt/labels_hints-12                        3007.0n ± ∞ ¹   546.5n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/logfmt/inline_stages-12                        904.8n ± ∞ ¹   905.8n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_greedy/no_labels_hints-12                4.460µ ± ∞ ¹   4.545µ ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_greedy/labels_hints-12                   4.566µ ± ∞ ¹   4.453µ ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_greedy/inline_stages-12                  4.474µ ± ∞ ¹   4.529µ ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/no_labels_hints-12         406.0n ± ∞ ¹   455.2n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/labels_hints-12            457.2n ± ∞ ¹   401.3n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/inline_stages-12           431.8n ± ∞ ¹   418.7n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/pattern/no_labels_hints-12                     258.4n ± ∞ ¹   281.7n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/pattern/labels_hints-12                        223.8n ± ∞ ¹   258.3n ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/pattern/inline_stages-12                       165.1n ± ∞ ¹   166.4n ± ∞ ¹        ~ (p=1.000 n=1) ²
geomean                                                452.1n         376.3n        -16.77%
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05

                                                    │  before.txt   │              after.txt               │
                                                    │     B/op      │    B/op      vs base                 │
_Parser/json/no_labels_hints-12                         280.0 ± ∞ ¹   280.0 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/json/labels_hints-12                          176.000 ± ∞ ¹   8.000 ± ∞ ¹        ~ (p=1.000 n=1) ³
_Parser/json/inline_stages-12                           64.00 ± ∞ ¹   64.00 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/no_labels_hints-12     0.000 ± ∞ ¹   0.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/labels_hints-12        0.000 ± ∞ ¹   0.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/inline_stages-12       0.000 ± ∞ ¹   0.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack/no_labels_hints-12                       80.00 ± ∞ ¹   80.00 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack/labels_hints-12                          80.00 ± ∞ ¹   80.00 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack/inline_stages-12                         80.00 ± ∞ ¹   80.00 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/no_labels_hints-12         0.000 ± ∞ ¹   0.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/labels_hints-12            0.000 ± ∞ ¹   0.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/inline_stages-12           0.000 ± ∞ ¹   0.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/logfmt/no_labels_hints-12                       336.0 ± ∞ ¹   336.0 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/logfmt/labels_hints-12                         336.00 ± ∞ ¹   52.00 ± ∞ ¹        ~ (p=1.000 n=1) ³
_Parser/logfmt/inline_stages-12                         74.00 ± ∞ ¹   74.00 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_greedy/no_labels_hints-12                 192.0 ± ∞ ¹   192.0 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_greedy/labels_hints-12                    192.0 ± ∞ ¹   192.0 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_greedy/inline_stages-12                   192.0 ± ∞ ¹   192.0 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/no_labels_hints-12          51.00 ± ∞ ¹   51.00 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/labels_hints-12             51.00 ± ∞ ¹   51.00 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/inline_stages-12            51.00 ± ∞ ¹   51.00 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/pattern/no_labels_hints-12                      35.00 ± ∞ ¹   35.00 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/pattern/labels_hints-12                         32.00 ± ∞ ¹   32.00 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/pattern/inline_stages-12                        3.000 ± ∞ ¹   3.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
geomean                                                           ⁴                -18.66%               ⁴
¹ need >= 6 samples for confidence interval at level 0.95
² all samples are equal
³ need >= 4 samples to detect a difference at alpha level 0.05
⁴ summaries must be >0 to compute geomean

                                                    │  before.txt  │              after.txt               │
                                                    │  allocs/op   │  allocs/op   vs base                 │
_Parser/json/no_labels_hints-12                        18.00 ± ∞ ¹   18.00 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/json/labels_hints-12                          12.000 ± ∞ ¹   1.000 ± ∞ ¹        ~ (p=1.000 n=1) ³
_Parser/json/inline_stages-12                          4.000 ± ∞ ¹   4.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/no_labels_hints-12    0.000 ± ∞ ¹   0.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/labels_hints-12       0.000 ± ∞ ¹   0.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/inline_stages-12      0.000 ± ∞ ¹   0.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack/no_labels_hints-12                      4.000 ± ∞ ¹   4.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack/labels_hints-12                         4.000 ± ∞ ¹   4.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack/inline_stages-12                        4.000 ± ∞ ¹   4.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/no_labels_hints-12        0.000 ± ∞ ¹   0.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/labels_hints-12           0.000 ± ∞ ¹   0.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/inline_stages-12          0.000 ± ∞ ¹   0.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/logfmt/no_labels_hints-12                      16.00 ± ∞ ¹   16.00 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/logfmt/labels_hints-12                        16.000 ± ∞ ¹   3.000 ± ∞ ¹        ~ (p=1.000 n=1) ³
_Parser/logfmt/inline_stages-12                        6.000 ± ∞ ¹   6.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_greedy/no_labels_hints-12                2.000 ± ∞ ¹   2.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_greedy/labels_hints-12                   2.000 ± ∞ ¹   2.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_greedy/inline_stages-12                  2.000 ± ∞ ¹   2.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/no_labels_hints-12         2.000 ± ∞ ¹   2.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/labels_hints-12            2.000 ± ∞ ¹   2.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/inline_stages-12           2.000 ± ∞ ¹   2.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/pattern/no_labels_hints-12                     2.000 ± ∞ ¹   2.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/pattern/labels_hints-12                        1.000 ± ∞ ¹   1.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
_Parser/pattern/inline_stages-12                       1.000 ± ∞ ¹   1.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
geomean                                                          ⁴                -15.91%               ⁴
¹ need >= 6 samples for confidence interval at level 0.95
² all samples are equal
³ need >= 4 samples to detect a difference at alpha level 0.05
⁴ summaries must be >0 to compute geomean
```

**Which issue(s) this PR fixes**:
Fixes #11647

### CODE REVIEW

**Review by chaudum — COMMENTED** [review]
LGTM

Please add a changelog entry and add the appropriate labels for backporting.

File: pkg/logql/log/parser_hints.go [hunk 1]
```diff
@@ -95,19 +91,25 @@ func (p *Hints) NoLabels() bool {
...
+	for _, e := range p.extracted {
+		for _, l := range p.requiredLabels {
+			if e == l {
+				found[l] = nil
+				break
+			}
+		}
+	}
+
+	return len(p.requiredLabels) == len(found)
```
Comment (trevorwhitney) [inline pkg/logql/log/parser_hints.go:112]: this is needed because previously, `RecordExtracted` was only recording required fields that were extracted. As a result, it was previously acceptable to just test the length of the 2 slices against each other. However, now that we're recording _all_ extracted labels, we have to actually compare extracted to required. I'm using a map to prevent duplicate extractions from causing an incorrect result here.

**Comment by trevorwhitney** [comment]
Ok, I think I've figured out why the benchmark was off. Here's a new benchstat after pushing 147dbab:

```
goos: linux
goarch: amd64
pkg: github.com/grafana/loki/pkg/logql/log
cpu: AMD Ryzen 5 3600X 6-Core Processor             
                                                    │  before.txt  │               after.txt               │
                                                    │    sec/op    │    sec/op      vs base                │
_Parser/json/no_labels_hints-12                       4.479µ ± ∞ ¹    4.419µ ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/json/labels_hints-12                          3.060µ ± ∞ ¹    3.483µ ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/json/inline_stages-12                         1.006µ ± ∞ ¹    1.050µ ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/no_labels_hints-12   76.89n ± ∞ ¹    78.11n ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/labels_hints-12      77.43n ± ∞ ¹    79.86n ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/inline_stages-12     77.66n ± ∞ ¹    76.44n ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack/no_labels_hints-12                     798.5n ± ∞ ¹    726.9n ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack/labels_hints-12                        839.7n ± ∞ ¹    845.7n ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack/inline_stages-12                       817.1n ± ∞ ¹    817.1n ± ∞ ¹       ~ (p=1.000 n=1) ³
_Parser/unpack-not_json_line/no_labels_hints-12       13.37n ± ∞ ¹    13.33n ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/labels_hints-12          12.55n ± ∞ ¹    14.73n ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/inline_stages-12         13.90n ± ∞ ¹    13.79n ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/logfmt/no_labels_hints-12                     3.324µ ± ∞ ¹    3.287µ ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/logfmt/labels_hints-12                        3.586µ ± ∞ ¹    4.311µ ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/logfmt/inline_stages-12                       981.9n ± ∞ ¹   1067.0n ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_greedy/no_labels_hints-12               4.477µ ± ∞ ¹    4.609µ ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_greedy/labels_hints-12                  4.530µ ± ∞ ¹    4.550µ ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_greedy/inline_stages-12                 4.504µ ± ∞ ¹    4.767µ ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/no_labels_hints-12        484.7n ± ∞ ¹    470.3n ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/labels_hints-12           446.1n ± ∞ ¹    457.4n ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/inline_stages-12          489.2n ± ∞ ¹    473.7n ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/pattern/no_labels_hints-12                    294.0n ± ∞ ¹    313.6n ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/pattern/labels_hints-12                       315.0n ± ∞ ¹    291.7n ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/pattern/inline_stages-12                      179.0n ± ∞ ¹    187.5n ± ∞ ¹       ~ (p=1.000 n=1) ²
geomean                                               472.4n          484.3n        +2.51%
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05
³ all samples are equal

                                                    │ before.txt  │              after.txt              │
                                                    │    B/op     │    B/op      vs base                │
_Parser/json/no_labels_hints-12                       280.0 ± ∞ ¹   280.0 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/json/labels_hints-12                          176.0 ± ∞ ¹   176.0 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/json/inline_stages-12                         64.00 ± ∞ ¹   64.00 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/no_labels_hints-12   0.000 ± ∞ ¹   0.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/labels_hints-12      0.000 ± ∞ ¹   0.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/inline_stages-12     0.000 ± ∞ ¹   0.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack/no_labels_hints-12                     80.00 ± ∞ ¹   80.00 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack/labels_hints-12                        80.00 ± ∞ ¹   80.00 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack/inline_stages-12                       80.00 ± ∞ ¹   80.00 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/no_labels_hints-12       0.000 ± ∞ ¹   0.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/labels_hints-12          0.000 ± ∞ ¹   0.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/inline_stages-12         0.000 ± ∞ ¹   0.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/logfmt/no_labels_hints-12                     336.0 ± ∞ ¹   336.0 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/logfmt/labels_hints-12                        336.0 ± ∞ ¹   336.0 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/logfmt/inline_stages-12                       74.00 ± ∞ ¹   74.00 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_greedy/no_labels_hints-12               192.0 ± ∞ ¹   192.0 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_greedy/labels_hints-12                  192.0 ± ∞ ¹   192.0 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_greedy/inline_stages-12                 192.0 ± ∞ ¹   192.0 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/no_labels_hints-12        51.00 ± ∞ ¹   51.00 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/labels_hints-12           51.00 ± ∞ ¹   51.00 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/inline_stages-12          51.00 ± ∞ ¹   51.00 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/pattern/no_labels_hints-12                    35.00 ± ∞ ¹   35.00 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/pattern/labels_hints-12                       32.00 ± ∞ ¹   32.00 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/pattern/inline_stages-12                      3.000 ± ∞ ¹   3.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
geomean                                                         ³                +0.00%               ³
¹ need >= 6 samples for confidence interval at level 0.95
² all samples are equal
³ summaries must be >0 to compute geomean

                                                    │ before.txt  │              after.txt              │
                                                    │  allocs/op  │  allocs/op   vs base                │
_Parser/json/no_labels_hints-12                       18.00 ± ∞ ¹   18.00 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/json/labels_hints-12                          12.00 ± ∞ ¹   12.00 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/json/inline_stages-12                         4.000 ± ∞ ¹   4.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/no_labels_hints-12   0.000 ± ∞ ¹   0.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/labels_hints-12      0.000 ± ∞ ¹   0.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/jsonParser-not_json_line/inline_stages-12     0.000 ± ∞ ¹   0.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack/no_labels_hints-12                     4.000 ± ∞ ¹   4.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack/labels_hints-12                        4.000 ± ∞ ¹   4.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack/inline_stages-12                       4.000 ± ∞ ¹   4.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/no_labels_hints-12       0.000 ± ∞ ¹   0.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/labels_hints-12          0.000 ± ∞ ¹   0.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/unpack-not_json_line/inline_stages-12         0.000 ± ∞ ¹   0.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/logfmt/no_labels_hints-12                     16.00 ± ∞ ¹   16.00 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/logfmt/labels_hints-12                        16.00 ± ∞ ¹   16.00 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/logfmt/inline_stages-12                       6.000 ± ∞ ¹   6.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_greedy/no_labels_hints-12               2.000 ± ∞ ¹   2.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_greedy/labels_hints-12                  2.000 ± ∞ ¹   2.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_greedy/inline_stages-12                 2.000 ± ∞ ¹   2.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/no_labels_hints-12        2.000 ± ∞ ¹   2.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/labels_hints-12           2.000 ± ∞ ¹   2.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/regex_status_digits/inline_stages-12          2.000 ± ∞ ¹   2.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/pattern/no_labels_hints-12                    2.000 ± ∞ ¹   2.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/pattern/labels_hints-12                       1.000 ± ∞ ¹   1.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
_Parser/pattern/inline_stages-12                      1.000 ± ∞ ¹   1.000 ± ∞ ¹       ~ (p=1.000 n=1) ²
geomean                                                         ³                +0.00%               ³
¹ need >= 6 samples for confidence interval at level 0.95
² all samples are equal
³ summaries must be >0 to compute geomean
```

The change needed was in [`AllRequiredExtracted`](https://github.com/grafana/loki/pull/11587/files#r1449297006) to account for the fact that we're recording all extracted labels now, and not just required ones.

@MasslessParticle kudos to your diligence here in making sure we understood why this benchmark was off!

File: pkg/logql/log/parser_hints.go [hunk 2]
```diff
@@ -95,19 +91,25 @@ func (p *Hints) NoLabels() bool {
...
 }
 
 func (p *Hints) AllRequiredExtracted() bool {
-	if len(p.requiredLabels) == 0 {
+	if len(p.requiredLabels) == 0 || len(p.extracted) < len(p.requiredLabels) {
 		return false
 	}
-	return len(p.extracted) == len(p.requiredLabels)
+
+	found := map[string]interface{}{}
```
Comment (MasslessParticle) [inline pkg/logql/log/parser_hints.go:102]: We probably want to say `found := make(map[string]struct{}, len(p.requiredLabels))` here. `struct{}` is smaller than `interface{}` and initializing with the max len we'll need ensures only one alloc

File: pkg/logql/log/parser_hints.go [hunk 3]
```diff
@@ -95,19 +91,25 @@ func (p *Hints) NoLabels() bool {
...
+	for _, e := range p.extracted {
```
Comment (MasslessParticle) [inline pkg/logql/log/parser_hints.go:103]: It might also be worth seeing if it's faster to just compare the list in two loops. It's an n^2 algorithm but it might be faster because it requires no allocs. (This function is called a lot)

It's the same reason `extractedLabels` and `requiredLabels` are `[]string` here rather than `map[string]`. It's actually faster to iterate a small slice than index all these things from a map!

**Review by MasslessParticle — APPROVED** [review]

**Comment by jameshartig** [comment]
@trevorwhitney I believe this ended up breaking downstream parsers/formatters overwriting fields. See https://github.com/grafana/loki/issues/12839, https://github.com/grafana/loki/issues/12798, and https://github.com/grafana/loki/issues/12800.
