### PR TITLE
Ip matcher for LogQL

### LINKED ISSUE #2722: Ready-made matchers for IP addresses
A recurring pain point is writing matchers for IPv4, IPv6, email addresses, etc. This leads to cargo culting of regexps, often wrong, from stackexchange. Even worse is trying to find valid regex for CIDR matching.

https://mobile.twitter.com/bettersafetynet/status/1312884924811227137 reminded me that we have the chance to get this right for our users days one, so we should :)

### PR DESCRIPTION
**Pull request by kavirajk**
**What this PR does / why we need it**:

This PR adds buiilt-in IP matcher support for LogQL. It adds filter `ip(pattern)`. It works with both IPv4 and IPv6 and can be used as both `label_filter` and `line_filter`

`pattern` can be one of the following.
1. Single IP - e.g: `192.168.0.1`, `::1`
2. IP Range - e.g: `192.168.0.1-192.189.10.12`, `2001:db8::1-2001:db8::8`
3. CIDR - e.g: `192.168.4.5/16`, `2001:db8::/32`

Example queries:
1.  `{ foo = "bar" }|=ip("192.168.4.5/16")
2. `{ foo = "bar" }|logfmt|addr=ip("192.168.4.5/16")`
2. `{ foo = "bar" }|logfmt|remote_addr=ip("2001:db8::1-2001:db8::8")|level="error"`

**Which issue(s) this PR fixes**:
Fixes #2722 

**Special notes for your reviewer**:
Based on the [design doc](https://docs.google.com/document/d/1tTevtkZ5fmyzbEoYIpAkMpyA3xNMkff-QMYK4jlSlXM/edit#heading=h.2rwixxvuhsi) 

**Checklist**
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

File: pkg/logql/log/ip_test.go [hunk 1]
```diff
@@ -0,0 +1,161 @@
...
+		})
+	}
+}
+
+func Benchmark_IPFilter(b *testing.B) {
+	b.ReportAllocs()
+
+	line := [][]byte{
+		[]byte(`vpn 192.168.0.0 connected to vm`),
+		/// todo add more cases,long line without match, with match etc....
```
Comment (cyriltovena) [inline pkg/logql/log/ip_test.go:137]: Let's add those case now.

Comment (kavirajk) [reply pkg/logql/log/ip_test.go]: Good catch!

Sure. Added some more cases.

I see following benchmark, with allocations.

```
goos: linux
goarch: amd64
pkg: github.com/grafana/loki/pkg/logql/log
cpu: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
Benchmark_IPFilter
Benchmark_IPFilter/127.0.0.1
Benchmark_IPFilter/127.0.0.1-4         	   94678	     12858 ns/op	     885 B/op	      10 allocs/op
Benchmark_IPFilter/192.168.0.1-192.189.10.12
Benchmark_IPFilter/192.168.0.1-192.189.10.12-4         	   95152	     13049 ns/op	     884 B/op	      10 allocs/op
Benchmark_IPFilter/192.168.4.5/16
Benchmark_IPFilter/192.168.4.5/16-4                    	   99135	     12112 ns/op	     885 B/op	      10 allocs/op

```

it has 10 allocs/op. should I optimize it to zero allocs?

File: pkg/logql/expr.y [hunk 2]
```diff
@@ -286,6 +289,9 @@ jsonExpressionList:
   | jsonExpressionList COMMA jsonExpression { $$ = append($1, $3) }
   ;
 
+ipLabelFilter:
+    IDENTIFIER EQ IP OPEN_PARENTHESIS STRING CLOSE_PARENTHESIS { $$ = log.NewIPLabelFilter($5, $1) }
```
Comment (cyriltovena) [inline pkg/logql/expr.y:293]: Should you also support inequality ?

File: pkg/logql/log/ip.go [hunk 3]
```diff
@@ -0,0 +1,216 @@
...
+		}
+	}
+	return false
+}
+
+// `Process` implements `Stage` interface
+func (ipf *IPFilter) Process(line []byte, lbs *LabelsBuilder) ([]byte, bool) {
+
+	// make sure the pattern provided was valid, even before trying to match.
+	if ipf.patternError != nil {
```
Comment (cyriltovena) [inline pkg/logql/log/ip.go:114]: This can be spotted before and so should return an error during query parsing.

File: pkg/logql/log/ip.go [hunk 4]
```diff
@@ -0,0 +1,216 @@
...
+}
+
+func NewIPLabelFilter(pattern string, label string) *IPFilter {
+	filter := NewIPFilter(pattern)
+	filter.labelName = label
+	filter.matchType = IPMatchLabel
+	return filter
+}
+
+func (ipf *IPFilter) Filter(line string) bool {
```
[the remark this answers is not in the document]
Comment (cyriltovena) [reply pkg/logql/log/ip.go:65]: This would allow you to avoid allocations.

File: pkg/logql/log/ip.go [hunk 5]
```diff
@@ -0,0 +1,216 @@
...
+		}
+		input = v
+	}
+
+	return line, ipf.Filter(input)
+}
+
+// `RequiredLabelNames` implements `Stage` interface
+func (ipf *IPFilter) RequiredLabelNames() []string {
+	return []string{}
```
Comment (cyriltovena) [inline pkg/logql/log/ip.go:135]: You should returns the label name if it exists.

**Review by cyriltovena — COMMENTED** [review]
Looking good ! I've left some comments.

File: pkg/logql/log/ip.go (hunk 3 above)
Comment (kavirajk) [reply pkg/logql/log/ip.go:114]: Yea. thought about that actually. My previous implementation had thrown this error during constructor of `NewIPFilter()` but while writing grammar, there was no way to handle that error while creating the `LabelFilter` expression!. So I changed it to like this. 

May be I'm missing something about handling this error during the parse stage?. Can you point me any example?

**Comment by kavirajk** [comment]
@cyriltovena addressed your comments. can you take a look again? thanks

File: docs/sources/logql/ip.md [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+```
+3.180.71.3 - - [17/May/2015:08:05:32 +0000] "GET /downloads/product_1 HTTP/1.1" 304 0 "-" "Debian APT-HTTP/1.3 (0.8.16~exp12ubuntu10.21)"
+93.180.71.3 - - [17/May/2015:08:05:26 +0000] "GET /downloads/product_1 HTTP/1.1" 404 324 "-" "Debian APT-HTTP/1.3 (0.8.16~exp12ubuntu10.21)"
+```
+
+but wait! what `93.180.71.3` is doing here?. Oh yea. it actually matches with what we queried for `3.180.71.3`. It can also match with other log lines which we don't actually want. The right option would be to use regexp to match the IP address(something like `|~"^3.180.71.3"`).
+
+Now forget about single IP, what about range of IP addresses? What about IP subnet? Or even more interesting IPv6 addresses? (not easy to come up with regexp for all the use cases).
+
+Luckily, LogQL comes with built-in support for IP matcher.
```
Comment (dannykopping) [inline docs/sources/logql/ip.md:31]: I don't think we need to present the need for the parser; I think that's relatively self-explanatory.

File: docs/sources/logql/ip.md [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+Following query return log lines that *doesn't* match with given IPv4 range
+
+```logql
+`{ foo = "bar" }!=ip("192.168.4.5-192.168.4.20")
+```
+
+- Label Filter
+
+```logql
+{ foo = "bar" }|logfmt|remote_addr=ip("2001:db8::1-2001:db8::8")|level="error"
```
Comment (dannykopping) [inline docs/sources/logql/ip.md:65]: Let's format these queries to make them more readable:

```logql
{ foo = "bar" }
  | logfmt
  | remote_addr=ip("2001:db8::1-2001:db8::8")
  | level="error"
```

**Review by dannykopping — COMMENTED** [review]
Generally looks good! Left a couple nits.

Also:
https://admin-dev-us-central-0.grafana.net/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22loki-boltdb-shipper%22,%7B%22exemplar%22:true,%22expr%22:%22count%20by%20(the_real_ip)%20(count_over_time(%7Bcontainer%3D%5C%22ingress-nginx%5C%22%7D%20%7C%20json%20%7C%20the_real_ip%20%3D%20ip(%5C%2210.0.0.1-8.0.0.1%5C%22)%5B1m%5D))%22%7D%5D

When using an invalid IP range `ip("10.0.0.1-8.0.0.1")` i'm returned "query error EOF"; I think we should improve that UX by returning a more clear error.

File: pkg/logql/log/ip.go (hunk 3 above)
Comment (cyriltovena) [reply pkg/logql/log/ip.go]: You can use the `Stage()` method of this expr, it can return an errors and will be considered as 400.

File: pkg/logql/expr.y [hunk 8]
```diff
@@ -237,9 +243,19 @@ pipelineStage:
   | PIPE labelFormatExpr         { $$ = $2 }
   ;
 
+filterOp:
+  IP { $$ = OpFilterIP }
+  ;
+
+lineFilter:
+    filter STRING                                             { $$ = newLineFilterExpr($1, "", $2,) }
```
Comment (cyriltovena) [inline pkg/logql/expr.y:251]: Can you indent this correctly please, this is to match the `{` below.

File: pkg/logql/log/ip.go [hunk 9]
```diff
@@ -0,0 +1,290 @@
...
+func (f *IPLineFilter) filterTy(line []byte, ty labels.MatchType) bool {
+	if ty == labels.MatchNotEqual {
+		return !f.ip.filter(line)
+	}
+	return f.ip.filter(line)
+}
+
+// `String` implements fmt.Stringer inteface, by which also implements `LabelFilterer` inteface.
+func (f *IPLineFilter) String() string {
+	// return fmt.Sprintf("%s%sip(%q)", ipf.labelName, eq, ipf.pattern) // label filter
```
Comment (cyriltovena) [inline pkg/logql/log/ip.go:80]: I don't think you need this ?

Comment (cyriltovena) [reply pkg/logql/log/ip.go:80]:
```
type Filterer interface {
	Filter(line []byte) bool
	ToStage() Stage
}
```

String is not required.

File: pkg/logql/log/ip.go [hunk 10]
```diff
@@ -0,0 +1,296 @@
...
+}
+
+// PatternError will be used `labelFilter.Stage()` method so that, if the given pattern is wrong
+// it retuns proper 400 error to the client of LogQL.
+func (f *IPLabelFilter) PatternError() error {
+	return f.patError
+}
+
+func (f *IPLabelFilter) filterTy(line []byte, ty LabelFilterType, lbs *LabelsBuilder) bool {
+	if f.patError != nil {
```
Comment (cyriltovena) [inline pkg/logql/log/ip.go:118]: We don't need this anymore. The filter won't run if it's a wrong.

File: pkg/logql/log/ip.go [hunk 11]
```diff
@@ -0,0 +1,296 @@
...
+	}
+
+	switch ty {
+	case LabelFilterEqual:
+		return f.ip.filter([]byte(input))
+	case LabelFilterNotEqual:
+		return !f.ip.filter([]byte(input))
+	}
+	// any other operation not supported
+	lbs.SetErr(fmt.Sprintf("%q, %s", ty, ErrIPFilterInvalidOperation))
```
Comment (cyriltovena) [inline pkg/logql/log/ip.go:136]: This should be validated too and not be there. Although I don't think it's possible. You might just want to remove it.

File: pkg/logql/log/ip.go [hunk 12]
```diff
@@ -0,0 +1,296 @@
...
+	return f.patError
+}
+
+func (f *IPLabelFilter) filterTy(line []byte, ty LabelFilterType, lbs *LabelsBuilder) bool {
+	if f.patError != nil {
+		lbs.SetErr(f.patError.Error())
+		return false
+	}
+
+	input, ok := lbs.Get(f.label)
```
Comment (cyriltovena) [inline pkg/logql/log/ip.go:123]: Other filter behave differently.

```
if lbs.HasErr() {
		// if there's an error only the string matchers can filter it out.
		return line, true
	}
	v, ok := lbs.Get(d.Name)
	if !ok {
		// we have not found this label.
		return line, false
	}
```

It should do the same.

File: pkg/logql/ast.go [hunk 13]
```diff
@@ -283,14 +293,32 @@ func (e *lineFilterExpr) String() string {
...
 	return sb.String()
 }
 
 func (e *lineFilterExpr) Filter() (log.Filterer, error) {
-	f, err := log.NewFilter(e.match, e.ty)
-	if err != nil {
-		return nil, err
+	var f log.Filterer
+
+	if e.op == OpFilterIP {
```
Comment (cyriltovena) [inline pkg/logql/ast.go:310]: nit: a switch might be better.

**Review by cyriltovena — APPROVED** [review]
LGTM

**Comment by cyriltovena** [comment]
@dannykopping @KMiller-Grafana Are we good to go ?

**Review by dannykopping — APPROVED** [review]

**Comment by KMiller-Grafana** [comment]
Looks good to me.  I've added an extra task to my personal to-do list to correct the weights in the docs files associated with this PR after this PR is merged in.

**Comment by cyriltovena** [comment]
@kavirajk  can up resolve conflicts and regenerate the y.go files.

**Comment by kavirajk** [comment]
@cyriltovena conflicts resolved. Can you merge it?
