### PR TITLE
Fix single job with multiple service discovery elements

### LINKED ISSUE #1754: Promtail: allow single job with multiple service discovery elements
Users can't configure a single job with two different service discovery entries:

```yaml
- job_name: job
  static_configs:
    - targets:
        - localhost
      labels:
        name: a
        job: job
        __path__: /data/file.a.log
    - targets:
        - localhost
      labels:
        name: b
        job: job
        __path__: /data/file.b.log
```

When using this config, Promtail will only use the latest element in the array. I believe 
[these lines](https://github.com/grafana/loki/blob/8df56cea6e3830a505d7f455894cd72c474f4c50/pkg/promtail/targets/filetargetmanager.go#L111-L122) are the cause.

### PR DESCRIPTION
**Pull request by adityacs**
**What this PR does / why we need it**:
Fix single job with multiple service discovery elements

**Which issue(s) this PR fixes**:
Fixes #1754 

@rfratto Kindly review

### CODE REVIEW

File: pkg/promtail/targets/filetargetmanager.go [hunk 1]
```diff
@@ -120,6 +120,12 @@ func NewFileTargetManager(
 		}
 		tm.syncers[cfg.JobName] = s
 		config[cfg.JobName] = cfg.ServiceDiscoveryConfig
+
+		// Add Source value to the static config target groups for unique identification
+		// within scrape pool.
+		for i, tg := range cfg.ServiceDiscoveryConfig.StaticConfigs {
+			tg.Source = fmt.Sprintf("%d", i)
+		}
```
Comment (rfratto) [inline pkg/promtail/targets/filetargetmanager.go]: Could this be moved before `targetSyncer` is initialized? I understand that this will work as-is (given that `StaticConfigs` is a pointer) but I'd prefer to treat it as a dependency of configuring the `targetSyncer`.

Comment (adityacs) [reply pkg/promtail/targets/filetargetmanager.go]: Made the changes

Comment (adityacs) [reply pkg/promtail/targets/filetargetmanager.go]: We can even add this here https://github.com/grafana/loki/blob/master/pkg/promtail/targets/manager.go#L54

Comment (rfratto) [reply pkg/promtail/targets/filetargetmanager.go]: Yeah, I had looked into other places to add it but I think where you have it now makes the most sense - it's the only place in the code where we use SD configs so it feels tidy to keep it close to where it's being used.

Comment (adityacs) [reply pkg/promtail/targets/filetargetmanager.go]: Cool! Thanks

**Comment by zswanson** [comment]
@adityacs @rfratto  this seems to have regressed, I'm seeing the same issue in promtail 1.6.0 with a similar config as the original issue.

```
scrape_configs:
  - job_name: centos
    pipeline_stages: [<stuff>]
    static_configs:
      - targets: ['localhost']
        labels:
          job: varlogs
          __path__: /var/log/messages
      - targets: ['localhost']
        labels:
          job: varlogs
          __path__: /var/log/secure
```

**Comment by adityacs** [comment]
@zswanson This is not a regression. You have to make sure the labels are unique. Try following configuration

```yaml
static_configs:
      - targets: ['localhost']
        labels:
          job: varlogs
          log_name: messages
          __path__: /var/log/messages
      - targets: ['localhost']
        labels:
          job: varlogs
          log_name: secure_log
          __path__: /var/log/secure
```

**Comment by zswanson** [comment]
I see, ok. I thought that the `__path__` internal label, that gets translated to `filename` when stored in loki, handled that uniqueness.
