### PR TITLE
fix: ensure to return delete requests only for the requested tanent

### LINKED ISSUE #18585: Sharing delete requests between different tenants/users (prefix match)
**Describe the bug**
Delete request matching in the boltdb implementation uses prefix search (https://github.com/grafana/loki/blob/7de56e290a84ca0132edbd023d9d8cd6eac19201/pkg/compactor/deletion/delete_requests_store_boltdb.go#L208) to find delete requests corresponding to a particular tenant. As a result, a delete request for tenant `tenant-123` is also returned for tenants `tenant-12` and `tenant-1` and `t`, etc.

**To Reproduce**
1. Started Loki (v3.5.3) backed by S3 storage with retention enabled.
2. Send a delete request with X-OrgID: tenant-123 via POST at `loki/api/v1/delete`
3. List delete requests wit X-OrgID: tenant-12 via GET at `loki/api/v1/delete`
4. See the previously added delete request for tenant-123 there under tenant-12

**Expected behavior**
Expect to see no delete requests under tenant-12.

**Environment:**
 - Infrastructure: Kubernetes, microservice deployment mode.
 - Deployment tool: helm

**Impact**
Although, the data for the wrong user/tenant `tenant-12` is not deleted in S3. Any query for it will filter it out due to the delete request being present. It seems that the querier uses the same compactor endpoint (GET at `loki/api/v1/delete`) to get the existing delete requests for the tenant and thus it is filtering the result data also for the wrong tenant.

### PR DESCRIPTION
**Pull request by tsaikat**
**What this PR does / why we need it**:
When api used to query delete requests for a tanent/userID, this we returning delete requests for all tanent with similar prefix in their name. For example when getting delete request for `tanent-1` we also endup getting delete requests for `tenant-12` because their prefix match.
In this PR, This will filter out the irrelevant delete requests and only return the one that is exact match with the provided tenant/userID. (Test included)
 

**Which issue(s) this PR fixes**:
Fixes #18585

### CODE REVIEW

File: pkg/compactor/deletion/delete_requests_store_boltdb.go [hunk 1]
```diff
@@ -211,7 +211,14 @@ func (ds *deleteRequestsStoreBoltDB) GetAllDeleteRequestsForUser(ctx context.Con
...
 
-	deleteRequests := mergeDeletes(deleteGroups)
+	filteredDeleteGroups := []DeleteRequest{}
+	for _, dr := range deleteGroups {
+		if dr.UserID == userID {
+			filteredDeleteGroups = append(filteredDeleteGroups, dr)
+		}
+	}
+
+	deleteRequests := mergeDeletes(filteredDeleteGroups)
```
Comment (sandeepsukhani) [inline pkg/compactor/deletion/delete_requests_store_boltdb.go]: We can avoid doing this by using `[]byte(userID + ":")` for `RangeValuePrefix` on line 208. This would also let us fetch only the required records from the database.

**Review by sandeepsukhani — COMMENTED** [review]
Thank you for fixing the issue! I have left a minor comment to improve the fix a bit.
Can you please take care of it?

File: pkg/compactor/deletion/delete_requests_store_boltdb.go (hunk 1 above)
Comment (tsaikat) [reply pkg/compactor/deletion/delete_requests_store_boltdb.go]: Makes sense. done!

**Review by sandeepsukhani — APPROVED** [review]
