### PR TITLE
prevents duplicate log lines from being replayed. closes #3378

### LINKED ISSUE #3378: WAL introduces duplicates.
**Describe the bug**

I was chasing for a bug and realized that the WAL when rolling out introduces duplicates entries next to each other in a chunk block.
I added a log line to prove it and every times I do a rollout I can see duplicates showing up. The push path protects from dupes thus why.

**Expected behavior**

No duplicates 🤷‍♂️ .

**Screenshots, Promtail config, or terminal output**

<insert duplicate screenshot>

/cc @owen-d

### PR DESCRIPTION
**Pull request by owen-d**

### CODE REVIEW

File: pkg/ingester/recovery_test.go [hunk 1]
```diff
@@ -190,3 +195,83 @@ func Test_InMemorySegmentRecover(t *testing.T) {
...
+			Labels: `{bar="baz1", foo="bar"}`,
+			Entries: []logproto.Entry{
+				{
+					Timestamp: time.Unix(1, 0),
+					Line:      "line 1",
+				},
+			},
+		},
+	}
+	require.Equal(t, expected, result.resps[0].Streams)
```
Comment (kavirajk) [inline pkg/ingester/recovery_test.go:276]: suggestion:  better to add length check before this equality check.?

Rationale:
1.  Assert errors looks better than panic :) (in case of failure or duplicates)
2. Plus checking for length == 1, make sure there are no duplicates more precisely? Now there can be resp[1] right? we never know.
e.g
```suggestion
	require.Equal(t, len(result.reps), 1)
	require.Equal(t, expected, result.resps[0].Streams)
```

**Review by slim-bean — APPROVED** [review]
LGTM

@kavirajk your feedback is good but I would like to get this merged and into our internal release so I'm going to merge as is!
