### PR TITLE
Clearer error response from push endpoint when labels are malformed

### LINKED ISSUE #1727: /api/prom/push produce error 400 with 'unexpected IDENTIFIER'
**Describe the bug**
When trying to submit stream thru api endpoint "/api/prom/push" loki return error code 400 with not helpful message "parse error at line 1, col 1: syntax error: unexpected IDENTIFIER"

**To Reproduce**
1 clone grafana/loki from https://github.com/grafana/loki
2 Run docker-compose up
3 Using chrome plugin ARC create POST request with based on documentation from https://github.com/grafana/loki/blob/v1.3.0/docs/api.md#get-lokiapiv1labels:

    URL: http://localhost:3100/api/prom/push
    Body content: application/json
    body: {"streams":[{"labels":"cat","entries":[{"ts":"2018-12-18T08:28:06.801064-04:00","line":"fizzbuzz"}]}]}

CURL output:
c:\test\loki\production\loki-mixin>curl -H "Content-Type: application/json" -X POST "http://localhost:3100/api/prom/push" -d "{\"streams\": [{ \"labels\": \"cats\", \"entries\": [{ \"ts\": \"2018-12-18T08:28:06.801064-04:00\", \"line\": \"fizzbuzz\" }] }]}"
parse error at line 1, col 1: syntax error: unexpected IDENTIFIER

4 Loki server return "parse error at line 1, col 1: syntax error: unexpected IDENTIFIER"

**Expected behavior**
HTTP status code 2XX or better explanation what is missing/incorrect

**Environment:**
 - Infrastructure: laptop, windows 10, docker-compose
 - Deployment tool: docker-compose

### PR DESCRIPTION
**Pull request by talham7391**
**What this PR does / why we need it**:
Currently, when users use the `/loki/api/v1/push` with a malformed `labels`, they get an error response saying something along the lines of:
`parse error at line 1, col 4: literal not terminated`.

It isn't clear that the `labels` are the issue. This PR makes it clear.

**Which issue(s) this PR fixes**:
Fixes #1727 

**Checklist**
- [x] Documentation added
- [x] Tests updated

### CODE REVIEW

**Comment by talham7391** [comment]
I signed the agreement, made sure my emails are attached as well. Not sure why it says I haven't signed it 🤔

**Comment by slim-bean** [comment]
Hi @talham7391 thanks for the PR!

It looks like the email associated with the commit is not valid and therefore github can't link it to your account.

You would need to `git config --global user.email "email@example.com"` with an email associated to your github account and re-write the commit/force push back to the PR I think for the CLA to be happy.

**Comment by talham7391** [comment]
Thanks! @slim-bean

File: pkg/distributor/validator.go [hunk 1]
```diff
@@ -59,6 +60,7 @@ func (v Validator) ValidateLabels(userID string, labels string) error {
 		// an orthogonal concept (we need not use ValidateLabels in this context)
 		// but the upstream cortex_validation pkg uses it, so we keep this
 		// for parity.
+		err = fmt.Errorf("error parsing labels: %v", err)
 		return httpgrpc.Errorf(http.StatusBadRequest, err.Error())
```
Comment (cyriltovena) [inline pkg/distributor/validator.go]:
```suggestion
		return httpgrpc.Errorf(http.StatusBadRequest,"error parsing labels: %v", err)
```
