### PR TITLE
Fix panic in instant query splitting when using unwrapped rate

### LINKED ISSUE #6344: Panic due to `unwrap` in mapped range vector in query planning
There's a panic @cstyan is looking into in the range-splitting code. When handling a `rate(foo | unwrap)`, we map it to `(count_over_time(split1) + count_over_time(split2) ..etc ) / duration`, but `count_over_time` doesn't support unwrap! There's also a little nit that it doesn't support _extrapolated rates_: https://github.com/grafana/loki/blob/main/pkg/logql/range_vector.go#L236

What if we changed the optimization to the following:
```(rate(split1) * split1_duration + rate(split2) * split2_duration ..etc) / total_duration```

cc @cyriltovena @slim-bean @ssncferreira @chaudum

### PR DESCRIPTION
**Pull request by chaudum**
**What this PR does / why we need it**:

The range aggregation `rate()` supports both log ranges and unwrapped ranges, e.g.

`rate({app="foo"} [$__interval])` and `rate({app="foo"} | unwrap bar [$__interval])`

Since `rate()` was split into multiple `count_over_time()` over total duration, but `count_over_time()` does not support `unwrap`, unwrapped rate queries caused panics.

This fix changes the splitting of `rate({app="foo"} | unwrap bar [$__interval]` into multiple `sum_over_time()` over total duration.

Signed-off-by: Christian Haudum <christian.haudum@gmail.com>

**Which issue(s) this PR fixes**:

Fixes #6344

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated
- [ ] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`

### CODE REVIEW

File: pkg/logql/rangemapper.go [hunk 1]
```diff
@@ -373,7 +375,15 @@ func (m RangeMapper) mapRangeAggregationExpr(expr *syntax.RangeAggregationExpr,
...
 			return expr
 		}
-		return m.sumOverFullRange(expr, vectorAggrPushdown, syntax.OpRangeTypeCount, rangeInterval, recorder)
+		// rate({app="foo"}[2m]) =>
+		// => (sum without (count_over_time({app="foo"}[1m]) ++ count_over_time({app="foo"}[1m]) offset 1m) / 120)
+		op := syntax.OpRangeTypeCount
+		if expr.Left.Unwrap != nil {
+			// rate({app="foo"} | unwrap bar [2m])
+			// => (sum without (sum_over_time({app="foo"}[1m]) ++ sum_over_time({app="foo"}[1m]) offset 1m) / 120)
+			op = syntax.OpRangeTypeSum
```
Comment (ssncferreira) [inline pkg/logql/rangemapper.go:384]: I'm a bit confused 😕   are we sure this is equivalent to `sum_over_time`? 
In this case, it would also be useful to add a test to `pkg/logql/downstream_test.go` to compare with the normal engine

Comment (chaudum) [reply pkg/logql/rangemapper.go:384]: Yes, I should add a downstream test :+1:

Comment (chaudum) [reply pkg/logql/rangemapper.go:384]: Instead of counting log lines for the rate, it sums the individual unwrap values.

Comment (chaudum) [reply pkg/logql/rangemapper.go:384]: :thinking: Maybe not ...

Comment (chaudum) [reply pkg/logql/rangemapper.go:384]: I think I understood unwrapped rate incorrectly. It does not sum the unwrapped values, but treats them as counter, which is treated as reset, when a subsequent value is smaller than the preceding one.
See
https://github.com/grafana/loki/blob/main/pkg/logql/range_vector.go#L227
and
https://github.com/grafana/loki/blob/main/pkg/logql/range_vector.go#L248-L256

Comment (chaudum) [reply pkg/logql/rangemapper.go:384]: Waiting for https://github.com/grafana/loki/pull/6361 to revert `rate` calculation.

Comment (chaudum) [reply pkg/logql/rangemapper.go:384]: @ssncferreira Rebased this PR with `main` and now the added tests pass :)

File: pkg/logql/rangemapper_test.go [hunk 2]
```diff
@@ -1471,6 +1479,23 @@ func Test_SplitRangeVectorMapping(t *testing.T) {
...
+		// regression test queries
+		{
+			`topk(10,sum by (org_id) (rate({container="query-frontend",namespace="loki"} |= "metrics.go" | logfmt | unwrap bytes(total_bytes) | __error__="" [3m])))`,
+			`topk(10,
+			  sum by (org_id) (
+					(
+						sum without(
+							   downstream<sumby(org_id)(sum_over_time({container="query-frontend",namespace="loki"} |= "metrics.go" | logfmt | unwrapbytes(total_bytes) | __error__="" [1m] offset 2m0s)),shard=<nil>>
+              ++ downstream<sumby(org_id)(sum_over_time({container="query-frontend",namespace="loki"} |= "metrics.go" | logfmt | unwrapbytes(total_bytes) | __error__="" [1m] offset 1m0s)),shard=<nil>>
+							++ downstream<sumby(org_id)(sum_over_time({container="query-frontend",namespace="loki"} |= "metrics.go" | logfmt | unwrapbytes(total_bytes) | __error__="" [1m])),shard=<nil>>
```
Comment (ssncferreira) [inline pkg/logql/rangemapper_test.go:1492]: Small nit 👀 

```suggestion
							   downstream<sum by(org_id)(sum_over_time({container="query-frontend",namespace="loki"} |= "metrics.go" | logfmt | unwrap bytes(total_bytes) | __error__="" [1m] offset 2m0s)),shard=<nil>>
              ++ downstream<sum by(org_id)(sum_over_time({container="query-frontend",namespace="loki"} |= "metrics.go" | logfmt | unwrap bytes(total_bytes) | __error__="" [1m] offset 1m0s)),shard=<nil>>
							++ downstream<sum by(org_id)(sum_over_time({container="query-frontend",namespace="loki"} |= "metrics.go" | logfmt | unwrap bytes(total_bytes) | __error__="" [1m])),shard=<nil>>
```

**Review by ssncferreira — APPROVED** [review]
LGTM! Great job 🚀 
Just a small nit on the test to ease readability
