### PR TITLE
operator: Add RBAC for Prometheus service discovery to Loki component metrics (OpenShift)

### LINKED ISSUE #5563: operator: Prometheus fails to scrape loki component metrics on OpenShift
**Describe the bug**
After switching the default installation namespace by #5440 from `openshift-logging` to `openshift-operators-redhat`, the OpenShift default Prometheus service account is not able to do service discovery for LokiStack owned services on `openshift-logging` anymore. In turn any instances of LokiStack in other namespaces than `openshift-operators-redhat` cannot be scraped for metrics.

**Expected behavior**
Any instance of Lokistack services is accessible by the OpenShift Prometheus to scrape metrics

**Environment:**
 - Infrastructure: OpenShift 4.9
 - Deployment tool: `make olm-deploy`

**Screenshots, Promtail config, or terminal output**
```
$ kubectl logs -n openshift-monitoring prometheus-k8s-0
ts=2022-03-07T13:39:53.611Z caller=log.go:168 level=error component=k8s_client_runtime func=ErrorDepth msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:448: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:openshift-monitoring:prometheus-k8s\" cannot list resource \"services\" in API group \"\" in the namespace \"openshift-logging\""
```

### PR DESCRIPTION
**Pull request by periklis**
**What this PR does / why we need it**:
This PR adds the capability to reconcile RBAC for the OpenShift `openshift-monitoring:prometheus-k8s` serviceaccount to scrape LokiStack owned Loki components (e.g. distributor, ingester) metrics.

**Which issue(s) this PR fixes**:
Fixes #5563

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [x] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

File: operator/internal/manifests/mutate.go [hunk 1]
```diff
@@ -127,10 +127,9 @@ func mutateClusterRole(existing, desired *rbacv1.ClusterRole) {
 }
 
 func mutateClusterRoleBinding(existing, desired *rbacv1.ClusterRoleBinding) {
+	existing.Annotations = desired.Annotations
 	existing.Labels = desired.Labels
 	existing.Subjects = desired.Subjects
-	existing.RoleRef = desired.RoleRef
-	existing.Subjects = desired.Subjects
```
Comment (periklis) [inline operator/internal/manifests/mutate.go:133]: This is probably an old hindsight, according to the official docs, roleRefs are immutable:
```
After you create a binding, you cannot change the Role or ClusterRole that it refers to. If you try to change a binding's roleRef, you get a validation error. If you do want to change the roleRef for a binding, you need to remove the binding object and create a replacement.
```
Source: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#clusterrolebinding-example

**Review by xperimental — CHANGES_REQUESTED** [review]
In addition to the comments: it seems weird to me that we need to create our own "prometheus role" with cluster-wide access.

The existing `prometheus-k8s` ClusterRole/Binding seems to already provide the `/metrics` access. Is it possible that we just need a Role/Binding for the namespaced resources instead?

File: operator/internal/manifests/openshift/monitoring_rbac.go [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+// BuildMonitoringClusterRole returns a ClusterRole resource that
+// defines GET access to the non-resource URL `/metrics` on pods,
+// services and endpoints.
+func BuildMonitoringClusterRole(opts Options) *rbacv1.ClusterRole {
+	return &rbacv1.ClusterRole{
+		TypeMeta: metav1.TypeMeta{
+			Kind:       "ClusterRole",
+			APIVersion: rbacv1.SchemeGroupVersion.String(),
+		},
+		ObjectMeta: metav1.ObjectMeta{
```
[the remark this answers is not in the document]
Comment (periklis) [reply operator/internal/manifests/openshift/monitoring_rbac.go:22]: Actually kube garbage collection rules disallows having ownerRefs from namespace-scoped resources (e.g. LokiStack) to cluster-scoped resources: https://kubernetes.io/docs/concepts/architecture/garbage-collection/#owners-dependents

FYI, this poisons the kube gargabe collector and you have sometimes deleted CRs out of nowhere.

File: operator/internal/manifests/openshift/var.go [hunk 3]
```diff
@@ -37,6 +37,14 @@ func clusterRoleName(opts Options) string {
 	return opts.BuildOpts.GatewayName
 }
 
+func monitoringRoleName(stackName string) string {
+	return fmt.Sprintf("%s-metrics-reader", stackName)
```
Comment (xperimental) [inline operator/internal/manifests/openshift/var.go:41]: As we have surmised by now this change affects Prometheus' service discovery more than the actual scrape. Is `metrics-discovery` a better name?

File: operator/internal/manifests/openshift/var.go [hunk 4]
```diff
@@ -37,6 +37,14 @@ func clusterRoleName(opts Options) string {
...
+}
+
+func monitoringRoleBindingName(stackName string) string {
+	return fmt.Sprintf("read-%s-metrics", stackName)
```
Comment (xperimental) [inline operator/internal/manifests/openshift/var.go:45]: I think this made sense when the binding was a non-namespaced object, but I think now the usual naming convention can be used.

File: operator/internal/manifests/mutate.go [hunk 5]
```diff
@@ -61,6 +61,16 @@ func MutateFuncFor(existing, desired client.Object) controllerutil.MutateFn {
 			wantCrb := desired.(*rbacv1.ClusterRoleBinding)
 			mutateClusterRoleBinding(crb, wantCrb)
 
+		case *rbacv1.Role:
+			cr := existing.(*rbacv1.Role)
```
Comment (xperimental) [inline operator/internal/manifests/mutate.go:65]: `r` or even `role`?

File: operator/internal/manifests/mutate.go [hunk 6]
```diff
@@ -61,6 +61,16 @@ func MutateFuncFor(existing, desired client.Object) controllerutil.MutateFn {
...
+			wantCr := desired.(*rbacv1.Role)
+			mutateRole(cr, wantCr)
+
+		case *rbacv1.RoleBinding:
+			crb := existing.(*rbacv1.RoleBinding)
```
Comment (xperimental) [inline operator/internal/manifests/mutate.go:70]: `rb`?

File: operator/internal/manifests/mutate_test.go [hunk 7]
```diff
@@ -306,6 +306,13 @@ func TestGetMutateFunc_MutateClusterRole(t *testing.T) {
 }
 
 func TestGetMutateFunc_MutateClusterRoleBinding(t *testing.T) {
+
```
Comment (xperimental) [inline operator/internal/manifests/mutate_test.go:309]: Unnecessary empty line

File: operator/internal/manifests/mutate_test.go [hunk 8]
```diff
@@ -315,21 +322,138 @@ func TestGetMutateFunc_MutateClusterRoleBinding(t *testing.T) {
...
+	// Partial mutation checks
+	require.Exactly(t, got.Labels, want.Labels)
+	require.Exactly(t, got.Annotations, want.Annotations)
+	require.Exactly(t, got.Rules, want.Rules)
+}
+
+func TestGetMutateFunc_MutateRoleBinding(t *testing.T) {
+	roleRef := rbacv1.RoleRef{
+		APIGroup: "rbac.authorization.k8s.io",
+		Kind:     "ClusterRole",
```
Comment (xperimental) [inline operator/internal/manifests/mutate_test.go:433]: Should probably point to a `Role`. Repeated in the `want`.

File: operator/CHANGELOG.md [hunk 9]
```diff
@@ -1,5 +1,6 @@
 ## Main
 
+- [5588](https://github.com/grafana/loki/pull/5588) **periklis**: Fix prometheus scrape access to Loki component metrics
```
Comment (xperimental) [inline operator/CHANGELOG.md:3]: Should we update the name of this PR to reflect that this is more about the SD rather than the scrape?

```suggestion
- [5588](https://github.com/grafana/loki/pull/5588) **periklis**: Create role for Prometheus service discovery to Loki component metrics
```

**Review by xperimental — CHANGES_REQUESTED** [review]
