### PR TITLE
fix: correct _extracted logic in detected fields

### LINKED ISSUE #14063: `detected_fields` API response with multiple parsers
**Describe the bug**
Currently the detected_fields API response always returns multiple parsers for detected fields, if multiple parsers were passed in the detected_fields query.

**To Reproduce**
```/detected_fields?query={service_name=](http://localhost:3000/api/datasources/uid/PDDA8E780A17E7EF1/resources/detected_fields?query={service_name=)`mimir-ruler`}    | json | logfmt | drop __error__, __error_details__ &start=2024-09-05T15:15:45.875Z&end=2024-09-05T15:20:45.875Z```

Current response: 
```
{"fields":[{"label":"method","type":"string","cardinality":1,"parsers":["json","logfmt"]},
{"label":"level_extracted","type":"string","cardinality":1,"parsers":["json","logfmt"]},
{"label":"caller","type":"string","cardinality":1,"parsers":["json","logfmt"]},
{"label":"ts","type":"string","cardinality":100,"parsers":["json","logfmt"]},
{"label":"tenant","type":"int","cardinality":5,"parsers":["json","logfmt"]},
{"label":"detected_level","type":"string","cardinality":1,"parsers":[]},
{"label":"duration","type":"duration","cardinality":100,"parsers":["json","logfmt"]},
{"label":"msg","type":"string","cardinality":1,"parsers":["json","logfmt"]}]}
```

But when just a single parser is used, e.g. json
```
/detected_fields?query={service_name=`nginx-json`} | json | drop __error__, __error_details__ &start=2024-09-05T17:52:26.113Z&end=2024-09-05T17:57:26.113Z
```
or logfmt
```
/detected_fields?query={service_name=`nginx-json`} | logfmt&start=2024-09-05T17:52:26.113Z&end=2024-09-05T17:57:26.113Z
```

Currently returns:
```
{
  "fields": [
    {"label": "referer", "type": "string", "cardinality": 100, "parsers": ["json"]},
    {"label": "protocol", "type": "string", "cardinality": 3, "parsers": ["json"]},
    ...
  ]
}
```

**Expected behavior**
detected_fields should return the desired parser to parse the values of that specific field, independent of the parsers passed into detected_fields. It is unexpected that even when using the "wrong" parser for a field is passed into detected_fields, a single parser passed into detected_fields will return the desired parser for that field, but when passing multiple parsers to detected_fields, multiple parsers are always returned.

The parser array should only contain multiple values if the field has values that need both parsers to parse.

Also we should only add `_extracted` to fields that conflict with existing stream selectors, but I think that's being addressed in another issue.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

### PR DESCRIPTION
**Pull request by trevorwhitney**
**What this PR does / why we need it**:

Explore logs passes multiple parsers in the query to `detected_fields`, which has resulted in a whole bunch of unknown edge cases. This fixes:

1. making sure `_extracted` is correctly applied when the incoming stream labels already have extracted fields because of the formatters included in the query
2. Returning the `Parsed` values on the entry being parsed if not additional parsed values are found
3. Correctly apply `logfmt` and `json` parsers to already parsed fields
4. Drop special error labels from detected fields response

**Which issue(s) this PR fixes**:
Fixes #14063

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

File: pkg/querier/querier.go [hunk 1]
```diff
@@ -1321,50 +1317,49 @@ func getParsedLabels(entry push.Entry) map[string][]string {
...
-	labels := map[string]map[string]struct{}{}
-	for _, lbl := range entry.StructuredMetadata {
-		if values, ok := labels[lbl.Name]; ok {
-			values[lbl.Value] = struct{}{}
-		} else {
-			labels[lbl.Name] = map[string]struct{}{lbl.Value: {}}
-		}
-	}
+func parseEntry(entry push.Entry, lbls *logql_log.LabelsBuilder) (map[string][]string, []string) {
+	logFmtParser := logql_log.NewLogfmtParser(false, false)
```
Comment (trevorwhitney) [inline pkg/querier/querier.go:1321]: this was part of the problem, we had strict turned on previously

File: pkg/querier/querier.go [hunk 2]
```diff
@@ -1403,12 +1420,28 @@ func streamsForFieldDetection(i iter.EntryIterator, size uint32) (logqlmodel.Str
 		// If lastEntry.Unix < 0 this is the first pass through the loop and we should output the line.
 		// Then check to see if the entry is equal to, or past a forward step
 		if lastEntry.Unix() < 0 || shouldOutput {
-			stream, ok := streams[streamLabels]
+			allLbls, err := syntax.ParseLabels(streamLabels)
```
Comment (trevorwhitney) [inline pkg/querier/querier.go:1423]: the logic added here is to extract the stream labels from the additional labels via parsing and structured metadata. this likely needs a test

File: pkg/querier/querier.go (hunk 1 above)
Comment (trevorwhitney) [reply pkg/querier/querier.go:1321]: yes, can do... missed that when I change the order to try json first
