### PR TITLE
logcli: Fix handling of logcli query using --since/--from and --tail

### LINKED ISSUE #3269: Logcli query --tail incorrectly handles --since/--from
**Describe the bug**
Logcli incorrectly sets the wrong query parameter for specifying the start time of a tail query, making --since/--from ineffective.

**To Reproduce**
```
~/p/loki(⎈ |dev-2447-us-west-2:monitoring) czibolski ❯❯❯ logcli --addr=https://loki.example.com query --no-labels '{doesnt="matter"}' --since 1s --tail                                                                                                                               master ✭ ✱ ◼
2021-01-29 12:23:13.546125 I | proto: duplicate proto type registered: ingester.Series
wss://loki.example.com/loki/api/v1/tail?delay_for=0&from=1611951792546900000&limit=30&query=%7Bdoesnt%3D%22matter%22%7D
```

Notice the query param `from` is used. It should be `start` according the API docs https://grafana.com/docs/loki/latest/api/#get-lokiapiv1tail. 

This results in all `logcli query --tail` requests to default to showing the last 1 hour of logs. 

**Expected behavior**
Logcli sets the `start` query parameter instead, properly filtering the logs based on the --since/--from time.

**Environment:**

```
~/p/loki(⎈ |dev-2447-us-west-2:monitoring) czibolski ❯❯❯ logcli --version                                                                                                                                                                                                                   master ✭ ✱ ◼
2021-01-29 12:26:20.504350 I | proto: duplicate proto type registered: ingester.Series
logcli, version 2.1.0 (branch: HEAD, revision: 1b79df37)
  build user:       root@b8941a81fe55
  build date:       2020-12-24T14:08:17Z
  go version:       go1.15.3
  platform:         darwin/amd64
  ```

### PR DESCRIPTION
**Pull request by chancez**
**What this PR does / why we need it**:
Fixes handling of `--since`/`--from` in `logcli query` when used with `--tail`.

Also changes uses of variable names in the logcli Client interface to match the
query parameter names for the Loki API for consistency.

**Which issue(s) this PR fixes**:
Fixes #3269

### CODE REVIEW

File: pkg/logcli/client/client.go [hunk 1]
```diff
@@ -131,12 +131,12 @@ func (c *DefaultClient) Series(matchers []string, from, through time.Time, quiet
 }
 
 // LiveTailQueryConn uses /api/prom/tail to set up a websocket connection and returns it
-func (c *DefaultClient) LiveTailQueryConn(queryStr string, delayFor int, limit int, from int64, quiet bool) (*websocket.Conn, error) {
+func (c *DefaultClient) LiveTailQueryConn(queryStr string, delayFor int, limit int, start int64, quiet bool) (*websocket.Conn, error) {
 	qsb := util.NewQueryStringBuilder()
 	qsb.SetString("query", queryStr)
 	qsb.SetInt("delay_for", int64(delayFor))
 	qsb.SetInt("limit", int64(limit))
-	qsb.SetInt("from", from)
```
Comment (chancez) [inline pkg/logcli/client/client.go:139]: This was the bug

**Review by sandeepsukhani — APPROVED** [review]
Thanks for the PR!
LGTM
